### ISSUE TITLE
Using reference atlas version 1 (2008)

### ISSUE THREAD

**Issue by jofrony** [brainglobe/brainrender#112]
Hi,

I am not sure if this is an appropriate place for this question. But I was wondering about the brainrender's ability of using the reference atlas version 1 (2008) of the mouse brain. The experimentalists I work with use the reference atlas version 1 (2008) to get the coordinates of the mouse brain and of course this is different from the brainrender coordinates. I tried using cellfinder but usually these are single slices and only two or three cells are filled, hence using cellfinder is not feasible (If I understand it correctly). 

Do you have any suggestions on how I could proceed? I get many requests about doing this and I would like to supply them with a solution, which I have failed with so far (a mere transformation into the coordinate space seems to be difficult to achieve, maybe?).

**Comment by FedeClaudi** [comment]
Hi, thanks for getting in touch. 

Brainrender relies on [brainglobe's atlas API](https://github.com/brainglobe/bg-atlasapi) behind the scenes to handle atlas data.
For this reason, the easiest way is probably to process the atlas data in a way that is compatible with the atlas API, you can then plug that directly into brainrener without problems. 

So I'd suggested having a look at:
- the api: https://github.com/brainglobe/bg-atlasapi
- the api docs: https://docs.brainglobe.info/
- the code we've used to generate the atlases already supported by brainglobe: https://github.com/brainglobe/bg-atlasgen

I don't know how the v1 version of the atlas is organized data-wise, but it should be fairly easy to recycle what we've done for v3 for you atlas version.  Should you have any question/problem during the atlas generation process however, I'd suggest opening an issue in the atlas API's repo as there's more people there that can help you with this kind of problem.

**Comment by FedeClaudi** [comment]
Closing as it's not a brainrender issue, feel free to open an issue about this in the BG_atlasAPI repository if you wish
