### ISSUE TITLE
controlling verbosity

### ISSUE THREAD

**Issue by bendichter** [brainglobe/brainrender#113]
```python
from brainrender.scene import Scene
Scene(verbose=False)
```

prints out

```
allen mouse atlas (res. 25um)
From: http://www.brain-map.org (Wang et al 2020, https://doi.org/10.1016/j.cell.2020.04.007 )
Setting 'display_inset' to False as this feature is not                             available in juputer notebooks
Setting window size to 'auto' as whole screen is not available in jupyter
```

Is there any way to turn these print-outs off?

**Comment by FedeClaudi** [comment]
> allen mouse atlas (res. 25um)
From: http://www.brain-map.org (Wang et al 2020, https://doi.org/10.1016/j.cell.2020.04.007 )

Come from the atlas API, but it should be possible to switch that off.

> Setting 'display_inset' to False as this feature is not                             available in juputer notebooks
Setting window size to 'auto' as whole screen is not available in jupyter

These are from brianrender and specific to usage in jupyter, but you're right they shouldn't get printed if `verbose` is `False`.

Will patch this in the next release (to come out soon hopefully)

**Comment by bendichter** [comment]
Thanks @FedeClaudi! I'm trying to incorporate this into NWBWidgets. I'm having trouble getting this to display in-line, and I think these print outs might be the issue.

**Comment by FedeClaudi** [comment]
If it's something urgent I can do it more quickly, do you need it now?

**Comment by bendichter** [comment]
I'm not 100% sure this is what is causing me problems, and I don't have a current project that requires this integration anyway, so no, just let me know when to test it out again

**Comment by FedeClaudi** [comment]
okay, will do!

**Comment by FedeClaudi** [comment]
Fixed in dev branch:
```
pip install -U git+https://github.com/marcomusy/vedo.git
pip install -U git+https://github.com/BrancoLab/brainrender.git@dev
```

**Comment by FedeClaudi** [comment]
Fixed with release: https://github.com/brainglobe/brainrender/releases/tag/1.0.1.0

Update `brainrender` and this shouldn't be an isssue anymore:
`pip install brainrender -U`
