### ISSUE TITLE
programmatically define the color of brain regions

### ISSUE THREAD

**Issue by mkunst23** [brainglobe/brainrender#115]
Hi,

I'm using brainrender to visualise brain regions of the Allen reference atlas and it works great. However, I would like to use different colors for the brain regions that the default Allen color scheme. Is there a way to set that as a properties when you add brain regions to the scene?

Here is my example code that slightly modified from one of your examples.

import brainrender
brainrender.SHADER_STYLE = "cartoon"
from brainrender.scene import Scene
from vedo import embedWindow, show 

embedWindow('k3d')  # <- this will make your scene embed as a panel

# Create a scene
scene = Scene(title='Amygdala', verbose=True)  # note that the title will not actually display

# Make sure it gets embedded in the window
scene.jupyter = True

# add individual brain regions to be displayed
scene.add_brain_regions(["AAA","IA","CEA","MEA","BLA","LA","BMA","PA","COA","PAA"], alpha=0.35)

# scene.render now will prepare the scene for rendering, but it won't render anything yet
scene.render()

#  to actually display the scene we use `vedo`'s `show` method to show the scene's actors
show(scene.actors) 

Keep up the great work!
Michael

**Comment by FedeClaudi** [comment]
You can pass a `colors` argument to `scene.add_brain_regions`. See https://github.com/brainglobe/brainrender/blob/35733a1c6554bf24ba545c0f4314334900a38dd1/brainrender/atlases/atlas.py#L148

Also `scene.add_brain_regions` returns pointers to the meshes objects so if you do
``` python
ca1 = scene.add_brain_regions('CA1')
ca1.c('red')
```
this will color the mesh accordingly

**Comment by mkunst23** [comment]
Thanks, that did the trick.
