### ISSUE TITLE
BUG custom color scheme for added brain regions gets overridden when displaying only one hemisphere

### ISSUE THREAD

**Issue by mkunst23** [brainglobe/brainrender#116]
Hi,

I"m using brainrender to display multiple brain regions of the mouse brain using the AMBA, and I manually assign the color to each brain region

scene.add_brain_regions(["AAA",
                         "IA",
                         "CEA",
                         "MEA",
                         "LA",
                         "BLA",
                         "BMA",
                         "PA",
                         "COA",
                         "PAA"],
                    
                        colors=["#FF0000",
                                "#FF4500",
                                "#ffa500",
                                "#ffff00",
                                "#32CD32",
                                "#006400",
                                "#ADD8E6",
                                "#0000A0",
                                "#D3D3D3",
                                "#A9A9A9"], 
                        use_original_color=False,
                        
                        alpha=0.35)

However, when I add the parameter:

    hemisphere="Right",

my color scheme get overwritten and all regions appear yellow

![K3D-1602805019528](https://user-images.githubusercontent.com/12502874/96196630-b5d73d80-0f04-11eb-83e1-b4c8e20c9a39.png)
![K3D-1602805086222](https://user-images.githubusercontent.com/12502874/96196674-d3a4a280-0f04-11eb-81a5-1a39a3bab2e6.png)

**Comment by FedeClaudi** [comment]
Oh dear, that's not good at all. Thanks for letting me know, I will fix this. 

In the meanwhile there's a couple things you can do:
1. You can still manually set the colors **after** you've added the actors
2. You can add the meshes without specifying the hemisphere and cut them afterwards. Something like:

``` python
import brainrender

brainrender.SHADER_STYLE = "cartoon"
from brainrender.scene import Scene


scene = Scene(use_default_key_bindings=True, title="cut with plane")

# Add some actors
th = scene.add_brain_regions(["STR", "TH"], alpha=0.5)

# Specify position, size and orientation of the plane
pos = scene.atlas._root_midpoint
sx, sy = 15000, 15000
norm = [0, 1, 0]  # ! I think that this is the correct normal for a sagittal plane
plane = scene.atlas.get_plane_at_point(
    pos, norm=norm, sx=sx, sy=sy, color="lightblue"
)

# Cut
scene.cut_actors_with_plane(
    plane,
    close_actors=False,  # set close_actors to True close the holes left by cutting
    showplane=True,
    actors=scene.root,
)

sil = scene.root.silhouette().lw(1).c("k")
scene.add_actor(sil)

scene.render(camera="top")
```

I think that 
```
norm = [0, 1, 0]  
```
is the correct norm for a sagittal plane but if that's not right you can try e.g. `[1, 0, 0]`. And if it's cutting the 'wrong' half of the brain jut invert the normal to `[0, -1, 0]`. 

Hope this helps

**Comment by mkunst23** [comment]
Hi Federico,

Unfortunately that only cuts the brain outline in half. the brain regions
on the cut side are still displayed. Also, the cutting plane is visible, is
there a way to remove it? I attached a screenshot so you know what I"m
talking about.

Thanks,
Michael

**Comment by FedeClaudi** [comment]
hey, I don't see the screenshot. 

The function you need to use is this:
```
scene.cut_actors_with_plane(
    plane,
    close_actors=False,  # set close_actors to True close the holes left by cutting
    showplane=True,
    actors=th,  # Specify which actors to cut here
)
```

if you pass `showplane=False` the plane will not be shown and you can specify which actors you want to be cut with the `actors` argument.

**Comment by mkunst23** [comment]
yes, I found something similar in the examples

# Cut with plane
scene.cut_actors_with_plane(
    "sagittal", showplane=False
)  # Set showplane to True if you want to see the plane location

**Comment by FedeClaudi** [comment]
yep, it was also in code example I've sent above ;)

**Comment by FedeClaudi** [comment]
Fixed in https://github.com/brainglobe/brainrender/releases/tag/1.1.0.0
New version to be released on `pip` by the end of the day, in the meanwhile you can install with:
``` pip install -U git+https://github.com/brainglobe/brainrender.git```
