### ISSUE TITLE
add_actor_label for export_for_web

### ISSUE THREAD

**Issue by AbdouEsi** [brainglobe/brainrender#119]
Hello
Unfortunately, the feature does not exist when exporting to the web
Is it a bug or is it not added yet?
Thank you

**Comment by FedeClaudi** [comment]
Hi, 

it's not a bug, it's due to the limitations of the backend used to export 3d renderings to .html format, as stated in the docs: https://docs.brainrender.info/usage/videos-animations-and-exporting-to-html#exporting-to-html
