### ISSUE TITLE
Improve flexibility and consistency of cell plotting

### ISSUE THREAD

**Issue by vigji** [brainglobe/brainrender#124]
ATM for plotting cells one would need to pass a pandas dataframe with the x,y,z columns, or a list of column names specifying col 1,2, and 3. 
 - The first option should be replaced for consistency with column names `ap`, `si`, `lr`
 - The second option is quite redundant syntax-wise, and should be replaced with just supporting a `(n_cells, 3)` shape numpy array (so that the user can just invoke `add_cells(df[[col1, col2, col3]].values`)

can make a PR fir this in the next days! But this will potentially break some code for the users, exp @adamltyson . Should probably go through a deprecation phase.

**Comment by adamltyson** [comment]
Would this be a good time to change the semantics, ie move from `cells` to `points`? I use cells for lots of stuff that aren’t cells.

**Comment by FedeClaudi** [comment]
yeah, both are very good points.

@adamltyson  it is true that we use `cells` for other things (e.g. points along a neuropixel), but I would say that it's  mostly used for indicating actual cells positions. Do you use `cells` for other things?

@vigji I agree with changing the columns names. 
Regarding passing a numpy array, the reason why it's the way it is at the moment is that users can pass a `df` and use another column as metadata for coloring.

**Comment by adamltyson** [comment]
>  Do you use cells for other things?

cellfinder etc. uses the concept of "points" to visualise anything that isn't a volume, this can be:
* detected cells
* any manually segmented single point
* any 1D track (probe track, fibre track)

**Comment by FedeClaudi** [comment]
okay, I propose that we rename `add_cells` and `add_cells_from_file` to use `points` instead, but also leave the two original methods and have them just raise a `DeprecatedWarning` and a message saying to use `add_points` instead. 

@vigji do you want to send a PR about this?

**Comment by vigji** [comment]
Yes, will do after Friday!

> Regarding passing a numpy array, the reason why it's the way it is at the moment is that users can pass a df and use another column as metadata for coloring.

I think this is useful but I would just point users in the docstring to how to label the columns for this to work!

**Comment by FedeClaudi** [comment]
@vigji  because I'm working on `v2.0` there's no need for the PR, I will implement this and then we can discuss this when I send in a PR for v2.0

**Comment by FedeClaudi** [comment]
Addressed in brainrender 2.0
