### ISSUE TITLE
Error in notebook-embed visualizations, even if the viz works

### ISSUE THREAD

**Issue by nantille** [brainglobe/brainrender#129]
I'm trying to run the examples from brainrender/examples in a jupyter notebook. 

Every time, it's asking that I use the show() method and I do so but I get the same error:
```
Error in silhouette(): direction is [None]
 render the scene with show() or specify camera/direction
Error in silhouette(): direction is [None]
 render the scene with show() or specify camera/direction

Your scene is ready for rendering, use: `show(scene.renderables)`
```

Thinking there was no camera, I used the CustomCamera code but the error remains:
```
from brainrender import Scene

custom_camera = {
    "pos": (41381, -16104, 27222),
    "viewup": (0, -1, 0),
    "clippingRange": (31983, 76783),
}


# Create a brainrender scene
scene = Scene(title="Custom camera")

# Add brain regions
scene.add_brain_region("CB", alpha=0.8)

# Render!
scene.render(camera=custom_camera, zoom=1.5)

show(scene.renderables)
```

I also tried to add the below code at the beginning of the code. Didn't change the result.
```
from vedo import embedWindow
embedWindow('k3d')
```

What is the usual use-case for brainrender? I'd like to extend brainrender (and also the gui) to give ready-to-use features that accept custom python data, which would run depending on the user needs either in jupyter notebooks or from the UI (less flexible). I read in the documentation that integration with jupyter nbs is limited. What are these limitations?

**Comment by nantille** [comment]
I took the notebook_workflow.ipynb from examples and the embed part works but still shows the same error mentioned above.

I see that `scenes.renderables` is unpacked as kargs in plt.show(), which differs from the above code. Though I guess this is unrealted.
```
plt = Plotter()
plt.show(*scene.renderables)
```

**Comment by FedeClaudi** [comment]
Hi, 

First thing, can you please make sure that you're using the latest vedo and brainrender with:
```
pip install vedo -U
pip install git+https://github.com/brainglobe/brainrender.git
```

After that, can you try the notebook_workflow notebook again? The first two examples work fine for me on both windows and mac. [Incidentally, I'm having some issues with the itkwidgets, @bendichter  and @marcomusy ]

If you still get errors/warning then we'll need to investigate what the cause may be, in which case knowing more about your setup (python version etc..) might help.


---
Now, for the limitations. 
As discussed in the [docs], scene's embedded in notebooks using the `K3d` backend suffer some limitations. This is not brainrender nor vedo's fault, it's with k3d. The limitations are relatively small (e.g. can't have cartoon shading, silhouettes etc) but brainrender's core functionality should work. 

The recomended approach is to have the render in a pop up window, then all of brainrender and vedo's functionality will work the same as in a python script. The itkwidgets option seems very promising, but it's somewhat experimental still. 

> What is the usual use-case for brainrender?

it's hard to say, I think most people use scripts or the GUI, but I've received many questions about notebooks too. 

In terms of extending brainrender's functionality, anything that works with normal python scripts will work if you use the pop up option in notebooks and should work fine in a GUI, happy to chat more about this.

**Comment by FedeClaudi** [comment]
Some more clarification for:
> Error in silhouette(): direction is [None]
 render the scene with show() or specify camera/direction

This is actually printed by `vedo`, not `brainrender`. I've disabled silhouettes when using embedded scenes (as they don't work anyway) so you will not get this error message any longer.

**Comment by nantille** [comment]
Thanks. Before I close this, I'm confused with the output and GUI. When I run a k3d embed notebook, I see something that looks awfully like dat.gui in JS (widely used in ThreeJS examples). There's an info box that shows JS version and Python version (2.7??).
Does this mean that visualizations embed in notebooks use something like ThreeJS, not vedo?

**Comment by FedeClaudi** [comment]
I'm not sure :)
I actually don't know what's happening behind the scenes with vedo, vtk and k3d, @marcomusy ?
Brainrender is for sure only using vedo, but what happens beyond that I'm not sure in this case.
The GUI should be using vtk (via vedo) like when using brainrender with python scripts. 

By the way, have you had a chance to play around with the GUI, is everything working with it?

**Comment by nantille** [comment]
Yes, I installed the gui as you said and it works. 

Though, when I double-click on the eye icon of "root", the camera twitches weirdly (but the functionality works). There is also a noticeable performance drop when the mouse brain envelope "root" is made visible but I suppose this is more related to vedo.

**Comment by FedeClaudi** [comment]
> Though, when I double-click on the eye icon of "root", the camera twitches weirdly (but the functionality works

Yeah.. I cannot quite figure out where that's coming from, the GUI is underdeveloped: it's a recent addition and I haven't yet heard much interest in it. As it stands it's far from perfect or complete. 
I haven't noticed any performance drop, is this with the mouse atlas?

**Comment by nantille** [comment]
Yes, running `brainrender-gui` with the UI in full screen, rotating the scene is visibly smoother without the mesh of the allen mouse brain, I know region 997 has 100k polygons. That should be a piece of cake though for that type of render. This worries me a little if I want to show hundreds of thousands of points later on (even by merging them).

**Comment by FedeClaudi** [comment]
that's very weird, I haven't noticed anything like that with simple meshes like that. 
I've also rendered very large number of points (e.g. >20k cells) wihout issues, or hundreds of neurons from MouseLight with minor performance decrements. 
Do you see the same when running brainrender from python scripts without the GUI?

**Comment by nantille** [comment]
In this case I'm running on MacOS Mojave on an old Macbook Pro. 
Yes the same thing happens with a script. Rendering is visibly not as smooth as with just the outline.
If rendering relies on the GPU, it might be a reason why it's slow on this machine. What's your take on this @marcomusy?

**Comment by FedeClaudi** [comment]
on my relatively new macbook pro (2019) it works very smoothly, weird!

**Comment by marcomusy** [comment]
> I actually don't know what's happening behind the scenes with vedo, vtk and k3d, @marcomusy ?
> Brainrender is for sure only using vedo, but what happens beyond that I'm not sure in this case.
> The GUI should be using vtk (via vedo) like when using brainrender with python scripts.

It's basically the following:
VTK works with its native rendering window which doesn't like (at the minute)  jupyter notebooks. So in that case an extra work of translation of the objects in the scene is needed to render them in the notebook using different technologies (`vedo.backends`). 
One of these is [k3d](https://github.com/K3D-tools/K3D-jupyter) which is webgl based - that's why it looks similar to three.js.
Yet some (many) features are not translatable like silhouettes, buttons, sliders, and customized axes.
One can still use `vedo` in notebooks - like any other native vtk script - by disabling the embedding and allowing the native rendering to pop up as an independent window, which is clearly not ideal.

**Comment by marcomusy** [comment]
> If rendering relies on the GPU, it might be a reason why it's slow on this machine. What's your take on this @marcomusy?

Yes - performance is affected by gpu quality, though i'm not an expert on that... 

@FedeClaudi  On my ubuntu I cannot actually run the gui! I get
```
> brainrender-gui
Bg_atlasapi: allen_mouse_25um version 0.3 is not the latest available (1.2). To 
update the atlas run in the terminal:
    brainglobe update -a allen_mouse_25um
ERROR: In /work/standalone-x64-build/VTK-source/IO/Geometry/vtkOBJReader.cxx, line 290
vtkOBJReader (0x5561ce9b0d60): Error reading 'v' at line 2

Generic Warning: In /work/standalone-x64-build/VTK-source/Interaction/Widgets/vtkOrientationMarkerWidget.cxx, line 540
Set interactor and Enabled before changing       interaction.

WARNING: QBasicTimer::start: QBasicTimer can only be used with threads started with QThread
WARNING: QBasicTimer::start: QBasicTimer can only be used with threads started with QThread
```

**Comment by FedeClaudi** [comment]
Hi Marco, 

Thanks for the detailed explanation, that makes things clearer.
Is there any update on the recently developed vtk package you showed me a while back?

----

For the GUI, I've never seen that. 
> ERROR: In /work/standalone-x64-build/VTK-source/IO/Geometry/vtkOBJReader.cxx, line 290
vtkOBJReader (0x5561ce9b0d60): Error reading 'v' at line 2

makes me think that perhaps there's something off in the .obj file for the brain's outline. 
Can you try `brainglobe update -a allen_mouse_25um` to update the atlas? That will also update the atlas' meshes. 

> Generic Warning: In /work/standalone-x64-build/VTK-source/Interaction/Widgets/vtkOrientationMarkerWidget.cxx, line 540
Set interactor and Enabled before changing       interaction.
WARNING: QBasicTimer::start: QBasicTimer can only be used with threads started with QThread
WARNING: QBasicTimer::start: QBasicTimer can only be used with threads started with QThread

I haven't seen these before either, but given that they're warnings I suppose they're not the problem here?

**Comment by marcomusy** [comment]
indeed I had an old version of the atlas.. still, I'm getting the same error message about the obj file ...

it's quite strange because i can browse all obj files normally in directory:
`~/.brainglobe/allen_mouse_25um_v1.2/meshes > vedo *obj -s`

![image](https://user-images.githubusercontent.com/32848391/100528725-061e0c80-31e0-11eb-8885-e8cb8b39ab2d.png)

**Comment by FedeClaudi** [comment]
mmm, that is very weird indeed. Honestly I am at a loss here, no idea what's causing this. 
Not having a linux machine it is hard for me to test things, but if you don't min could you try with another one of brainglobe's atlases?

The GUI replaces the default Scene's `Plotter` with one using `QVTKRenderWindowInteractor`, would that change anything about how .obj files are loaded?
