### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by ltuominen** [brainglobe/brainrender#131]
**Describe the bug**
I downloaded yesterday the version 2.0 of the brainrender. The images look gorgeous! 

When running: 
scene = Scene(title="brain regions")

I get a massive error message, which is attached here. 
[error.txt](https://github.com/brainglobe/brainrender/files/5610935/error.txt)

**To Reproduce**
Python 3.7.6 
brainrender 2.0.0.2 
vedo 2020.4.2
OSX Big Sur

Thanks so much!! 
Cheers
Lauri

**Comment by FedeClaudi** [comment]
Hi, 

Thanks for getting in touch and for the detialed report. 

Unfortunately it seems that Big Sur has problems with several core python packages, people have been reporting problems with numpy, matplotlib etc.. 
It seems like you've run into one of these issues, specifically with requests.

I'd suggest trying to create a new python environment and re installing brainrender.
Should that fail, then I fear you can only wait for this kind of problems to be solved or you can downgrade your mac. 

I will close this issue as it is not a brainrender problem, but do let me know if I can be of any help.
