### ISSUE TITLE
Jupyter notebook itkwidget error (not visible in notebook)

### ISSUE THREAD

**Issue by nantille** [brainglobe/brainrender#132]
This example does not work in Jupyter notebook, the itkwidget does not show up and in my case an error is printed:
`Error displaying widget: model not found`

Code:
```
from vedo import embedWindow, show
import brainrender
from brainrender.scene import Scene

embedWindow('itkwidgets') 
brainrender.SHADER_STYLE = "cartoon"
scene = Scene(title="brain regions", inset=False)
scene.add_brain_region("TH", alpha=0.15)
val = scene.add_brain_region("VAL")
val.wireframe()scene.jupyter = True
scene.render()
from ipywidgets import VBox, Button
VBox([Button(description='hi'), show(*scene.renderables)])
```

**Comment by FedeClaudi** [comment]
Hey,

I've tried creating a fresh conda environment and re-installing everythingm didn't work. 
So I tried fully uninstalling jupyter and re-installing (see https://stackoverflow.com/questions/33052232/how-to-uninstall-jupyter/52912244#52912244) and that seems to have worked:
![image](https://user-images.githubusercontent.com/17436313/101052706-dcb60580-357e-11eb-97bf-cb049e5e6b4c.png)

Although I have no idea why but all meshes are purple and opaque. 

So my guess is that we both have something conflicting in our set up that breaks the widgets.

I guess we both have a bunch of extensions and stuff like that
![image](https://user-images.githubusercontent.com/17436313/101052860-05d69600-357f-11eb-83ce-93123a5fdb71.png)


It'd be good to try and use a completely vanilla version of jupyter, but I have no idea how to do that, do you?

**Comment by FedeClaudi** [comment]
By the way for some reason you need to run the cell twice, the first time the widget is not rendered

**Comment by FedeClaudi** [comment]
I've been trying to replicate this on my mac, where I do have Jupyter with no extensions. 
I can't get it to work, everything's fine but the window doesn't show up.
If I just have the `button` in the `VBox` then it works fine, so the problem seems to be in the inreaction between `show` and the `itkwidgets`
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/17436313/101087435-1c461700-35aa-11eb-9de8-d28148e08655.png">


I'll keep digging...

**Comment by FedeClaudi** [comment]
This code runs reliably for me now (well, you still have to run the cell twice for some reason):
```python
from vedo import embedWindow, show
import brainrender
from brainrender.scene import Scene
from itkwidgets import view

embedWindow('itkwidgets') 
brainrender.SHADER_STYLE = "cartoon"
scene = Scene(title="brain regions", inset=False)
scene.add_brain_region("TH", alpha=0.15)
val = scene.add_brain_region("VAL")
val.wireframe()

scene.jupyter = True
scene.render()

print(scene.renderables)
view(show(*scene.renderables))
```

**Comment by FedeClaudi** [comment]
Hey @nantille 

I've made some changes and it now seems to work fine for me, would you mind updating brainrender from the github repository and try the example notebook in `examples`?

**Comment by nantille** [comment]
Hey Federico,

I tried updating the pip install from github and I still get the same error, even after restarting the kernel or jupyter. I tried to install brainrender and vedo on another Ubuntu 20 workstation and I got the same error.

I'll keep trying.

**Comment by FedeClaudi** [comment]
mmm, that's very weird. It works fine for me on both mac and windows, though on windows it looks different (I think because of the extension that makes the notebooks use a dark theme, which I don't know how to remove). 

It doesn't seem to be brainrender or vedo related, but more a conflict between the notebook environment and the itkwidgets package. Have you tried re-installing itkwidgets?

**Comment by nantille** [comment]
This example with vedo works in Jupyter notebook, not in Jupyter lab (for some reason).
```
# This example works in Jupyter notebook, not in Jupyter lab

#from ipywidgets import VBox, Button
from vedo import show
from vedo import load, datadir, Sphere
from vedo import embedWindow, Plotter
from vedo import shapes
from vedo import Mesh

from itkwidgets import view

embedWindow('itkwidgets')  # <- this will make your scene embed as a panel

actor = load(datadir + 'embryo.tif')
actor.color('green')
s = Sphere(r=200, res=10).color('tomato')
view(show(actor, s))
```

**Comment by nantille** [comment]
So I guess it was related to Jupyter lab more than anything else. Your code above works in Jupyter notebook. I see the brain in a basic UI (finally!).

**Comment by FedeClaudi** [comment]
yay! that's great, finally.
Does it all look good (i.e. the meshes transparency and color is correct)?

**Comment by nantille** [comment]
You are right about having to refresh the jupyter notebook. This is odd. If I start the notebook and play the code, only text is displayed (as if you print the window object). Note that I see in the background a new python task started. When I reload the notebook and play the code again, the UI appears, though not like in your screenshot at all. I have a dark purple brain without transparency.
![vedo_ui](https://user-images.githubusercontent.com/10866779/101624262-fbeae200-3a19-11eb-9d04-8372f599351e.png)

**Comment by FedeClaudi** [comment]
Yeah, I have no idea why it needs to be ran twice. 
I see the same, but only on windows where I have some jupyter extensions installed that make, among other things, the notebooks look dark. On mac, where I have vanilla jupyter it looks fine, so my fear is that the change in colors is messing with the rendering, though that could be completely wrong. 

Unfortunately I tried removing all extensions to see if that's the cause but failed.

**Comment by FedeClaudi** [comment]
It might be worth moving this discussion to an issue in the itkwidgets repository since this is clearly not brainrender related

**Comment by nantille** [comment]
Yes, we can close this issue for now. Thanks for your help.
