### ISSUE TITLE
Error while making video using brainrender 1.0.1.1: AttributeError: 'NoneType' object has no attribute 'Elevation'

### ISSUE THREAD

**Issue by rdbcasillas** [brainglobe/brainrender#133]
Hello,

I am using brainrender Version: 1.0.1.1 within jupyter notebook inside Chrome. 

I am unable to recreate the video example mentioned in old Github "examples" repository [here].(https://github.com/brainglobe/brainrender/blob/4c087bc4cb8f94ba394dc0cf75baa646065ea44b/Examples/advanced/videomaker.py)

Following is my code: 
```
import brainrender
brainrender.SHADER_STYLE = 'cartoon'
from brainrender.scene import Scene
from brainrender.animation.video import BasicVideoMaker as VideoMaker


scene = Scene()
scene.add_brain_regions(['RN'], color="violet")

scene.add_cells_from_file("C:\\Users\\7057mehrav\\Documents\\164-test\\cells_in_standard_space.h5", radius=15,alpha=0.5)

# Create an instance of VideoMaker with our scene
vm = VideoMaker(scene, niters=30)  # niters = number of frames

# Make a video!
vm.make_video(
    elevation=1, roll=5
)  # specify how the scene rotates at each frame

```

After promising messages, I get an error: 

```
Bg_atlasapi: allen_mouse_25um version 1.1 is not the latest available (1.2). To update the 
atlas run in the terminal:
    brainglobe update -a allen_mouse_25um
allen mouse atlas (res. 25um)
From: http://www.brain-map.com (Wang et al 2020, https://doi.org/10.1016/j.cell.2020.04.007 )
Setting 'display_inset' to False as this feature is not                             available in juputer notebooks
Setting window size to 'auto' as whole screen is not available in jupyter
Added 15473 cells to the scene
Saving video in C:\Users\7057mehrav\.brainrender\Output/Videos
('\x0bideo Video', 'brainrender_video__20201203_123641', 'is open...')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-3ee3c505a465> in <module>
     15 # Make a video!
     16 vm.make_video(
---> 17     elevation=1, roll=5
     18 )  # specify how the scene rotates at each frame

c:\users\7057mehrav\appdata\local\continuum\anaconda3\envs\brainrender\lib\site-packages\brainrender\animation\video.py in make_video(self, azimuth, elevation, roll, **kwargs)
    144         for i in range(self.niters):
    145             self.scene.plotter.show()  # render(interactive=False, video=True)  # render the scene first
--> 146             self.scene.plotter.camera.Elevation(elevation)
    147             self.scene.plotter.camera.Azimuth(azimuth)
    148             self.scene.plotter.camera.Roll(roll)

AttributeError: 'NoneType' object has no attribute 'Elevation'

```

What could be causing this? I have already looked in the location where it tries to save the output but that folder is empty. Is it because I am running this functionality from within jupyter?

**Comment by FedeClaudi** [comment]
Hi, thanks for the report. 

The short answer to this
>Is it because I am running this functionality from within jupyter?

is yes.

Running brainrender in notebooks can incur into limitation, as discussed in several issues and in the [documentation](https://docs.brainrender.info/usage/using-notebooks)

You can see if setting up brainrender to pop up the rendering window (see instructions [here](https://github.com/brainglobe/brainrender/blob/master/examples/notebook_workflow.ipynb)) helps, but the example linked is for the latest `brainrender 2.0` so you might have to adjust it to make it work with the older version you're using. 

A simpler solution is just to not use a notebook, this error should disappear if you run brainrender from a script

**Comment by rdbcasillas** [comment]
Thanks for the response @FedeClaudi 

Unfortunately, running with the script also doesn't work. I do get a Win32 Open GL window but after few seconds, it crashes. Attached is the image of that window. Can we simply save the video and not open it? 

![image](https://user-images.githubusercontent.com/9725334/101087014-43cfbc00-3577-11eb-9294-a761f758f175.png)

**Comment by FedeClaudi** [comment]
> Can we simply save the video and not open it?

With brainrender 2.0 you can, in fact it does that by default.

Do you get any error, anything happens before it crashes?
Can you render the scene normally?

Is there any reason against moving to brainrender 2.0? The video an animation functionality is much improved now and the [transition is almost effortless](https://docs.brainrender.info/usage/overview/v1-greater-than-v2)

**Comment by rdbcasillas** [comment]
>Can you render the scene normally?

Same error with rendering also when running the script (which works in jupyter using Plotter). No specific error. After this piece of info: 

```
Bg_atlasapi: allen_mouse_25um version 1.1 is not the latest available (1.2). To update the atlas run in the terminal:
    brainglobe update -a allen_mouse_25um
allen mouse atlas (res. 25um)
From: http://www.brain-map.com (Wang et al 2020, https://doi.org/10.1016/j.cell.2020.04.007 )
Added 15473 cells to the scene
Saving video in C:\Users\7057mehrav\.brainrender\Output/Videos
('\x0bideo Video', 'brainrender_video__20201203_150342', 'is open...')
```

just a  "python has stopped working" dialog box 

>Is there any reason against moving to brainrender 2.0? 

Not a huge reason. Just wanted to keep stuff consistent with stuff I have already created for a website I am working on. I will give it a shot now. Congratulations for the new version!

**Comment by FedeClaudi** [comment]
Thanks, I hope you'll find is much improved and that hopefully the transition is relatively painless.

Given your error message, are you rendering after creating the video? Can you try rendering *intead* of creating the video?
If that's still a problem perhaps you can try without adding the cells to the scene. It's not a very large number of cells you're displaying, but if you are running window 32bit perhaps that's a bit too much?

> Not a huge reason. Just wanted to keep stuff consistent with stuff I have already created for a website I am working on. I will give it a shot now. Congratulations for the new version!

This is so cool! 🎉 
Let me know how that goes, if you can. I've been curious about the possibility of having brainrender being used for online content for a while. And happy to chat/add new features that could make your life a bit easier with that.

**Comment by rdbcasillas** [comment]
>Can you try rendering intead of creating the video?

Yes, unfortunately did not work. Tried removing cells and just loading the brain but still same error. 

>Let me know how that goes, if you can.

Sure, will let you know when website goes live.

**Comment by FedeClaudi** [comment]
mmm, weird.

Can you give me some more info, what OS are your using, what version of python, brainrender and vedo and any output that you get while trying to render the scene. Thanks. 

Also, I suppose that you have been able to get brainrender to work before, did anything change?
Can you get any of the example scripts to run?

**Comment by rdbcasillas** [comment]
I just tried [this](https://github.com/brainglobe/brainrender/blob/master/examples/video.py) video example on latest brainrender version. My anaconda prompt is just stuck with this. 

![image](https://user-images.githubusercontent.com/9725334/101094122-839ba100-3581-11eb-9540-8bd651f49550.png)

Windows 10
Python - 3.7.9

```
Name: vedo
Version: 2020.4.2

Name: brainrender
Version: 2.0.0.2
```
I am running brainrender from within a conda environment.

**Comment by rdbcasillas** [comment]
I was able to make the latest brainrender's video example work on my personal Macbook. Although support for loading cells from h5 file has been removed?  :(

**Comment by FedeClaudi** [comment]
Hey, 

I see. I have no idea why it would work on mac but not on windows. I suppose that you have `ffmpeg` correctly installed in both machines?
On windows, can you get any of the other examples to work? Can you please check which version of `vtk` you have?

> p.s.: There is a typo in the error (in bold , it should be "not"):

Thanks, fixed.

> Although support for loading cells from h5 file has been removed? :(

That's right, sorry. The previous approach required users to have dataframes with specific column names, using numpy arrays instead of dataframes should give more flexibility to the users. It does mean that you have to load the file directly though.

A simple function would take care of this
``` python
def load_cells(path):
    return pd.read_hdf(path).values
```
assuming that your dataframe only has 3 columns and these correspond to the coordinates.

**Comment by FedeClaudi** [comment]
Hi, 

If you use `embedWindow(None)` video generation in Jupyter notebooks works:
<img width="843" alt="image" src="https://user-images.githubusercontent.com/17436313/101158005-eee97f80-3622-11eb-84bf-f61295ddf327.png">

**Comment by FedeClaudi** [comment]
hey @rdbcasillas did you get a chance to try this out?
Everything seems to work okay at my end, but I wanted to make sure that your problem is fixed!

**Comment by rdbcasillas** [comment]
Hey @FedeClaudi, 

I haven't tested it yet because I am still working with h5 files which new version doesn't support. We created a lot of h5 files using cellfinder's function "points_to_brainrender" which converts xml output from cellfinder to h5. So we will have to continue using older version of brainrender for a while. 

Thanks!

**Comment by FedeClaudi** [comment]
I see, okay.  To use the .h5 files you just need a function that loads the file and gets the coordinates :)
```python
def load_cells(path):
    return pd.read_hdf(path).values
```

Anyway, I'll close this for now then but let me know if you bump into other problems
