### ISSUE TITLE
Shader style

### ISSUE THREAD

**Issue by jt522** [brainglobe/brainrender#134]
Hi Federico,

I'm trying to render the brain in jupyter notebook with "plastic" style, using the command shown below.
The image I got is kind of like the sum of "plastic" and "cartoon."
Is there any way to fix this?

from brainrender import settings
from vedo import embedWindow
from brainrender import Scene
from brainrender.actors import Points

settings.SHADER_STYLE = "plastic"
settings.BACKGROUND_COLOR = "white"
embedWindow(None) 
scene = Scene()

# add cells in here

scene.render() 

Thanks! 

<img width="393" alt="image" src="https://user-images.githubusercontent.com/13648214/101122837-68508600-35c1-11eb-9954-f21d1bce9432.png">

**Comment by FedeClaudi** [comment]
Hi, thanks for letting me know, the root silhouette shouldn't be added when using a shader different from 'cartoon'.
If you update with `pip install -U git+https://github.com/brainglobe/brainrender.git` this problem should be fixed

**Comment by jt522** [comment]
Thanks! Now it works perfectly!
