### ISSUE TITLE
ConnectionError: No internet connection found.

### ISSUE THREAD

**Issue by nantille** [brainglobe/brainrender#136]
**Issue**
Brain render requires an Internet connection but it should not be necessary if data is already cached and available locally.

**To Reproduce**
import brainrender and load a brain region.

**Expected behavior**
That it works without Internet connection.

**Comment by FedeClaudi** [comment]
Hey, 

This is most likely a brainglobe atlas API issue, very few functions in brainrender need a connection. 
I will look into it properly and if necessary make changes to the API as you are correct in that it shouldn't fail when no connection is present unless it actually needs it.

**Comment by FedeClaudi** [comment]
The next release of brainrender will fix this, htanks Nantille.
