### ISSUE TITLE
GUI color BUG

### ISSUE THREAD

**Issue by goodwinnastacia** [brainglobe/brainrender#138]
Hi all, I used pip install brainrender on my computer (windows 10) and didn't seem to run into any issues, but when I tried to call the gui I'm running into this error message: 
![brainrender](https://user-images.githubusercontent.com/59748563/102425386-10068480-3fc2-11eb-9f2a-de40491d780c.png)

**Comment by FedeClaudi** [comment]
Hi,  thanks for reporting. 

The problem seems to arise within `pyinspect`, which is another package of mine, but I've never seen that before. 
Did you install brainrender in a brand new python environment? What python version are you using, and what version of `rich` do you have installed?

**Comment by willmcgugan** [comment]
I think this is because the code is running on Python3.6, but Rich requires Python3.6.1 or above.

It's a strange quirk of Python3.6 that methods on NamedTuples don't work.

**Comment by FedeClaudi** [comment]
Thanks for catching this Will, I didn't know!
Brainrender docs say that it works with python >= 3.6, so I guess I should edit that to avoid this kind of issues. 

@goodwinnastacia if you don't mind, could you try installing e.g. python==3.7.0 and see if that works okay?

**Comment by goodwinnastacia** [comment]
Sorry I just had a chance to follow up on this - I made a new anaconda env with python 3.7 and the pip install went fine, followed by these errors with the gui 
![br](https://user-images.githubusercontent.com/59748563/104649681-f06a8680-5669-11eb-89e0-a32d53c2e11e.png)

**Comment by FedeClaudi** [comment]
Hey, that's great. 

Sorry that should give a better error message. You will need to install either pyside or pyqt:
https://github.com/brainglobe/brainrender/blob/ad524f9e10898492ff8aeb1f31c69bf43b4f6d3c/setup.py#L57

**Comment by goodwinnastacia** [comment]
ah I had tried pip install pyside but not pyside2. It's working now! Thanks for your help

**Comment by FedeClaudi** [comment]
awesome, enjoy!
