### ISSUE TITLE
Inside the brain is not painted after slicing

### ISSUE THREAD

**Issue by jt522** [brainglobe/brainrender#139]
Hi Federico,

In the version 2, inside the brain is not painted/filled with root color after slicing.
Is there anyway to fix this? 

This one was made by the previous version.
<img width="269" alt="previous version" src="https://user-images.githubusercontent.com/13648214/103789847-75bcbe00-500e-11eb-8b36-40d1d2fd6add.png">

This one was made by version 2.
<img width="342" alt="image" src="https://user-images.githubusercontent.com/13648214/103790374-1c08c380-500f-11eb-8b7f-42e859831013.png">

Thanks!

**Comment by FedeClaudi** [comment]
Hey, 

It looks fine for me:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/17436313/103791825-d530c300-503a-11eb-82b6-cffe1b8a2118.png">

with:
```python

from brainrender import Scene  
from brainrender import settings

settings.ROOT_ALPHA = .8

s = Scene()

s.root.color('red')

s.add_brain_region("SUB", 'CA1', 'CA3', alpha=.4)

s.slice('frontal')

s.render(camera='frontal')
```

Can you share the code you've used to generate the image (or a minimal example reproducing the problem) and let me know which version python, vedo, brainrender...

Thanks, 
Fede

**Comment by jt522** [comment]
Thanks for your quick response.

Actually, when I use your code, I can get the same image that you posted.
I think that the problem only happens when I render thin brain slices.

Version
Python: 3.7.6
Brainrender:  2.0.0
vedo: 2020.4.2
Jupyterlab: 1.2.6

This is my code

```
from brainrender import Scene
from brainrender import settings
from vedo import embedWindow
embedWindow(None) 

settings.SHADER_STYLE = "plastic"
settings.ROOT_ALPHA = 0.5
settings.ROOT_COLOR = [0.8,0.8,0.8]
settings.BACKGROUND_COLOR = "white"
settings.SHOW_AXES = False
settings.WHOLE_SCREEN = False

# Create a brainrender scene
scene = Scene()
scene.add_brain_region("SUB", 'CA1', 'CA3', alpha=.4)

pos = {
     'pos': (43225, 8315, -5048),
     'viewup': (0, -1, 0),
     'clippingRange': (29250, 34639),
   }

plane1 = scene.atlas.get_plane([9400, 0, 0], norm=(1, 0, 0))
plane2 = scene.atlas.get_plane([9900, 0, 0], norm=(-1, 0, 0))

scene.slice(plane1)
scene.slice(plane2)
scene.render(camera = pos)
```

Thanks!

**Comment by FedeClaudi** [comment]
Right if you're cutting twice, so that only a middle section of the brain is left, you want have anything to render at the back, that makes sense no?

If you try passing `close_actors=True` to one of the calls to slice, then it will try to close the meshes it has cut, is that more like what you'd expect?

**Comment by jt522** [comment]
Ah, OK. It works now. Thanks for your clear explanation!

**Comment by FedeClaudi** [comment]
No problem, have fun!

**Comment by jt522** [comment]
Sorry, actually one more question.
After closing actor, I see some strange lines in the brain structure. Is there any way to solve this?

<img width="364" alt="image" src="https://user-images.githubusercontent.com/13648214/103797354-5fb2fb80-5016-11eb-916a-307047fc8d4d.png">

**Comment by FedeClaudi** [comment]
Not  that I know of, this is internal to `vedo` and how it closes the mesh after cutting, sorry.

**Comment by jt522** [comment]
ok, Thanks!

**Comment by marcomusy** [comment]
@jt522 ..I've seen this before.. capping a mesh is not always perfect.. you may try to recompute normals with
`mesh.clean().computeNormals()` and/or `mesh.phong()`, but i'm not sure if it will help.

@FedeClaudi I just committed a few changes in `vedo` which might affect `brainrender` axes .. 
check out https://github.com/marcomusy/vedo/blob/master/docs/changes.md
maybe it's a good idea if you check if it's all ok before uploading to pypi
One other small thing is that you may wish to import (and even change name to) `vedo.embedWindow` so you dont need to expose vedo to the brainrender user :) e.g.
`from brainrender import embedWindow`

**Comment by FedeClaudi** [comment]
Thanks for the heads up, will give it a go when I have time.
