### ISSUE TITLE
Change the pivot to focus local areas

### ISSUE THREAD

**Issue by youeh1** [brainglobe/brainrender#140]
**Is your feature request related to a problem? Please describe.**
Currently, we can only rotate and zoom the frame with a fixed pivot to navigate the location we want to see, and it looks like we cannot change the fixed pivot. So users cannot zoom and focus on where we specifically want to see.

**Describe the solution you'd like**
If we can move a fixation point for focusing a certain region, it would be very nice
Once we set a certain angle we want to see a certain brain region in the center by
- move the center
- zoom in

**Additional context**
![suggestion1](https://user-images.githubusercontent.com/23224154/103930706-2a2d1180-50ed-11eb-9eb5-a4fa350d9a25.PNG)

**Comment by FedeClaudi** [comment]
Hello, 

This is already supported. If you keep SHIFT pressed and drag around with the mouse this does what you require.

**Comment by youeh1** [comment]
Oh, Great Thanks.
