### ISSUE TITLE
Latest versions of rich cause RecursionError

### ISSUE THREAD

**Issue by crsanderford** [brainglobe/brainrender#141]
Hi Federico,

The latest versions of rich produce a RecursionError. Uninstalling rich and then reinstalling rich==9.7.0 seems to get rid of the issue.
Windows 10 and Ubuntu 20.04, brainrender==2.0.0.4, vedo==2020.4.2

Attached is a script and data that produces the error.
[rich_issue.zip](https://github.com/brainglobe/brainrender/files/5825552/rich_issue.zip)

**Comment by FedeClaudi** [comment]
Hi, 

Thanks for the detailed report.
I wasn able to reproduce your error, can you try updating brainrender from github, it fixed it for me:
```
pip install git+https://github.com/brainglobe/brainrender.git
```

**Comment by crsanderford** [comment]
Installing from the git repository does fix the issue on my end - as does rolling rich back to 9.7.0.

**Comment by FedeClaudi** [comment]
Hi, just following up on this: is everything resolved now?

**Comment by crsanderford** [comment]
Hi Federico - I'll give this another try with the latest version of rich and see if the issue is still present.

**Comment by FedeClaudi** [comment]
THanks
