### ISSUE TITLE
BUG - not rendering human atlas properly, but mouse atlas works fine

### ISSUE THREAD

**Issue by ramroomh** [brainglobe/brainrender#142]
**Describe the bug**
Hi brainrender team,

Thank you for creating this great package. So far I have been able to generate nice images with the mouse brain atlas (allen_mouse_25um specifically), but I run into problems when I render images with allen_human_500um atlas. I know this problem is not restricted to jupyter notebooks because the same problem appears as an executable .py script. Specifically,
the brain is rendered however shown with a very non-proportional scale bar. ![Screenshot from 2021-01-27 09-57-15](https://user-images.githubusercontent.com/39342954/106021181-88b53200-6092-11eb-8d94-f10dbe6f7563.png)
When I zoom to the right hand corner of the scale bar I can see the rendered image, but barely, and only at the right angle. 
![Screenshot from 2021-01-27 11-28-39](https://user-images.githubusercontent.com/39342954/106021530-e5185180-6092-11eb-8cbe-1985085b5347.png)

**To Reproduce**
I am using Ubuntu Ubuntu 18.04.5 LTS, Python 3.7.6, brainrender 2.0.0.4, vedo 2020.4.2
Here is the executable script I wrote:

#!/usr/bin/env python
def main():
    # Enable popups
    from vedo import embedWindow   
    embedWindow(None)
    # Import library
    import brainrender
    from brainrender import Scene
    # Change Settings
    brainrender.SHOW_AXES = True 
    brainrender.SHADER_STYLE = "shiny"
    brainrender.DISPLAY_INSET = False  
    # Generate atlas
    scene = Scene(atlas_name='allen_human_500um', title='Human Brain')
    # Add brain regions
    region = scene.add_brain_region('STR')
    # Render
    scene.render()
if __name__ == "__main__":
    # execute only if run as a script
    main()

**Expected behavior**
I would expect to see the full human brain with the striatum highlighted and no inset. But as can be seen, there is still an inset on on the bottom right corner. Thanks for your help!

**Comment by FedeClaudi** [comment]
Hi, thanks for getting in touch.

Indeed it seems that the axes are wrong for the human brain, not sure what's the cause but setting `SHOW_AXES` to `False` will get rid of them and you'll see the brain normally. 

However please not that the correct way to set values for settings is:
``` python 
from brainrender import settings
settings.SHOW_AXES = False
```
or, equivalently
``` python
import brainrender
brainrender.settings.SHOW_AXES = False
```
but not 
``` python
import brainrender
brainrender.SHOW_AXES = False
```

This should explain why the inset still shows in your image.

**Comment by ramroomh** [comment]
Thank you so much for your prompt reply!

I have updated the script to reflect the proper import of settings:

def main():
    # Enable popups
    from vedo import embedWindow   
    embedWindow(None)
    # Import library
    from brainrender import settings
    from brainrender import Scene
    # Change Settings
    settings.SHOW_AXES = False
    settings.SHADER_STYLE = "shiny"
    settings.DISPLAY_INSET = False  
    # Generate atlas
    scene = Scene(atlas_name='allen_human_500um', title='Human Brain')
    # Add brain regions
    region = scene.add_brain_region('STR')
    # Render
    scene.render()
if __name__ == "__main__":
    # execute only if run as a script
    main()

However, now no brain is rendered at all:
![Screenshot from 2021-01-27 12-29-22](https://user-images.githubusercontent.com/39342954/106030139-d7b39500-609b-11eb-9d0b-b29adc3ce038.png)

**Comment by FedeClaudi** [comment]
Okay, there's two things going on here:

### scaling issues
There seems to be something wrong with how brainrender scales things with this atlas, not sure why. I will have to investigate if the problem is with brainrender or with the atlas data. Either way, the brain is rendered now but it's just tiny, if you call `scene.render(zoom=300)` it will be of the right size.

### Inset
`settings.DIPLAY_INSET` does nothing, because if you want to visualize the inset or not is specified in a different way:
```python
scene = Scene(atlas_name='allen_human_500um', 
     inset=False,  # THIS WILL WORK
)
```


The following code should work:
```python 

from brainrender import settings
from brainrender import Scene

# Change Settings
settings.SHOW_AXES = False
settings.SHADER_STYLE = "shiny"
# settings.DISPLAY_INSET = False  # THIS DOESN'T WORK

# Generate atlas

scene = Scene(
    atlas_name='allen_human_500um', 
    title='Human Brain',
    inset=False,
    )
# Add brain regions
region = scene.add_brain_region('STR')
# Render
scene.render(zoom=300)


```

**Comment by ramroomh** [comment]
Thank you for the workaround Fede, works beautifully now!
![Screenshot from 2021-01-27 12-46-09](https://user-images.githubusercontent.com/39342954/106031890-cc616900-609d-11eb-94aa-cd4080683602.png)

Will leave it to you to close the issue or not.
