### ISSUE TITLE
Minor repo cleanup

### ISSUE THREAD

**Issue by vigji** [brainglobe/brainrender#144]
Very minor repo cleanup suggestions: there's still a travis.yml file, now redundant thanks to github actions: there is a DS_Store file, committed by mistake from a mac I guess - it should ge .gitignored. The bash script for  running all examples could probably go in docs or tests.

I also wonder if the .coveragerc could be merged in the setup.cfg file!

As a side note, I would also add badges in the README.md!

**Comment by FedeClaudi** [comment]
Hey, 

Thanks.
The travis.yml is removed in the development branch, will clean up the rest too (if I manage to get the GH actions to not fail my tests). 

And yes for the badges!

**Comment by vigji** [comment]
Ah sorry, I was looking at the
