### ISSUE TITLE
display 2D sections and extract areas of specific brain regions

### ISSUE THREAD

**Issue by mkunst23** [brainglobe/brainrender#146]
Hi,

We are looking for a feature where we display individual slices of the Allen Reference Atlas and then can extract the area of specific brain regions. Is there already a way to do this in brainrender?

Thanks,
Michael

**Comment by FedeClaudi** [comment]
Hi, 

The short answer is no. I've played around with this but didn't end up making it a  feature as I was not sure if it would be used. 
Vedo has a method for displaying 2D images in a 3D rendering however, so it should be doable. The main challenge is aligning the image to the atlas.
