### ISSUE TITLE
Extract slices as single plane

### ISSUE THREAD

**Issue by MathieuBo** [brainglobe/brainrender#149]
Hi,

Great tool! thanks a lot!!

For various projects, I would be interested in being able to extract slices at various coordinates. I envision we could either:
1. Extract a plane as a screenshot
2. Manipulate the depth of field to highlight a specific section or
3. Affect a lower alpha to other planes than the preferred one. 

Do you have any tips on how to do that? 

Thanks a million!
Mathieu

**Comment by FedeClaudi** [comment]
Hi,

Thanks!

I'm not sure I understand what you mean exactly, but brainrender's `Scene` has a `slice` method (see [example(https://github.com/brainglobe/brainrender/blob/master/examples/slice.py)].

This can be used to cut open any or all actors with a plane at a given point and with a given norm. So you can do this to highlight a plane in your data. To take a screenshot of the highlighted plane you can simply orient your camera to face it (either manually or by specifying a set of camera parameters like in [this example](https://github.com/brainglobe/brainrender/blob/master/examples/custom_camera.py))

Of course this slice method cut's a scene and laves everything on one side of the plane intact. If you want to highlight a thin slice of your scene (e.g. only stuff between 1 and 2 mm in the AP axis) you can simply use `slice` twice with accurately selected plane (in particular the norms should point in opposite directions). 

Note that `slice` cuts the actors' meshes and discards part of them. If you don't want that part to disappear but simply to e.g. change alpha, you can create a copy of the original actor, slice it with the same plane but with opposite norm (this gives you the parts that would disappear with the first slice) and then change its alpha. 

Let me know if any of this is unclear or if I can be of any help.

**Comment by MathieuBo** [comment]
Thanks a lot for your super fast answer!
The second options worked perfectly for my purposes. 
![Slice (1)](https://user-images.githubusercontent.com/14175231/109516633-aec25d80-7aa8-11eb-9b2e-b283c8cb42c3.png)

Related question, can I fill the volumes to avoid the gruyere-like picture? 

Thanks again!

**Comment by FedeClaudi** [comment]
Awesome, that looks cool!

`slice` has a `close_actors` argument (see [here](https://github.com/brainglobe/brainrender/blob/ad77730001a98296a27ef3629d6145976b5f955f/brainrender/scene.py#L329)) that creates a face where the actor was cut.

**Comment by MathieuBo** [comment]
It worked perfectly thanks! This is a major improvement in our analysis routine. 
![Slice](https://user-images.githubusercontent.com/14175231/109545490-34560580-7ac9-11eb-904c-ebdcda060a7d.png)

Last question (I swear!), is there an easy to convert the x,y,z coordinates to distance to Bregma, etc, as we have been used to use in printed atlases?

**Comment by adamltyson** [comment]
> Last question (I swear!), is there an easy to convert the x,y,z coordinates to distance to Bregma, etc, as we have been used to use in printed atlases?

Unfortunately not. There's currently no mapping from Allen CCF space to skull coordinates.

**Comment by MathieuBo** [comment]
> > Last question (I swear!), is there an easy to convert the x,y,z coordinates to distance to Bregma, etc, as we have been used to use in printed atlases?
> 
> Unfortunately not. There's currently no mapping from Allen CCF space to skull coordinates.

Got it, thanks for the fast reply!

**Comment by adamltyson** [comment]
I really like this visualisation @MathieuBo. @FedeClaudi what do you think about having somewhere to host cool user-contributed scripts?

**Comment by MathieuBo** [comment]
> I really like this visualisation @MathieuBo. @FedeClaudi what do you think about having somewhere to host cool user-contributed scripts?

Happy to share if interested!

**Comment by FedeClaudi** [comment]
> Last question (I swear!), is there an easy to convert the x,y,z coordinates to distance to Bregma, etc, as we have been used to use in printed atlases?

There's no good way to do this, but there's a rough approximation. If you see [here](https://github.com/brainglobe/probeplanner/blob/a0b10a37b51c8e4fb1bcc209b21d1633f290301a/probeplanner/probe.py#L15) these are approximate bregma coordinates in allen CCF (originally from Shamash et al 2018, and used in [this preprint](https://www.biorxiv.org/content/10.1101/2021.02.18.431923v1.abstract)). If it's just for a rough visualization this might be good enough, but for surgery or quantitative analysis it might not be accurate enough. 

@adamltyson  I also **really** like this visualization, it's a great idea. The docs have [something](https://docs.brainrender.info/info/publications-using-brainrender) like what you are suggesting, but it could be better: currently it doesn't include example code. 
Suggestions for how to best make something like this?

**Comment by adamltyson** [comment]
> Suggestions for how to best make something like this?

Perhaps this might be something for BrainGlobe docs 2.0? Something like jupyter books, and then brainrender examples, along with tutorials for the other packages (and things like common cellfinder post-processing analysis tasks).

**Comment by FedeClaudi** [comment]
@MathieuBo  I will close this issue now, get in touch with any other question if you need.

In regard to your question:
> Last question (I swear!), is there an easy to convert the x,y,z coordinates to distance to Bregma, etc, as we have been used to use in printed atlases?

The answer is still that there's no very accurate way to do this, but you can get an approximate idea. This is how I did it in proleplanner: https://github.com/brainglobe/probeplanner/blob/befc90d62e5124036343cbd6e3acc6b7db7209a5/probeplanner/terminal_ui.py#L84
