### ISSUE TITLE
Other atlases 

### ISSUE THREAD

**Issue by MathieuBo** [brainglobe/brainrender#150]
Hi, 

I would be interested in using BrainRender for non-human primates (macaques).  

What are the roadblocks, and which kind of data would be required (collection of 3D meshes?)? Depending on the required data, I think I can contribute to providing it. 

Thanks!

**Comment by FedeClaudi** [comment]
That would be amazing!

Brianrender uses BrainGlobe's AtlasAPI for handling atlas data: https://docs.brainglobe.info/bg-atlasapi/introduction.
So you'd have to format your data to match the APIs requirements. We don't have the minimal requirements written in the docs anywhere yet (cc @adamltyson, @vigji ), but the main things are a 3D image with the reference image and an image with a label at each voxel to indicate which brain region that belongs to as well as data about structures hierarchy. If you have the meshes that's a bonus, but if not we have code to create meshes from images. 

We have code we used to generate the atlases we currently support, that would facilitate the atlas creation greatly.

**Comment by FedeClaudi** [comment]
> What are the roadblocks

Once an API-compatible atlas is ready you can use brainrender just as you did so far.

**Comment by adamltyson** [comment]
@MathieuBo Once the atlas is implemented within the AtlasAPI, it will also be available for use in other [BrainGlobe](https://github.com/brainglobe) software, so this would be really useful for the community.

**Comment by MathieuBo** [comment]
Ok, thanks for the answers. I will come back to you if/when I have data available. Maybe we should close the issue here and I will open the issue directly on BrainGlobe's AtlasAPI.

**Comment by FedeClaudi** [comment]
Perfect, let us know we'd love to have a NHP atlas!
