### ISSUE TITLE
Improvements to transformation matrix

### ISSUE THREAD

**Issue by FedeClaudi** [brainglobe/brainrender#151]
To correct for the different orientation of the axes in vedo vs e.g. napari, brainrender currently uses a [transform matrix](https://github.com/brainglobe/brainrender/blob/4f5a157636ce3c996f21adfa6e65a61fb020aa60/brainrender/render.py#L21) to reflect each mesh object in the ML axis. 

This 'works' in the sense that things look correct (e.g. L/R hemispheres are not inverted anymore) but causes some problems: while things 'look' normal, the coordinates in the ML axis of the meshes are negative numbers. This becomes a problem e.g. if a mesh's center of mass is used for further analysis. 

I was thinking of adding a 'translation' matrix in addition to the current reflection one, but I'm unsure what the best way to make this work across atlases would be. Any thoughts @vigji ?

**Comment by vigji** [comment]
Mmmm a translation would make it even more confusing because it would actually change the value of a coordinate instead of just adding a minus sign to it, so people will find their coordinate looking different  in the viewer! What do you think?

**Comment by FedeClaudi** [comment]
Yeah, it's a fair point. The current situation might be best then. It's a bit hacky buyt 90% of users won't realize. But when one starts doing more advanced stuff (e.g. [probeplanner](https://github.com/brainglobe/probeplanner)) it becomes annoying sometimes. We might just have to live with that though./
