### ISSUE TITLE
BUG actor labels are duplicated in animations

### ISSUE THREAD

**Issue by janfpl** [brainglobe/brainrender#153]
Using add_label() to label to an actor added with add_brain_region() results in two labels being rendered in animations in brainrender 2.0.2.4 and 2.0.2.3. Using 2.0.2.2 renders only one label in animations.

Using scene.render() works as expected in 2.0.2.4, with only one label rendered.

Tested running a .py file from terminal in Ubuntu 18.04.

https://user-images.githubusercontent.com/41079621/110849342-fb095c80-8263-11eb-97f6-9566bad02053.mp4

https://user-images.githubusercontent.com/41079621/110849344-fba1f300-8263-11eb-8a84-ca7fc898685f.mp4

**Comment by janfpl** [comment]
Here is the copy of the .py file I used
https://drive.google.com/file/d/1ekvxwTd_sCmCwiOseVaBTqpfCuUHe_Ws/view?usp=sharing

**Comment by FedeClaudi** [comment]
The problem was due to labels being rendered multiple times when calling `scene.render` multiple times. Version `2.0.2.5` fixed this. Thank you again for the info.
