### ISSUE TITLE
Loading .obj file in v2.0

### ISSUE THREAD

**Issue by jsiegle** [brainglobe/brainrender#154]
I have a model of a Neuropixels shank that I'd like to insert into a scene (.obj file is attached below). This worked fine using `scene.add_from_file()` in brainrender v1, but I can't get the model to appear using `scene.add()` in v2.0. I've tried various parameters for the scaling and translation, but the model never becomes visible.

FWIW, I created the model in Blender with the tip centered on the origin. When I try to load `CC_134_1_ch1inj.obj` in Blender, nothing appears. So maybe there's some file format incompatibility? If so, I'd appreciate any advice on how to create a usable .obj file.

Thanks for your help!

[shank.obj.zip](https://github.com/brainglobe/brainrender/files/6152846/shank.obj.zip)

**Comment by FedeClaudi** [comment]
Hey, thanks for getting in touch.

First thing, can you please make sure you have the latest version of brainrender (`v2.0.2.6`)? 

This worked for me:
```
from brainrender import Scene
from brainrender import settings

settings.SHOW_AXES = False

# crate a scene and add brain regions
scene = Scene(root=True, inset=False)
mos = scene.add_brain_region('MOs')

probe = scene.add('/Users/federicoclaudi/Downloads/shank.obj')

print(probe)

probe.scale(10)
probe.pos(mos.centerOfMass())
print(probe)

# render
scene.render()
```

It looks like your probe needs to be scaled up (brainrender's units are in microns) and it's set at the origin by default so it has to be moved to a different position. Hope this helps.

By the way, if you are using neuropixels you might have fun playing around with [probeplanner](https://github.com/brainglobe/probeplanner)

**Comment by jsiegle** [comment]
I installed `v2.0.2.6rc` into a fresh conda environment (Python 3.8), and now I'm seeing a different problem: `scene.add` is returning `None` instead of an `Actor` object, so the `print` command returns a `TypeError`. This happens for both my shank file as well as the example injection volume .obj file.

Any idea what could be causing this?

Also, probeplanner looks like it will be super useful! However, `probe view` and `probe plan` are failing on both Mac and Linux. Should I open up an issue in that repo?

**Comment by FedeClaudi** [comment]
Mmm it sould be `2.0.2.6` not `2.0.2.6rc`, did you  do `pip install -U brainrender`? If not, could you try that?

It's weird that it's not returning anything even for the injection volume, can you share exactly the code you're using?

> Also, probeplanner looks like it will be super useful! However, probe view and probe plan are failing on both Mac and Linux. Should I open up an issue in that repo?

Thanks, `probeplanner` is at a very early stage of development and won't receive much attention in the short term future due to my lack of time, but an issue would be great. Also if anyone is interested in collaborating on its development at brainglobe we are always happy to welcome new developers on board :)

**Comment by jsiegle** [comment]
`pip install -U brainrender` (in my existing environment) and `pip install brainrender` (in a clean environment) both installed the `rc` version on Mac. I was able to get the correct version with `pip install brainrender==2.0.2.6`. Now, however, it looks like `2.0.2.8` is the default.

I encountered the problem when using the `add_mesh_from_file.py` example. It actually looks like most of the examples are failing now. For example, adding a title to the scene raises `ValueError: Unrecognized argument: vtkActor2D`. Could there have been a change in one of the dependencies that's triggering this?

I'm happy to help with some of the `probeplanner` development. I was planning to build a similar tool for our own purposes, but it's much better to collaborate! I will try to troubleshoot the startup failures before I open an issue.

**Comment by FedeClaudi** [comment]
You're right, this doesn't sound like a `brainrender` issue, would you mind giving more details about your system? Which OS, python version, `vtk` and `vedo` versions etc...

Another thing you can do is enabling 'debug mode' and see if more detailed information is provided as to why things are failing:
```python 
import brainrender

brainrender.set_logging('DEBUG')
```

> I'm happy to help with some of the probeplanner development. I was planning to build a similar tool for our own purposes, but it's much better to collaborate! I will try to troubleshoot the startup failures before I open an issue.

That's great news! Looking forward to collaborating with you on that.

**Comment by jsiegle** [comment]
I had to do two things to get this to work:

1. Downgrade `vedo` to `2020.4.2`. It seems like there were some breaking changes in `2021.0.2` (released 7 days ago) that were causing the examples to fail.

2. Change line 141 of `actor.py` to `return lambda : "<placeholder info string>"`. I originally thought the `scene.add` method was returning `None`, but it's actually a problem with the `__rich__` attribute being `None`, which causes the `print` statement to fail.

I'm not sure what accounts for the difference in behavior related to (2). Do you have any ideas?

**Comment by FedeClaudi** [comment]
Okay, good investigation. 

1) is a bit worrying (cc @marcomusy), do you know what exactly is causing the issue by any chance?

2) I am not sure.. which version of `rich` do you have? What happens if you just return an empty string `''` ?

**Comment by marcomusy** [comment]
Hi Federico 

the `Text2D` is now genuinely a class, so you need to change in line 143 of `brainrender/scene.py`
```
            if isinstance(item, (Mesh, Assembly)):
                actors.append(Actor(item, name=name, br_class=_class))

            elif isinstance(item, Text2D):
```
also change line 85
```
                Text2D(title, pos="top-center", s=2.5, c="k", alpha=1),
```
font Montserrat doesn't exist , and `pos` cannot be numeric anymore. You can change the default font with e.g.
`settings.defaultFont = "Theemim"`

With the new `Text2D` class you can change the text message more easily with the method `text("some new message")`.

with these changes i could run the example `examples/add_cylinder.py`
![Screenshot from 2021-03-24 18-29-45](https://user-images.githubusercontent.com/32848391/112357336-b94ecc00-8ccf-11eb-856d-c49fa75534d5.png)

PS: you might consider locking the vedo version in the requirements file, so any crazy vedo "improvement" would not directly affect brainrender (at the price of not getting immediately new features or bug fixes)

**Comment by jsiegle** [comment]
I have `rich` version `9.13.0` installed.

Actually, everything works as expected after commenting out the `if attr == "__rich__":` statement (lines 140 + 141). It seems like the `__rich__` attribute is no longer needed.

**Comment by marcomusy** [comment]
...more things:
- `xFlipText` does not exist anymore, (but i'm not sure what exactly is desired there)

- change in `brainrender/scene.py`:
`self.plotter.showInset()` to `addInset()` (just renaming)

- `examples/animation.py` seems to have a zooming in the loop..

- `vedo.Text` changed to `vedo.Text3D` (just renaming)


all examples seem to have the pivoting point for the camera to be the end point of one axis - not sure if this is intended.

**Comment by FedeClaudi** [comment]
Thanks @jsiegle  I will try removing it.

And thank you very much @marcomusy it's great that you took the time to go through all that.

> all examples seem to have the pivoting point for the camera to be the end point of one axis - not sure if this is intended.

How do you specify were the pivot point is?

**Comment by FedeClaudi** [comment]
Hi Marco, 

I've been implementing the modifications you have suggested. Is there a way to rotate the axes ticks labels?
<img width="1292" alt="image" src="https://user-images.githubusercontent.com/17436313/112385393-7a2c7500-8ce7-11eb-8fe4-26418f16db1f.png">

**Comment by marcomusy** [comment]
Hi Federico
I hope this will do:
```python

from vedo import *

ax = Axes(xrange=(0,12000),
          yrange=(0,8000),
          zrange=(11400,1266),
          xLabelRotation=180,
          yLabelRotation=180,
          zLabelRotation=180,
          xTitleRotation=180,
          # xTitleJustify="bottom-left", # these are guessd automatically
          xtitle='AP(\mum)',
          ytitle='DV(\mum)',
          ztitle='LR(\mum)',
         )

show(ax)
```
![Screenshot from 2021-03-24 22-48-19](https://user-images.githubusercontent.com/32848391/112388255-2de73200-8cf3-11eb-8f93-5ebfd7a637d4.png)
