### ISSUE TITLE
Volume smoothing

### ISSUE THREAD

**Issue by mabbasi6** [brainglobe/brainrender#155]
I wanted to ask if smoothing volumes is possible? I am loading nii files with 100-micrometer resolution and have an edgy shape now.

**Comment by FedeClaudi** [comment]
Hi, how are you rendering the volume?

When using the `Volume` actor you can set `as_surface=False` to create a smooth volume:
``` python
actor = Volume(
    "examples/data/volume.npy",
    voxel_size=200,  # size of a voxel's edge in microns
    as_surface=False,  # if true a surface mesh is rendered instead of a volume
    c="Reds",  # use matplotlib colormaps to color the volume
)
```


![image](https://user-images.githubusercontent.com/17436313/111745754-f3aa0a80-8884-11eb-9763-a4f831e797b0.png)


If you set `as_surface=True` a 'lego' (blocky) surface is extracted from you volumetric data.

Note that in the first case you'll rendered actor will be represented by a `vedo.Volume` object while in the second case it will be a `vedo.Mesh`. So if you want to play around with the appearance of your volume you will have to look at the corresponding class in [vedo](https://github.com/marcomusy/vedo)
