### ISSUE TITLE
Add optic canula in brainrender 2.0

### ISSUE THREAD

**Issue by kreikersdorfer** [brainglobe/brainrender#156]
Is there a way to produce an optic cannula in the new version of brainrender? Scene class appears to not contain the add_optic_cannula function, which exists in the brainglobe/brainrender-docs

Running brainrender 2 (I think) on OS Big Sur

Expected behavior: an optic cannula emerging from CA1 target region

<img width="764" alt="Screen Shot 2021-03-19 at 9 44 15 PM" src="https://user-images.githubusercontent.com/51750988/111857132-81294100-88fd-11eb-8c79-57c6b0a2dad6.png">
<img width="908" alt="Screen Shot 2021-03-19 at 9 44 29 PM" src="https://user-images.githubusercontent.com/51750988/111857134-82f30480-88fd-11eb-8b84-78c664fa0518.png">
<img width="764" alt="Screen Shot 2021-03-19 at 9 42 21 PM" src="https://user-images.githubusercontent.com/51750988/111857137-85555e80-88fd-11eb-8cae-160d09f180ed.png">
<img width="764" alt="Screen Shot 2021-03-19 at 9 43 55 PM" src="https://user-images.githubusercontent.com/51750988/111857139-87b7b880-88fd-11eb-94bb-a56aad53c86b.png">

**Comment by FedeClaudi** [comment]
Hi,

I'll add an example to the repo, but in brief all `Scene` class methods `add_X` have been replaced by a single `Scene.add` method. You now need to specify want you want to add to the scene: e.g. for an optic canula you need to create a `Cylinder Actor` and pass that to `add`, like so:

```python
"""
    This example shows how to add a cylinder actor to a scene (e.g. 
    to represent the location of an implanted optic canula)
"""
import numpy as np
from brainrender import Scene
from brainrender import settings

from brainrender.actors import Cylinder

settings.SHOW_AXES = False
settings.WHOLE_SCREEN = False


from rich import print
from myterial import orange
from pathlib import Path

print(f"[{orange}]Running example: {Path(__file__).name}")

scene = Scene(inset=False, title='optic canula')

th = scene.add_brain_region('TH', alpha=.4,)

# create and add a cylinder actor
actor = Cylinder(
  th,  # center the cylinder at the center of mass of th
  scene.root,  # the cylinder actor needs information about the root mesh
  )

scene.add(actor)
scene.render(zoom=1.6)

```

**Comment by kreikersdorfer** [comment]
Hi, 
Thank you so much for taking the time to walk me through this!! I really appreciate it (and apologize for my difficulty in understanding the documentation)!

When I run the sample script above I get the following error: 
<img width="763" alt="Screen Shot 2021-03-20 at 8 25 31 AM" src="https://user-images.githubusercontent.com/51750988/111871023-08a29e80-8956-11eb-9f10-03120dd27e60.png">
<img width="623" alt="Screen Shot 2021-03-20 at 8 25 41 AM" src="https://user-images.githubusercontent.com/51750988/111871026-0a6c6200-8956-11eb-8964-eec47f552711.png">

Any additional thoughts? 

Thanks again.

**Comment by FedeClaudi** [comment]
Can you try updating brainrender with `pip install git+https://github.com/brainglobe/brainrender.git` to see if that fixes it?

**Comment by kreikersdorfer** [comment]
That took care of the error. Thanks so much again. One last question- when running the script above, the cylinder is centered on the midline rather than in the unilateral brain region represented (almost like its still finding the center of mass between R and L regions). Any tips?

Thanks so much for helping me through these issues!

<img width="442" alt="Screen Shot 2021-03-21 at 6 59 18 PM" src="https://user-images.githubusercontent.com/51750988/111925729-07699280-8a78-11eb-9f14-b3ccc0440133.png">
<img width="824" alt="Screen Shot 2021-03-21 at 6 59 25 PM" src="https://user-images.githubusercontent.com/51750988/111925730-089abf80-8a78-11eb-9ffd-e870690f5114.png">

**Comment by FedeClaudi** [comment]
Hey, I am not sure actually I will need to investigate.

In the meanwhile there's a workaround:
```python

pos = th.centerOfMass()  # yields the position of the center of the whole thalamus
pos = pos + np.array([X, Y, Z])  # shift the position by a given ammount in each direction

actor = Cylinder(pos, scene.root)

```

The first argument to `Cylinder` can be a numpy array of coordinates of the tip of the cylinder. It's not great but if you need to make some renderings right now it should allow you to position the optic fiber as you need.

**Comment by FedeClaudi** [comment]
I hope that fixed it, closing now. Get in touch if it didn't work!
