### ISSUE TITLE
Bug: new vedo version failure

### ISSUE THREAD

**Issue by kvinehout** [brainglobe/brainrender#157]
**Describe the bug**
When I install Brainrender and run examples I get a variety of depreciation errors associated with vedo. 

**To Reproduce**
I am using pycharm and installing brainrender. Initially, this installs Vedo version 2021.0.2
When I change vedo to  2020.4.1 I no longer get these errors. It looks like in your setup.py you have "vedo>=2020.4.1" instead of "vedo==2020.4.1". 

Then tell us the steps to reproduce the behavior:
1. Install Brainrender
2. run user_volumetric_data.py
3. See error

**Comment by FedeClaudi** [comment]
Hi, 

Yep that has been highlighted under another issue also: https://github.com/brainglobe/brainrender/issues/154

I will soon (today maybe) release a version of brainrender that works with the latest vedo version. In the meanwhile downgrading vedo should address these issues.

**Comment by FedeClaudi** [comment]
Please try updating brainrender and see if that fixes the problem

**Comment by kvinehout** [comment]
With brainrender == 2.0.2.9 and vedo == 2021.0.2 i still get the following error with :user_volumetric_data.py
TypeError: addPos() got an unexpected keyword argument 'dp_x'

With brainrender == 2.0.2.9 and vedo == 2020.4.1 i dont get any errors.

**Comment by marcomusy** [comment]
Try changing 
`.addPos(SHIFT)`
to
`.shift(SHIFT)`

**Comment by FedeClaudi** [comment]
@kvinehout  you will also need to update the example code from this repository (`git pull`) for it to work correctly

**Comment by kvinehout** [comment]
Thanks! that worked!
