### ISSUE TITLE
install issues

### ISSUE THREAD

**Issue by jaehongpark-neuro** [brainglobe/brainrender#159]
**Issues with jupyter notebooks**
We have received [several issues related to Jupyter notebooks](https://github.com/brainglobe/brainrender/issues?q=is%3Aissue+is%3Aopen+label%3A%22Jupyter+Notebooks%22).
If your issue is specific to running brainrender in a notebook, please check if any of the previously addressed issues is helpful, look at the [documentation on using notebooks](https://docs.brainrender.info/usage/using-notebooks) and try running the [notebooks workflow example](https://github.com/brainglobe/brainrender/blob/master/examples/notebook_workflow.ipynb) **before** opening a new issue. 

If you are not sure if your issue is specific to jupyter notebooks, try running your code in a python script (i.e. with a `.py` file) and see if you get the same error, or any error at all. If you don't then the problem is restricted to notebooks.

**Describe the bug**

**To Reproduce**
First tell us which version of `brainrender` and `vedo` you're using and something about your system (e.g. OS etc). 

Then tell us the steps to reproduce the behavior:

**Expected behavior**
I was once using the brainrender well, but I recently formatted my laptop and got a new computer.
So I was trying to install python through anaconda, and install brainrender, but I am stuck with installing your package.

Any ide what's going on?
I've tried several version of anaconda, but non of them work..

**Screenshots**
![image](https://user-images.githubusercontent.com/80608873/118385244-6e6c7900-b5db-11eb-8f0b-3f67555259f6.png)

![image](https://user-images.githubusercontent.com/80608873/118385248-7b896800-b5db-11eb-9909-bf379c5b6de0.png)

**Comment by FedeClaudi** [comment]
Hi, 

I'm not sure what the cause of this could be, I haven't seen it before. 
Could you give me more details about what you're doing (e.g. python version you're using, brainrender version you're trying to install etc..)

**Comment by jaehongpark-neuro** [comment]
I tried to install 3.8, 3.7, 3.6 via anaconda3, non of them worked.

Once I installed anaconda, I made an virtual env, 
conda create -n br python=3.x
conda activate br
then type 
pip install brainrender

yea, it is very weird, I actually did the same thing early this year, formatted my laptop and install anaconda and brainrender, it had no problem at all, it was totally fine, so I am confused what I am doing wrong.

Thanks,

**Comment by FedeClaudi** [comment]
I see. Yeah that's weird indeed. it seems that the problem is with installing [morphio](https://github.com/BlueBrain/MorphIO/issues) so perhaps it would be best to ask morphio's developers for help?

**Comment by FedeClaudi** [comment]
hey @jaehongpark-neuro  any luck with this?
