### ISSUE TITLE
K3D closer cooperation

### ISSUE THREAD

**Issue by artur-trzesiok** [brainglobe/brainrender#161]
First of all - awesome work. As a main developer of K3D-jupyter package I want ask: do you need bigger support from my side? I'm working right now on quite important refactor in k3d soe if there is anything that I can planed that will make your life easier please let me now!

I'm glad that K3D found that kind of usage :).

**Comment by FedeClaudi** [comment]
Hi, thanks, and thanks for getting in touch.

All of brainrender's visualizations are done through @marcomusy's awesome package: vedo. For the time being I don't see brainrender starting to use packages like K3D directly. So any changes to K3D that affect how vedo makes use of it will benefit brainrender, but I can't think of any specific need currently.

**Comment by artur-trzesiok** [comment]
Och, I see. Good to hear that. If there Will be any suggestion please don't hesitate to add feature request. So I that case I think we can close this issue here :)

**Comment by marcomusy** [comment]
Hey, thanks, indeed the `vedo` interface to `k3d` is old, ugly, and kind of stopped working properly in latest versions of `k3d`, but didn't have the time to debug. The main issue seems to be some strange backfaceculling effect of meshes which do not render correctly.
At the same time also `vedo` is going through some important restructuring which might affect various parts, so i'll get back to you as soon as i have something semifinal..
It' very good to have a tool like `k3d` for notebook and web-browser renderings (a cool example [here](https://vedo.embl.es/examples/geo_scene.html)) as vtk I guess was never designed with that in mind..

**Comment by artur-trzesiok** [comment]
@marcomusy K3D has many new features at development phase like volume slice inspection, interactive masks, depthpeels (OIT) etc. If there is any case where I can help with polishing breaking changes in K3D please prepare isolated case that shows a problem and I can try to solve that in my free time.

Example that you showed is impresive. Great work!

**Comment by FedeClaudi** [comment]
Indeed the ability to have something that can be exported directly for the web is one of the most attractive features of K3D in my opinion: for brainrender that would allow to send visualizations by email or embed them online into papers or websites, which is awesome.

**Comment by marcomusy** [comment]
@FedeClaudi True!

> send visualizations by email 

you can send a dropbox link, then e.g.:
`vedo https://www.dropbox.com/s/ilu64q3vgs1f7a2/geo_scene.npz?dl=0`

but obviously the receiver needs to have `vedo` installed.
