### ISSUE TITLE
Brainrender-gui, keyboard is not working and blocked

### ISSUE THREAD

**Issue by MBPhys** [brainglobe/brainrender#165]
When I have started the brainrender-gui via the console the Gui will be opened and the rendering and click buttons via mouse work, but I can not make input for the alphas for instance or any other text inputs. Furthermore the keyboard is blocked in the terminal or in any other applications. I have installed the newest brainrender version 2.0.3.1 and vedo 2021.0.3, Ubuntu 20.04.2.0 LTS (Focal Fossa). No error message occurs in the terminal.

**Comment by FedeClaudi** [comment]
Hi, thanks for reporting this.
If you use brainrender normally (i.e. without the GUI) does everything work fine?
Which version of PySide or PyQT did you install?

**Comment by MBPhys** [comment]
Hi,
Yeah just for the GUI. The rendering works well. I have tried different versions of pyside and pyqt (  5.15.4, 5.11.2, 5.14.0). But it does not work.

**Comment by FedeClaudi** [comment]
I see, thank.
Do you have a Windows or Mac OS machine you could test things on?
I don't have linux and can't replicate your problem on my machines.

**Comment by adamltyson** [comment]
FWIW @FedeClaudi, I tried to reproduce this on Ubuntu 18.04, fresh Python 3.9 environment, and when I run `brainrender-gui` I get a brief flash of an upside down brain, and then `Segmentation fault (core dumped)`, and nothing else.

**Comment by MBPhys** [comment]
No just Linux Ubuntu 18.04 and 20.04. I have used python=3.7. For python=3.9 brainrender does not work generally

**Comment by adamltyson** [comment]
> For python=3.9 brainrender does not work generally

I should have known this!

@FedeClaudi I can reproduce @MBPhys's issue on Python 3.8 though. The main GUI window opens, along with a fairly weird looking brainrender scene in a separate window, maybe this is blocking the keyboard input?

It also blocks keyboard input across all windows, so I can't even take a screenshot,

**Comment by FedeClaudi** [comment]
Okay so: the 3.9 business I hadn't tested, is it limited to the GUI? Might be worth highlighting it in the docs if I haven't done that yet..

For the GUI, it seems like it's a linux specific problem, I can't replicate it anywhere.
If it's limited to the GUI then it's not brainrender bug but probably pyqt, might be worth having a look online for pyqt/linux related problems?

**Comment by MBPhys** [comment]
@adamltyson 
Yeah, this is the same problem:) No keyboard input is possible in general.

**Comment by FedeClaudi** [comment]
> along with a fairly weird looking brainrender scene in a separate window, maybe this is blocking the keyboard input

That happens on all systems (see https://github.com/brainglobe/brainrender/issues/164) but it doesn't seem to cause problems

**Comment by adamltyson** [comment]
> Okay so: the 3.9 business I hadn't tested, is it limited to the GUI? Might be worth highlighting it in the docs if I haven't done that yet..

From a **very** quick test, this doesn't seem limited to the GUI. As soon as a scene is instantiated, the weird brain appears and everything is blocked. This is also happening on 3.8 too, so probably a new version of something?

**Comment by MBPhys** [comment]
@FedeClaudi 
I think it is is a specific error in Brainrender for Linux. I have tested a the input via QLineEdit of qt with a test script, which was used in Brainrender too  and no error occurs. This means there is not a bug in pyqt.
Gui of Brainrender blocks the input via keyboard.

**Comment by FedeClaudi** [comment]
Okay, thanks for testing that. I'll have a look but I'm not sure how to fix this since I can't replicate.

**Comment by FedeClaudi** [comment]
See: https://github.com/brainglobe/brainrender/issues/164

The issue with the extra window appearing in the GUI has been fixed, perhaps this resolves the keyboard issue on linux?
To test: `pip install brainrender==2.0.3.3`, let me know!

**Comment by adamltyson** [comment]
Works for me on Ubuntu 18.04 with PySide2 and Python 3.8. :tada:

**Comment by FedeClaudi** [comment]
happy days!
