### ISSUE TITLE
Github actions tests failing

### ISSUE THREAD

**Issue by FedeClaudi** [brainglobe/brainrender#168]
All tests run fine locally, but fail on github actions: on both [windows](https://github.com/brainglobe/brainrender/runs/2924726367?check_suite_focus=true) and [linux](https://github.com/brainglobe/brainrender/runs/2924705061?check_suite_focus=true). 

On linux the error is `Error: Process completed with exit code 134.` which an online search suggests might be a memory error while on Windows I get `Windows fatal exception: access violation` on the first call to `Scene()` which should be where the atlas data from `brainglobe atlas API` are first downloaded.

I will investigate if the problem is with downloading, saving and accessing the atlas data.

**Comment by FedeClaudi** [comment]
Yep, the errors are due to [failures during atlas download](https://github.com/brainglobe/brainrender/runs/2924781544?check_suite_focus=true) since [this test](https://github.com/brainglobe/brainrender/blob/master/tests/test_01_atlas_download.py) is failing. 

Any ideas, @adamltyson ?

**Comment by adamltyson** [comment]
Isn't the default atlas `"allen_mouse_25um"`?

**Comment by FedeClaudi** [comment]
it is, I've changed it to see if downloading a more lightweight atlas would help but it didn't: I get the same error with both.
Tests pass locally btw, so it's not a huge problem though it'd be nice to have it fixed

**Comment by FedeClaudi** [comment]
Btw this doesn't seem to be a problem with just downloading things since in my personal website I have an [action](https://github.com/FedeClaudi/FedeClaudi.github.io/actions) which downloads about 300MB of data using [refy](https://github.com/FedeClaudi/refy). So I'm not sure what's going on here!

**Comment by adamltyson** [comment]
I asked about the default atlas, because the test has `assert atlas.atlas_name == "allen_mouse_100um"`. Won't this always fail unless you specify the atlas?

**Comment by FedeClaudi** [comment]
I set it to be `allen_mouse_100um` for the tests: https://github.com/brainglobe/brainrender/blob/6decb9ce3e7a2d49abe3ee99baea4f492cfd1845/tests/__init__.py#L5

**Comment by adamltyson** [comment]
Ah, then I've got no idea. The atlas seems to download fine on GitHub actions for brainreg etc.
