### ISSUE TITLE
BUG - Issue with imported point alignment

### ISSUE THREAD

**Issue by tamachado** [brainglobe/brainrender#171]
First, thanks for putting this software out there. It looks to be a useful tool for visualizing disparate data streams in the Allen Atlas Space and am looking forward to using it more.

Here, I'm reporting that points that I have plotted on top of the most recent Allen atlas do not appear correctly on the 3d model in brainrender (when multiplied by 4 to plot on top of the 25 um atlas you guys use). 

These are points that I have transformed into the ARA using [CloudReg](https://www.nature.com/articles/s41592-021-01218-z) from Josh Vogelstein and Vikram Chandrashekhar. My points look as expected when plotted on the ARA in neuroglancer. And I looked up the exact atlas stacks used by both CloudReg and brainrender and they appeared identical, aside from the 4x scale factor, so I do not think that atlas incompatibility is the issue either. But as you can see, the most posterior points appear outside of the brain in only brainrender but not in neuroglancer. The more anterior points look more accurate.

I chose points at the front and back and along the midline of the brain to illustrate my issue. With that said, I see what seems to be a multiplicative offset on the Z and X axes. Do you guys know why this could potentially be?

Screenshots and example below. Two of the screenshots are from brainrender and the other two are the expected output when the points are plotted in neuroglancer.

```
## fp is the path to the json file I uploaded

# to convert between the 100 micron and 25 micron atlases
global_scale = 4

# load up the json 
with open(save_path, 'r') as fp:
    coords = json.load(fp)

# set up brainrender and a basic scene
brainrender.settings.SHADER_STYLE = 'cartoon'
brainrender.settings.ROOT_ALPHA = .25
brainrender.settings.DEFAULT_ATLAS = 'allen_mouse_100um'
embedWindow(None)
new_plotter = Plotter()
scene = brainrender.Scene(plotter=new_plotter)

# plot and render the points
for points in coords:
    pt = np.array(points['point'])*global_scale
    scene.add(brainrender.actors.points.Point(pt))
scene.render(camera=camera, zoom=1)
fn.append(scene.screenshot())
view(scene.plotter.show(*scene.renderables, `interactive=False))
```
![M5-brainrender_screenshot_20210806_134810](https://user-images.githubusercontent.com/131403/128571750-4a1abf3f-f9f6-4185-a479-8a85e7fd5c54.png)
![M5-brainrender_screenshot_20210806_134814](https://user-images.githubusercontent.com/131403/128571753-f39abc19-bae7-47b3-be5d-97747739f048.png)
![M5-sagittal](https://user-images.githubusercontent.com/131403/128571754-04a7896f-3e4c-4ae9-b6a3-c1551626687c.png)
![M5-top](https://user-images.githubusercontent.com/131403/128571755-3be51d3b-75c0-46d6-8db1-91fab36f45d9.png)

Data JSON containing points:
```
[{"point": [244.74099345789736, 829.903482729078, 1472.6802775365259], "type": "point", "id": "9125a76ef6f411eb8ce9a0369ff79b40", "description": "points_0"}, {"point": [684.3982305730708, 867.3526540253052, 1476.158680061234], "type": "point", "id": "9125a76ff6f411eb8ce9a0369ff79b40", "description": "points_1"}, {"point": [1082.1105137416644, 830.8877912111058, 1476.2668379711163], "type": "point", "id": "9125a770f6f411eb8ce9a0369ff79b40", "description": "points_2"}, {"point": [2071.3232625509, 784.2561169243751, 1476.232580373937], "type": "point", "id": "9125a771f6f411eb8ce9a0369ff79b40", "description": "points_3"}, {"point": [2749.088166103844, 790.0171149073026, 1480.341961034197], "type": "point", "id": "9125a772f6f411eb8ce9a0369ff79b40", "description": "points_4"}, {"point": [3427.2605816967375, 846.3932303849405, 1492.1338806013878], "type": "point", "id": "9125a773f6f411eb8ce9a0369ff79b40", "description": "points_5"}, {"point": [3449.1432826751466, 786.9751268631277, 986.1612415986593], "type": "point", "id": "9125a774f6f411eb8ce9a0369ff79b40", "description": "points_6"}, {"point": [3411.2577339447857, 926.9277680616727, 2058.4942532738046], "type": "point", "id": "9125a775f6f411eb8ce9a0369ff79b40", "description": "points_7"}]
```

**Comment by FedeClaudi** [comment]
hey, I'll have a more detailed look as soon as I can, but my hunch would be that there's a difference in where the origin is defined between the two software. I haven't used neuroglancer, but if you have stacks for its atlas you can try loading both that and brainglobe's into napari to compare them. Or you can try loading neuroglancer's stacks in brainrender as a Volume actor to see if they are well aligned.

**Comment by tamachado** [comment]
Thanks for the quick response! I think they both use a top anterior corner of the atlas as the origin, and the points don't seem flipped, so they are probably the same? The weird thing here is that I think I am seeing a multiplicative scaling offset of about .925 on the A-P and D-V axes (but not the M-L axis).

Plotting the Neuroglancer stack as a volume actor is a good idea though, I'll try that now.

**Comment by tamachado** [comment]
Ah, I figured it out, there is a scale factor buried in Neuroglancer that's only applied to the X and Z axes (and it's .93) so the problem was with my points after all. Plotting the volume actor helped me figure this out, so thanks. I'll close this.

**Comment by FedeClaudi** [comment]
Awesome, happy its fixed (and that it wasn't a brainrender bug :P )
