### ISSUE TITLE
BUG - brainrender does not initialise due to lack of vedo.closePlotter in vedo==2021.0.5

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/brainrender#172]
With the new version of vedo `2021.0.5`, `closePlotter` seems to have been removed ([commit](https://github.com/marcomusy/vedo/commit/51298fbfbfb99b59ea0903b131e8b8081aa6ad8b#diff-f34e7acb92a4bfaea438a2710719a5ba1c4390796e9a46ab6122ec09cfa10b76)), so `brainrender` and `brainrender-gui` crash with:

```bash
    from vedo import Plotter, closePlotter
ImportError: cannot import name 'closePlotter' from 'vedo' (/home/adam/miniconda3/envs/brainrender/lib/python3.7/site-packages/vedo/__init__.py)

```

**Comment by marcomusy** [comment]
yep, you should use 
`plt.close()`

**Comment by FedeClaudi** [comment]
Thanks guys, I'm about to publish a new version with a fix.
@marcomusy  I'm having a problem with multiple semi-transparent meshesh, if I set `useDepthPeeling=False` meshes that are behind get rendered on top of those on front (e.g. the pink area should be behind all others): 
![image](https://user-images.githubusercontent.com/17436313/131630172-7c08fff2-fcbd-4c0b-84b9-8ba8fc015944.png)

but if i set `useDepthPeeling=True` then only the meshes' outlines get rendered: 
![image](https://user-images.githubusercontent.com/17436313/131630263-3ef2c7c6-3eef-4c2d-b616-91db45ff2700.png)

Other settings like `useSSAO` and `useFXAA` don't seem to have a noticeable impact.
Any idea what could be the cause of the problem?

**Comment by marcomusy** [comment]
Hi @FedeClaudi that looks scary... can you confirm that the problem is not there with the same vtk version in vedo version 2021.0.3? you can use `vedo --info`

**Comment by FedeClaudi** [comment]
![image](https://user-images.githubusercontent.com/17436313/131664876-23e4958f-b651-44ca-9084-2746ac7e235b.png)

there's still weird transparency issues (the red area is behind the green, also the black outlines becomes green for the red area when its behind the green one):
![image](https://user-images.githubusercontent.com/17436313/131664912-b61c5bfb-44b9-4aa2-bd2f-1e2428cd5251.png)

with the depth peeling I still get everything transparent.

The transparency issue is there also using vedo's examples (`cartoony.py`):
![image](https://user-images.githubusercontent.com/17436313/131665282-09ffcf08-31c4-47ea-ab8b-218a8eb874d6.png)

with `useDepthPeeling =True`:
![image](https://user-images.githubusercontent.com/17436313/131665367-917aaa04-c0a2-496c-8314-1c7f43e86109.png)

**Comment by FedeClaudi** [comment]
Changing python and vtk version did not help either.

**Comment by marcomusy** [comment]
That's strange I cannot reproduce the issue on my ubuntu:
![Screenshot from 2021-09-01 14-00-30](https://user-images.githubusercontent.com/32848391/131667774-88502f0f-0f36-45d7-9fbd-aa664bbff4f6.png)
I wonder if that's due to the mac graphic card. 

Playing various combinations with this:
```python
from vedo import *

settings.useDepthPeeling = True
settings.multiSamples = 8

plt = Plotter() 
man = Mesh(dataurl+'man.vtk'  ).lighting('off').c('pink'  ).alpha(1.0)
ted = Mesh(dataurl+'teddy.vtk').lighting('off').c('sienna').alpha(0.5)
ted.scale(0.4).rotateZ(-45).pos(-1,-1,-1)

plt.show(ted, man, 
         ted.silhouette(),
         man.silhouette(featureAngle=40).lineWidth(3).color('dr'),
)
```
![Screenshot from 2021-09-01 14-03-59](https://user-images.githubusercontent.com/32848391/131668218-3ee06e33-970b-4b7c-8bd9-44b49c23487c.png)

seems to give the expected result.. Try set multisamples to 0.

**Comment by FedeClaudi** [comment]
Settings `multisamples=0` gets rid of the disappearing meshes with `useDepthPeeling` and improves the transparency issues, but it doesn't fix everything. 
When there's only two semi-transparent meshes overlapping it gets it right:
![image](https://user-images.githubusercontent.com/17436313/131669137-99f1f493-e960-4021-9b92-ff40abb0885b.png)
 
but with 3 it messes up:
![image](https://user-images.githubusercontent.com/17436313/131669188-6e139c82-afe9-4d4b-ba58-5c6c005fa662.png)

Also with only two meshes it works ok if I'm close enough with the camera, if I zoom out it's as if it wasn't using depth peeling:
![image](https://user-images.githubusercontent.com/17436313/131669318-87b8db20-d6f4-4a40-950d-984ae908dae3.png)


On windows using `multiSamples=8` works fine:
![image](https://user-images.githubusercontent.com/17436313/131669633-ddef839b-73c5-4d08-a162-fcc8d7ca11a8.png)

but if I set `useDepthPeeling=False` I get the transparent meshes

**Comment by marcomusy** [comment]
this transparency thing makes me want to cry..... maybe in the first case you mentioned increasing `maxNumberOfPeels=12` helps?
Unfortunately the combination of these settings can be tricky in VTK depending on the actual machine, I tried to find a compromise  in the defaults  - but apparently it's not good enough.

**Comment by FedeClaudi** [comment]
Yeah I can imagine! It used to be okay on both machines in the past though.
Anyways, I will try setting parameters differently based on the machine to see if that gets rid of most issues.

@adamltyson  I just push a commit and a new release on pip if you want to try it out.

**Comment by adamltyson** [comment]
Looks good, thanks @FedeClaudi

**Comment by hackedintothemainframe** [comment]
Hi, 

is there any temporary fix to the original crash issue? Else, can you point to a previous version that is functional? 

Thank you

**Comment by FedeClaudi** [comment]
hi, have you tried to upgrade brianrender? It should work no
```
pip install -U brainrender
```

**Comment by hackedintothemainframe** [comment]
Thank you @FedeClaudi! 
I had originally reverted to this version because version 2.0.4.4 had not originally worked, which I now realize is because it did not automatically install PySide 2 and its dependencies (see [issue #138 ](https://github.com/brainglobe/brainrender/issues/138))
All seems to be in working order now!
