### ISSUE TITLE
BUG: Fail to close the rendering window

### ISSUE THREAD

**Issue by XiaochenFu** [brainglobe/brainrender#175]
**Describe the bug**
I can open the rendering window with scene.render(), but I could not close the window by press 'Esc' or 'q'. When I click the red cross at the right up corner of the window, python froze. 
This happens in Jupyter Notebook and Python IDLE.

**To Reproduce**
`brainrender`  version: 2.0.4.4
 `vedo` version: 2021.0.6
OS: windows 10

Then tell us the steps to reproduce the behavior:
*When I use python IDLE*
1. run the following lines. (Nothing happens)
from brainrender import Scene
from vedo import embedWindow, Plotter, show
embedWindow(None)
2. run the following line. The window poo out, title 'Visualization Toolkit Win32OpenGL 1'
popup_scene = Scene(title='popup')
popup_scene.add_brain_region('MOs')
3. run the following line. The title of the popout window becomes 'brainrender'
embedWindow(None)
4. See error.  'Closing window. Plotter.escaped is set to True.' was printed on screen, but the window was not closed. 

*When I use python IDLE*
1. run the following lines. (Nothing happens)
from brainrender import Scene
from vedo import embedWindow, Plotter, show
embedWindow(None)
2. run the following line. The window poo out, title 'Visualization Toolkit Win32OpenGL 1'
popup_scene = Scene(title='popup')
popup_scene.add_brain_region('MOs')
3. run the following line. The title of the popout window becomes 'brainrender'
embedWindow(None)
I have to restart the kerel to close the window. 

**Expected behavior**
I expect the pop-up windows to be closed, but it freezes 

**Screenshots**
![image](https://user-images.githubusercontent.com/45837330/140317408-dd1302a2-118b-47f4-93e4-6121e1650e30.png)

**Comment by FedeClaudi** [comment]
Hi, 

Thanks for the detailed report. 

Just to confirm, everything works fine when you're not using Jupyter Notebooks?
Have you tried different options for `embedWindow`, as shown in this example notebook: https://github.com/brainglobe/brainrender/blob/master/examples/notebook_workflow.ipynb ?


@marcomusy sorry to bother you, but has something changed with how to close a pop up windows when using vedo in notebooks?

**Comment by XiaochenFu** [comment]
Thank you so much for your quick reply!

*Just to confirm, everything works fine when you're not using Jupyter Notebooks?*
No. The rendering window cannot be closed as well when I'm not using Jupyter Notebooks

*Have you tried different options for embedWindow, as shown in this example notebook: https://github.com/brainglobe/brainrender/blob/master/examples/notebook_workflow.ipynb ?*
Yes, the enbadded window seems to be working fine!

**Comment by marcomusy** [comment]
> @marcomusy sorry to bother you, but has something changed with how to close a pop up windows when using vedo in notebooks?

no worries... No in principle nothing has changed in that respect... if the window is external.
