### ISSUE TITLE
each keyframe causes an increase in zoom

### ISSUE THREAD

**Issue by blogeman** [brainglobe/brainrender#178]
brainrender = 2.0.4.4
vedo = 2021.0.7
python = 3.7
OS = Windows 10
anaconda terminal (no jupyter)

I've had enough success with brainrender to be excited about using it, but seem to be experiencing a step learning curve with Animation. My goal is to render videos highlighting various brain regions.  

I started by trying to re-create the videos from the Elife paper. First I tried running brainrender/paper/videos/probes_video.py but was never able to figure out how to install the oneibl.onelight package. I then tried brainrender/paper/videos/mouse_neurons_video.py and after having to comment out a couple lines (see code below) I was able to render and save a video. However, the transitions between keyframes is abrupt causes the camera to zoom in every time. For example, the transition from cam0 to cam2 during the first  5 seconds is smooth, but then at 5 seconds the transition from cam2 to cam1 is an immediate transportation with no interpolation. Furthermore, at each keyframe transition the camera zooms in much more than the video in the paper. The zoom effect is additive so much so that by the final few frames the fiber track of a single neuron is taking up most of the screen.

I've played around with custom camera values but always seem to get this transportation/zoom effect and am not sure what I am doing wrong. Any help/suggestions is much appreciated. 

`from rich import print
import sys
from pathlib import Path

from brainrender import Scene, Animation
from morphapi.api.mouselight import MouseLightAPI
from brainrender.actors import make_neurons

sys.path.append("./")
from paper.figures import INSET, SILHOUETTE

# define three camera positions
cam0 = {
    "pos": (-27734, -17206, 30307),
    "focalPoint": (5703, 3283, -3835),
    "viewup": (0, -1, 0),
    "distance": 51995,
    "clippingRange": (35301, 77678),
}

cam1 = {
    "pos": (6967, -1597, 30135),
    "focalPoint": (4063, 1645, 1110),
    "viewup": (0, -1, 0),
    "distance": 29350,
    "clippingRange": (28096, 49788),
}
cam2 = {
    "pos": (8151, 2782, 30286),
    "focalPoint": (7168, 3838, 971),
    "viewup": (0, -1, 0),
    "distance": 29350,
    "clippingRange": (23584, 51780),
}

print("[bold red]Running: ", Path(__file__).name)

# -------------------------- define frames callback -------------------------- #

def slc(scene, *args):
    """
    Slices some scene actors and makes sure silhouettes are updated
    """
    sils = scene.get_actors(br_class="silhouette")
    scene.remove(*sils)

    mos = scene.get_actors(name="MOs")[0]
    th = scene.get_actors(name="TH")[0]
    sc = scene.get_actors(name="SCm")[0]

    plane = scene.atlas.get_plane(norm=[0, 0, -1])
    scene.slice(plane, actors=[scene.root, th, mos])

    th._needs_silhouette = True
    mos._needs_silhouette = True
    scene.root._needs_silhouette = True
    sc._needs_silhouette = True

# ----------------------------------- Scene ---------------------------------- #

scene = Scene(inset=INSET)#, screenshots_folder="paper/screenshots") ########### EDITED##############
scene.root._needs_silhouette = SILHOUETTE

# add neruons
mlapi = MouseLightAPI()
neurons_metadata = mlapi.fetch_neurons_metadata(
    filterby="soma", filter_regions=["MOs"]
)

to_add = [neurons_metadata[47], neurons_metadata[51]]
neurons = mlapi.download_neurons(to_add, soma_radius=500)
neurons = scene.add(*make_neurons(*neurons, neurite_radius=12))

# add brain regions
th = scene.add_brain_region("TH", alpha=0.3, silhouette=SILHOUETTE)
mos = scene.add_brain_region("MOs", alpha=0.3, silhouette=SILHOUETTE)
scm = scene.add_brain_region("SCm", alpha=0.3, silhouette=SILHOUETTE)

# ----------------------------- create animation ----------------------------- #

anim = Animation(scene, "videos", "neurons")#, size=None) ########### EDITED##############

# Specify camera pos and zoom at some key frames`
anim.add_keyframe(0, camera=cam0, zoom=1.8)
anim.add_keyframe(5, camera=cam2, zoom=1.8, callback=slc)
anim.add_keyframe(10, camera=cam1, zoom=3.5)
anim.add_keyframe(15, camera=cam2, zoom=4)

# Make videos
anim.make_video(duration=15, fps=30)`

**Comment by FedeClaudi** [comment]
Hi, 

Thank you for getting in touch with this issue.

The onelib is documented here: https://int-brain-lab.github.io/ONE/notebooks/one_quickstart.html

When pasting code, please put it between triple backticks "`" such that it gets formatted correctly:
```python
import  numpy as np

# create an array
np.ones(100)
```

as opposed to:
import  numpy as np

# create an array
np.ones(100)


----
The example file: [`examples/animation.py`](https://github.com/brainglobe/brainrender/blob/master/examples/animation.py) includes a minimal animation example, does that work for you?

Regarding the zooming issue: when specifying a keyframe of the animation, you can set the camera position and the zoom
```python
anim.add_keyframe(0, camera=cam0, zoom=1.8)
```
The zoom values used in the eLife scripts were good for the code back then, but the way the zoom parameter is realized into the 3D rendering has since changed. As such the fix is simply to use much smaller (`<1.1`) value so that you can zoom in less. In general, `zoom<1` results in zooming out, `zoom=1` doesn't change the zoom and `zoom>1` zooms in.

The `camera` parameter sets the position and orientation of the camera, but the zoom is set separately.


For the second problem, I'm not sure what the causes is. Can you provide a (formatted) minimal example code that reproduces it?

**Comment by blogeman** [comment]
Hi @FedeClaudi. Thanks for your help and kind suggestions. The example file you link to works for me and highlights one of the issues I am encountering. Below is a shorted version of the example that I will be referring to (thanks teaching me how properly insert code):

```
from brainrender import Scene, Animation
from rich import print
from myterial import orange
from pathlib import Path

print(f"[{orange}]Running example: {Path(__file__).name}")
"""
    This example shows how to create an animated video by specifying
    the camera parameters at a number of key frames
"""
# Create a brainrender scene
scene = Scene(title="brain regions", inset=False)

# Add brain regions
scene.add_brain_region("TH")

anim = Animation(scene, "./examples", "vid3")

# Specify camera position and zoom at some key frames
# each key frame defines the scene's state after n seconds have passed
anim.add_keyframe(0, camera="top", zoom=1, interpol='linear')
anim.add_keyframe(1, camera="sagittal", zoom=1, interpol='linear')

# Make videos
anim.make_video(duration=1, fps=15)
```

The camera starts in the 'top' position and the initial movement is to zoom in before zooming out while rotating to the 'sagittal' position (zoom might not be the appropriate term, but I hope you see what I mean). This is in contrast to the first few seconds of Video 2 from the Elife paper where the transition from the first camera angle to the second angle is linear and without a zoom-in/zoom-out effect. My goal is to figure out how to write the code above to be like Video 2 with the linear camera transition. I initially thought setting both keyframes to have linear interpolation would fix the problem, but I'm still getting the same effect.

Is there a way to make the transition linear?

**Comment by FedeClaudi** [comment]
Hi,

Thank's for the info.

There was a bug with the `Animation` class such that it wasn't interpolating the zoom value between keyframes.  That's now (a6e92db7135a67944f1e961ce52a8bcaa7d33f10) fixed, so this works for me:

```python

from brainrender import Scene, Animation
from rich import print
from myterial import orange
from pathlib import Path

print(f"[{orange}]Running example: {Path(__file__).name}")
"""
    This example shows how to create an animated video by specifying
    the camera parameters at a number of key frames
"""
# Create a brainrender scene
scene = Scene(title="brain regions", inset=False)

# Add brain regions
scene.add_brain_region("TH")

anim = Animation(scene, "./examples", "vid3")

# Specify camera position and zoom at some key frames
# each key frame defines the scene's state after n seconds have passed
anim.add_keyframe(0, camera="top", zoom=1,)
anim.add_keyframe(.5, camera="top", zoom=0.9,)
anim.add_keyframe(1, camera="top", zoom=1,)
anim.add_keyframe(1.5, camera="sagittal", zoom=1.4,)
anim.add_keyframe(2, camera="sagittal", zoom=1,)


# Make videos
anim.make_video(duration=2.5, fps=15)
```

To test it, first update brainrender with: `pip install -U git+https://github.com/brainglobe/brainrender.git`


---
```python
# btw "```python" at the start of a code section highlights the code syntax like the one above
```

**Comment by blogeman** [comment]
Thanks for the interpolation fix, working nicely now.
