### ISSUE TITLE
BUG GUI does not populate root scenery

### ISSUE THREAD

**Issue by FKiffer** [brainglobe/brainrender#183]
**Describe the bug**
When attempting to open the GUI, the root background does not populate (see screenshot). No other actors populate the background at all.

**To Reproduce**
Mac OS 11.6

Brainrender 2.0.4.5

Vedo-2021.0.7

Python 3.8.0 (in conda env)

Then tell us the steps to reproduce the behavior:
In conda env, run brainrender-gui

**Expected behavior**
GUI is supposed to open and populate the root scenery

**Screenshots**
![Screen Shot 2021-12-17 at 12 38 02 PM](https://user-images.githubusercontent.com/92173929/146586799-45c221b4-207a-4ee1-bb6a-218fc8cc7d06.png)

In the terminal (Key value Observer Error?):
`qt.qpa.fonts: Populating font family aliases took 708 ms. Replace uses of missing font family "Roboto" with one that exists to avoid this cost. 
qt.qpa.window: <QNSWindow: 0x7f9dcbaa4480; contentView=<QNSView: 0x7f9dc9a0c4a0; QCocoaWindow(0x7f9dc95c2d60, window=QWidgetWindow(0x7f9dc991a3e0, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
qt.qpa.window: <QNSWindow: 0x7f9dcbaa5e90; contentView=<QNSView: 0x7f9dcbaa5bd0; QCocoaWindow(0x7f9dcbaa4eb0, window=QWidgetWindow(0x7f9dcbaa45f0, name="CentralColumnWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
qt.qpa.window: <QNSWindow: 0x7f9dcb867b80; contentView=<QNSView: 0x7f9dcb867490; QCocoaWindow(0x7f9dcb867380, window=QWidgetWindow(0x7f9dcb866e80, name="QSplitterClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
qt.qpa.window: <QNSWindow: 0x7f9dc381d430; contentView=<QNSView: 0x7f9dc381cd00; QCocoaWindow(0x7f9dc381cbf0, window=QWidgetWindow(0x7f9dc381c6f0, name="MainWidgetWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.`

**Comment by FedeClaudi** [comment]
Hi, 

Is this still an issue? Can you give me more details about your setup? Are you suing `pyqt`?

**Comment by RobertoDF** [comment]
I had the same problem with my mac when I was installing pyqt with conda (conda install -c anaconda pyqt). pip install PyQt5 solved it. On Ubuntu pyqt installed from conda seems to work but actually it creates some subtle problems (for ex. with meshes transparency), took quite long to understand that was the reason..... maybe there should be a disclaimer somewhere to use only pip?

**Comment by FKiffer** [comment]
Thanks @RobertoDF .

I reinstalled PyQt5 using pip, it works fine now.
