### ISSUE TITLE
"Points" class multiple colors in gui

### ISSUE THREAD

**Issue by RobertoDF** [brainglobe/brainrender#189]
Hi Federico,

I'm trying to use the Points class inside the gui however I cannot assign a different color to each point. Outside the gui everything works fine:

```
import random
import numpy as np

from brainrender import Scene
from brainrender.actors import Points

def get_n_random_points_in_region(region, N):

    region_bounds = region.mesh.bounds()
    X = np.random.randint(region_bounds[0], region_bounds[1], size=10000)
    Y = np.random.randint(region_bounds[2], region_bounds[3], size=10000)
    Z = np.random.randint(region_bounds[4], region_bounds[5], size=10000)
    pts = [[x, y, z] for x, y, z in zip(X, Y, Z)]

    ipts = region.mesh.insidePoints(pts).points()
    return np.vstack(random.choices(ipts, k=N))


scene = Scene(title="Labelled cells")

# Get a numpy array with (fake) coordinates of some labelled cells
mos = scene.add_brain_region("MOs", alpha=0.10)
coordinates = get_n_random_points_in_region(mos, 3)

# Add to scene
scene.add(Points(coordinates, radius=40, name="CELLS", colors=['#A44A3F', '#d4e09b', '#290b55']))

# render
scene.content
scene.render()

```

The color assignment for Points class with multiple colors in the gui breaks here:
https://github.com/brainglobe/brainrender/blob/b414cebfc19a4ad8a230fe87eab6b68b562d3069/brainrender/gui/app.py#L164-L167
because mesh.color() returns always (1. ,1. , 1.) when colors is a list with multiple values. If I assign the same color to all points (a list with one element only) everything runs fine.

You can check this here:

```
a=Points(np.array([[1,2,3],[2,3,4],[1,2,3]]), radius=40, name="CELLS", colors=['#07051b', '#1e0c45', '#290b55'])
a.mesh.color()
```

I'm not sure what's the best solution to this, should I just switch to the Point (singular) class if I want to assign different colors to each point?

**Comment by RobertoDF** [comment]
I just found that if I modify this https://github.com/brainglobe/brainrender/blob/b414cebfc19a4ad8a230fe87eab6b68b562d3069/brainrender/gui/app.py#L164-L167 to this====>
```
 if actor.name not in self.actors.keys(): 
     self.actors[actor.name] = self.atuple( 
         actor, True, None, actor.mesh.alpha() 
     ) 
```
the color assignment works, however I lose the possibility to modify alpha and color in the gui.....

**Comment by FedeClaudi** [comment]
Sorry Robert, I missed this the last few days. Is it resolved?

**Comment by RobertoDF** [comment]
No worry :), the solution I found is good enough. I'm not interested in modifying color and alpha after the mesh has been created, so I also reassigned those buttons to different functions.

**Comment by FedeClaudi** [comment]
Haha smart, very nice! Enjoy!
