### ISSUE TITLE
Vedo update causes issue with volume actor colormap creation

### ISSUE THREAD

**Issue by davoudian** [brainglobe/brainrender#192]
Tested with volume actor (ABA gene expression), using `gene_expression.py` example script. 

**To Reproduce**
brainrender version: 2.0.5.0, vedo version: 2022.0.1. reverting to vedo version 2021.0.5 resolves the bug.

Then tell us the steps to reproduce the behavior:
Run `gene_expression.py` example script, will result in:
![actual](https://user-images.githubusercontent.com/5169381/153648347-0bd8790f-248a-433c-8f88-e07a657cd9d3.png)

**Expected behavior**
expected:
![expected](https://user-images.githubusercontent.com/5169381/153648388-55ad5c6e-e236-44e6-ad2e-e57c92b2dca7.png)

**Comment by marcomusy** [comment]
my first guess is that some `None` slipped in as color..

**Comment by marcomusy** [comment]
Is this solved by the new vedo version ?

**Comment by FedeClaudi** [comment]
Let me know if this helps!
