### ISSUE TITLE
brainrender-gui KeyError: 'notebookBackend'

### ISSUE THREAD

**Issue by jjtukker** [brainglobe/brainrender#197]
Hi,
I just made a fresh install of brainrender with pip in a new conda environment (conda create --name brainrender2 python=3.7)(
the only additional thing I installed was spyder), on Kubuntu20.04, and brainrender-gui gives following errors:

(brainrender2) kiosk@stitcher:/mnt/data/Friedrich/DRD003240222Malinda$ brainrender-gui
╭─ file: /home/kiosk/anaconda3/envs/brainrender2/bin/brainrender-gui:8 line 8 ──────────────────────────────────────────────╮
│                                                                                                                           │
│  Error line:                                                                                                              │
│    8     sys.exit(clilaunch())                                                                                            │
│                                                                                                                           │
│  Local variables                                                                                                          │
│                                                                                                                           │
│             object   value                                                    type                                info    │
│   ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────  │
│        clilaunch =   <Command clilaunch>                                      click.core.Command                          │
│                                                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─ file: /home/kiosk/anaconda3/envs/brainrender2/lib/python3.7/site-packages/brainrender/_jupyter.py:12 line 12 ────────────╮
│                                                                                                                           │
│  Error line:                                                                                                              │
│    12         if vedo.settings.notebookBackend == "k3d":                                                                  │
│                                                                                                                           │
│  Local variables                                                                                                          │
│                                                                                                                           │
│             object   value                                                    type                                info    │
│   ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────  │
│             self =   <repr-error "'Scene' object has no attribute             brainrender.scene.Scene                     │
│                      'actors'">                                                                                           │
│                                                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─ file: /home/kiosk/anaconda3/envs/brainrender2/lib/python3.7/site-packages/vedo/utils.py:238 line 238 ────────────────────╮
│                                                                                                                           │
│  Error line:                                                                                                              │
│     238         return self[k]                                                                                            │
│                                                                                                                           │
│  Local variables                                                                                                          │
│                                                                                                                           │
│           object   value                                               type                             info              │
│   ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────  │
│              k =   notebookBackend                                     builtins.str                     Length: 15        │
│                                                                                                                           │
│           self =   {                                                   vedo.utils.dotdict                                 │
│                        'warn_on_setting': 'bool',                                                                         │
│                        'defaultFont': 'str',                                                                              │
│                        'screeshotScale': 'int',                                                                           │
│                        'screenshotTransparentBackground': 'bool',                                                         │
│                        'screeshotLargeImage': 'bool',                                                                     │
│                        'allowInteraction': 'bool',                                                                        │
│                        'hackCallScreenSize': 'bool',                                                                      │
│                        'enableDefaultMouseCallbacks': 'bool',                                                             │
│                        'enableDefaultKeyboardCallbacks': 'bool',                                                          │
│                        'immediateRendering': 'bool',                                                                      │
│                        'rendererFrameColor': 'NoneType',                                                                  │
│                        'rendererFrameAlpha': 'float',                                                                     │
│                        'rendererFrameWidth': 'float',                                                                     │
│                        'rendererFramePadding': 'float',                                                                   │
│                        'renderLinesAsTubes': 'bool',                                                                      │
│                        'hiddenLineRemoval': 'bool',                                                                       │
│                        'pointSmoothing': 'bool',                                                                          │
│                        'lineSmoothing': 'bool',                                                                           │
│                        'polygonSmoothing': 'bool',                                                                        │
│                        'visibleGridEdges': 'bool',                                                                        │
│                        'lightFollowsCamera': 'bool',                                                                      │
│                        'twoSidedLighting': 'bool',                                                                        │
│                        'useDepthPeeling': 'bool',                                                                         │
│                        'multiSamples': 'int',                                                                             │
│                        'alphaBitPlanes': 'int',                                                                           │
│                        'maxNumberOfPeels': 'int',                                                                         │
│                        'occlusionRatio': 'float',                                                                         │
│                        'useFXAA': 'bool',                                                                                 │
│                        'preserveDepthBuffer': 'bool',                                                                     │
│                        'useSSAO': 'bool',                                                                                 │
│                        'SSAORadius': 'float',                                                                             │
│                        'SSAOBias': 'float',                                                                               │
│                        'SSAOKernelSize': 'int',                                                                           │
│                        'SSAOBlur': 'bool',                                                                                │
│                        'usePolygonOffset': 'bool',                                                                        │
│                        'polygonOffsetFactor': 'float',                                                                    │
│                        'polygonOffsetUnits': 'float',                                                                     │
│                        'interpolateScalarsBeforeMapping': 'bool',                                                         │
│                        'useParallelProjection': 'bool',                                                                   │
│                        'windowSplittingPosition': 'NoneType',                                                             │
│                        'tiffOrientationType': 'int',                                                                      │
│                        'annotatedCubeColor': 'tuple',                                                                     │
│                        'annotatedCubeTextColor': 'NoneType',                                                              │
│                        'annotatedCubeTextScale': 'float',                                                                 │
│                        'annotatedCubeTexts': 'list',                                                                      │
│                        'enablePrintColor': 'bool',                                                                        │
│                        'k3dMenuVisibility': 'bool',                                                                       │
│                        'k3dPlotHeight': 'int',                                                                            │
│                        'k3dAntialias': 'bool',                                                                            │
│                        'k3dLighting': 'float',                                                                            │
│                        'k3dCameraAutoFit': 'bool',                                                                        │
│                        'k3dGridAutoFit': 'bool',                                                                          │
│                        'k3dAxesHelper': 'bool',                                                                           │
│                        'k3dPointShader': 'str',                                                                           │
│                        'k3dLineShader': 'str',                                                                            │
│                        'flagDelay': 'int',                                                                                │
│                        'flagFont': 'str',                                                                                 │
│                        'flagFontSize': 'int',                                                                             │
│                        'flagJustification': 'int',                                                                        │
│                        'flagAngle': 'int',                                                                                │
│                        'flagBold': 'bool',                                                                                │
│                        'flagItalic': 'bool',                                                                              │
│                        'flagShadow': 'bool',                                                                              │
│                        'flagColor': 'str',                                                                                │
│                        'flagBackgroundColor': 'str',                                                                      │
│                        'font_parameters': 'dict'                                                                          │
│                    }                                                                                                      │
│                                                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│                                                                                                  │
│ /home/kiosk/anaconda3/envs/brainrender2/bin/brainrender-gui:8 in <module>                        │
│                                                                                                  │
│   5 from brainrender.gui.__init__ import clilaunch                                               │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(clilaunch())                                                                    │
│   9                                                                                              │
│ /home/kiosk/anaconda3/envs/brainrender2/lib/python3.7/site-packages/click/core.py:1128 in        │
│ __call__                                                                                         │
│                                                                                                  │
│   1125 │                                                                                         │
│   1126 │   def __call__(self, *args: t.Any, **kwargs: t.Any) -> t.Any:                           │
│   1127 │   │   """Alias for :meth:`main`."""                                                     │
│ ❱ 1128 │   │   return self.main(*args, **kwargs)                                                 │
│   1129                                                                                           │
│   1130                                                                                           │
│   1131 class Command(BaseCommand):                                                               │
│                                                                                                  │
│ /home/kiosk/anaconda3/envs/brainrender2/lib/python3.7/site-packages/click/core.py:1053 in main   │
│                                                                                                  │
│   1050 │   │   try:                                                                              │
│   1051 │   │   │   try:                                                                          │
│   1052 │   │   │   │   with self.make_context(prog_name, args, **extra) as ctx:                  │
│ ❱ 1053 │   │   │   │   │   rv = self.invoke(ctx)                                                 │
│   1054 │   │   │   │   │   if not standalone_mode:                                               │
│   1055 │   │   │   │   │   │   return rv                                                         │
│   1056 │   │   │   │   │   # it's not safe to `ctx.exit(rv)` here!                               │
│                                                                                                  │
│ /home/kiosk/anaconda3/envs/brainrender2/lib/python3.7/site-packages/click/core.py:1395 in invoke │
│                                                                                                  │
│   1392 │   │   │   echo(style(message, fg="red"), err=True)                                      │
│   1393 │   │                                                                                     │
│   1394 │   │   if self.callback is not None:                                                     │
│ ❱ 1395 │   │   │   return ctx.invoke(self.callback, **ctx.params)                                │
│   1396 │                                                                                         │
│   1397 │   def shell_complete(self, ctx: Context, incomplete: str) -> t.List["CompletionItem"]:  │
│   1398 │   │   """Return a list of completions for the incomplete value. Looks                   │
│                                                                                                  │
│ /home/kiosk/anaconda3/envs/brainrender2/lib/python3.7/site-packages/click/core.py:754 in invoke  │
│                                                                                                  │
│    751 │   │                                                                                     │
│    752 │   │   with augment_usage_errors(__self):                                                │
│    753 │   │   │   with ctx:                                                                     │
│ ❱  754 │   │   │   │   return __callback(*args, **kwargs)                                        │
│    755 │                                                                                         │
│    756 │   def forward(                                                                          │
│    757 │   │   __self, __cmd: "Command", *args: t.Any, **kwargs: t.Any  # noqa: B902             │
│                                                                                                  │
│ /home/kiosk/anaconda3/envs/brainrender2/lib/python3.7/site-packages/brainrender/gui/__init__.py: │
│ 34 in clilaunch                                                                                  │
│                                                                                                  │
│   31 def clilaunch(atlas=None, axes=False, output=None):                                         │
│   32 │   app = QApplication(sys.argv)                                                            │
│   33 │   app.setApplicationName("Brainrender GUIs")                                              │
│ ❱ 34 │   ex = App(atlas_name=atlas, axes=axes, screenshots_folder=output)                        │
│   35 │   app.aboutToQuit.connect(ex.onClose)                                                     │
│   36 │   ex.show()                                                                               │
│   37 │   sys.exit(app.exec_())                                                                   │
│                                                                                                  │
│ /home/kiosk/anaconda3/envs/brainrender2/lib/python3.7/site-packages/brainrender/gui/app.py:48 in │
│ __init__                                                                                         │
│                                                                                                  │
│    45 │   │   # Get vtkWidget plotter and creates a scene embedded in it                         │
│    46 │   │   new_plotter = Plotter(qtWidget=self.vtkWidget)                                     │
│    47 │   │   self.scene = Scene(                                                                │
│ ❱  48 │   │   │   *args, atlas_name=atlas_name, plotter=new_plotter, **kwargs                    │
│    49 │   │   )                                                                                  │
│    50 │   │                                                                                      │
│    51 │   │   # Initialize parent classes                                                        │
│                                                                                                  │
│ /home/kiosk/anaconda3/envs/brainrender2/lib/python3.7/site-packages/brainrender/scene.py:50 in   │
│ __init__                                                                                         │
│                                                                                                  │
│    47 │   │   logger.debug(                                                                      │
│    48 │   │   │   f"Creating scene with parameters: root: {root}, atlas_name: '{atlas_name}'',   │
│    49 │   │   )                                                                                  │
│ ❱  50 │   │   JupyterMixIn.__init__(self)                                                        │
│    51 │   │                                                                                      │
│    52 │   │   self.actors = []  # stores all actors in the scene                                 │
│    53 │   │   self.labels = []  # stores all `labels` actors in scene                            │
│                                                                                                  │
│ /home/kiosk/anaconda3/envs/brainrender2/lib/python3.7/site-packages/brainrender/_jupyter.py:12   │
│ in __init__                                                                                      │
│                                                                                                  │
│    9 class JupyterMixIn:  # pragma: no cover                                                     │
│   10 │   def __init__(self):  # pragma: no cover                                                 │
│   11 │   │   # keep track if we are in a jupyter notebook                                        │
│ ❱ 12 │   │   if vedo.settings.notebookBackend == "k3d":                                          │
│   13 │   │   │   self.backend = "k3d"                                                            │
│   14 │   │   elif vedo.settings.notebookBackend == "itkwidgets":                                 │
│   15 │   │   │   self.backend = "itkwidgets"                                                     │
│                                                                                                  │
│ /home/kiosk/anaconda3/envs/brainrender2/lib/python3.7/site-packages/vedo/utils.py:238 in         │
│ __getattr__                                                                                      │
│                                                                                                  │
│    235 │   │   │   │   self[k] = dotdict(v)                                                      │
│    236 │                                                                                         │
│    237 │   def __getattr__(self, k):                                                             │
│ ❱  238 │   │   return self[k]                                                                    │
│    239 │                                                                                         │
│    240 │   def __setattr__(self, k, v):                                                          │
│    241 │   │   if self.warn_on_setting:                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
KeyError: 'notebookBackend'
Exception ignored in: <function Scene.__del__ at 0x7fab395cb440>
Traceback (most recent call last):
  File "/home/kiosk/anaconda3/envs/brainrender2/lib/python3.7/site-packages/brainrender/scene.py", line 102, in __del__
    self.close()
  File "/home/kiosk/anaconda3/envs/brainrender2/lib/python3.7/site-packages/brainrender/render.py", line 281, in close
    self.plotter.close()
AttributeError: 'NoneType' object has no attribute 'close'
Exception ignored in: <function Scene.__del__ at 0x7fab395cb440>
Traceback (most recent call last):
  File "/home/kiosk/anaconda3/envs/brainrender2/lib/python3.7/site-packages/brainrender/scene.py", line 102, in __del__
    self.close()
  File "/home/kiosk/anaconda3/envs/brainrender2/lib/python3.7/site-packages/brainrender/render.py", line 281, in close
    self.plotter.close()
AttributeError: 'NoneType' object has no attribute 'close'

Any idea what could be going on? I got a similar notebookBackend error (in a separate conda env) when I ran brainrender from spyder, which could be solved by adding a line
vedo.settings['notebookBackend'] = 'False'

cheers,
John

**Comment by marcomusy** [comment]
Have you tried:
`pip install vedo==2021.0.5`

**Comment by jjtukker** [comment]
> Have you tried: `pip install vedo==2021.0.5`

thanks, that worked!
I just have to report a minor follow-up issue. 
The starting image (line drawing of brain outline) disappears as soon as I click on the "root" text on the "Actors" part of the screen. And after that zoom no longer works. It looks like I can still add another brain area, but cannot I cannot zoom out or in (e.g. if I add cerebellum in turquoise I see CH on the Actors list but I just see the display part of the screen turn turquoise). In this situation, the reset button does not seem to work.

If I do not click on "root" but simply load a brain area, everything works fine (and the "root" disappears from the Actors list). And this is really nice. 

Is there a way to remove brain areas as well? Of course I can just start new at any time, but if this feature exists e.g. via some keyboard shortcut obviously it would be good to know (delete did not do it). Also, is there some way to keep the outline of the brain intact? Selecting "root" as a brain area does not work.
Sorry these are probably not real issues, just user questions but I don't know where else I could get this info.

cheers,
John

**Comment by horsto** [comment]
I ran into this issue under MacOS as well and `pip install vedo==2021.0.5` helped. However, the brainrender-gui seems to be broken: See attached screenshot. No brain is visible, instead I get a cutout in the app. ![Screenshot 2022-03-19 at 10 23 38](https://user-images.githubusercontent.com/7548928/159115516-0fe02951-f922-4a7d-b50a-31ba12b32efe.png)

**Comment by FedeClaudi** [comment]
Oh dear. That's not good. What python version? Have you tried a fresh environment? Which OS version?

Works well for me; 
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/17436313/159176661-eec7a9f8-4b64-4c84-9a5b-1aae3171ec67.png">

> Is there a way to remove brain areas as well? 

I'm afraid not worry. The GUI is meant for quick visualizations, but it's not a fully developed application with all of brainrender's features.

**Comment by jjtukker** [comment]
> 
> Works well for me; <img alt="image" width="1680" src="https://user-images.githubusercontent.com/17436313/159176661-eec7a9f8-4b64-4c84-9a5b-1aae3171ec67.png">

The screen you show is also what I get when I open brainrender, and indeed it works fine. The issues start when I either click on "root" in the Actors list (which is not a big deal, fixed by just not clicking on that any more :)), or when I add another area. In the latter case "root" disappears from the list and also the drawing disappears (only the newly added areas are shown), and then I cannot get it back by choosing root again. It seems like this is simply blocked, although it does show up in the structure tree. Does this not happen for you? It this expected/desired behavior? 

It would be nice to have some way in the GUI of preserving the brain outline as a visual reference. I appreciate that the GUI is not a fully developed application, I just want to make sure that this feature is in fact not there, rather than just not working for me (e.g. because I am doing something stupid). Thanks!

**Comment by FedeClaudi** [comment]
I'm sorry it appears I had tested an older version of brainrender, with the newsest I get the same problem as @horst and this error message
```
qt.qpa.fonts: Populating font family aliases took 739 ms. Replace uses of missing font family "Roboto" with one that exists to avoid this cost. 
qt.qpa.window: <QNSWindow: 0x7fb41e66c710; contentView=<QNSView: 0x7fb40f2e3930; QCocoaWindow(0x7fb40f2e3860, window=QWidgetWindow(0x7fb3ff80b3e0, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
qt.qpa.window: <QNSWindow: 0x7fb408962e10; contentView=<QNSView: 0x7fb408962b50; QCocoaWindow(0x7fb408951a60, window=QWidgetWindow(0x7fb40894b390, name="CentralColumnWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
qt.qpa.window: <QNSWindow: 0x7fb40896a820; contentView=<QNSView: 0x7fb40896a130; QCocoaWindow(0x7fb40896a020, window=QWidgetWindow(0x7fb408969ae0, name="QSplitterClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
qt.qpa.window: <QNSWindow: 0x7fb43e4c95b0; contentView=<QNSView: 0x7fb43e4c8c80; QCocoaWindow(0x7fb43e4c8b70, window=QWidgetWindow(0x7fb43e4c8690, name="MainWidgetWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
```

@marcomusy have you seen this before?

**Comment by marcomusy** [comment]
I've seen it before:
https://discourse.vtk.org/t/vtkproppicker-not-working-in-osx-and-qt/8057
but unfortunately i'm not familiar with qt at all and I'm not sure what to do with it :(
