### ISSUE TITLE
Colors differ in between scene rendering and video output

### ISSUE THREAD

**Issue by horsto** [brainglobe/brainrender#198]
I started to create videos from my scene in brainrender but noticed a discrepancy in how colors are exported in the video compared to how they are displayed in just normal brainrender views (see attached screenshots). Specifically, video colors seem to be dulled down (darker, less transparency / light over all?). Is there a trick to make them more comparable? Also, can the compression of the video be changed (I saw that the size can be changed, but the resolution is affected by quite some compression in my videos)? 

![Screenshot 2022-03-19 at 12 14 59](https://user-images.githubusercontent.com/7548928/159118912-34870638-a23c-4a12-a766-4e95d6dd21ae.png)
![Screenshot 2022-03-19 at 12 15 08](https://user-images.githubusercontent.com/7548928/159118917-6a8fb887-da17-4f0a-a5f4-f69ff6ee92f9.png)

**Comment by FedeClaudi** [comment]
Hi, 

I've never noticed that before so I'm not sure what could be causing the color difference or how to fix it, sorry. 
No I'm afraid you can't. But if you're willing to hack something together you can use brainrender to pruduce each frame and save it as a screenshot. Then you can crate a video from the saved the saved images with whatever method you like. That's kind of [what vedo does](https://github.com/marcomusy/vedo/blob/240ba3bd8c4a8f2016ddedbc148d52729fd10a0c/vedo/io.py#L1945) under the hood
