### ISSUE TITLE
Screenshot transparent background not enabled

### ISSUE THREAD

**Issue by horsto** [brainglobe/brainrender#199]
If I understand https://docs.brainrender.info/usage/videos-animations-and-exporting-to-html#screenshots correctly, then screenshots should have a transparent background by default? However, I don't seem to be able to get transparent backgrounds (always white). 
I tried 
```python
brainrender.SCREENSHOT_TRANSPARENT_BACKGROUND = True
brainrender.settings.vsettings.screenshotTransparentBackground = True
```
but no success. Is this feature available? 

`vedo.__version__ = '2021.0.5'`
`brainrender.__version__ =  '2.0.5.0'`

**Comment by FedeClaudi** [comment]
I think the docs are a bit outdated on that. Currently they're not transparent by [default](https://github.com/brainglobe/brainrender/blob/402542a6e30360921ad9ec15f1552573eac28ff5/brainrender/settings.py#L22) you need to set:
```python
brainrender.vsettings.screenshotTransparentBackground = True  # vedo for transparent bg
brainrender.vsettings.useFXAA = True  # This needs to be false for transparent bg
```

**before** you create your scene. Also I'm not sure if this works in notebooks if you're using those
