### ISSUE TITLE
Sagittal slicing bug

### ISSUE THREAD

**Issue by RobertoDF** [brainglobe/brainrender#204]
Hi Federico,
I can't slice structures using a custom plane if it is "sagittal".  "frontal" and "horizontal" work fine.  Trying to find the problem, no success....

```
scene = Scene()

ca1 = scene.add_brain_region("CA", alpha=0.1)

plane = scene.atlas.get_plane(pos=ca1.centerOfMass(), plane="sagittal")

scene.slice(plane)

scene.render()
```
Using brainrender 2.0.5.0 vedo 2021.0.5.

**Comment by FedeClaudi** [comment]
doublecheck that the center of mass is where you think it is, it might outside the brain (hence the slicing doesn't slice anything)

**Comment by RobertoDF** [comment]
I am using the center of mass of ca1, frontal and horizontal slicing works fine, I think it's something else
![Screenshot 2022-04-14 at 19 25 20](https://user-images.githubusercontent.com/37729096/163441569-0d0ca2c9-a701-4c56-ae4f-2ce0225bd401.png)

**Comment by RobertoDF** [comment]
further:
if use this plane:
`plane = scene.atlas.get_plane(pos=ca1.centerOfMass(), norm=(0,0,1))`
everything is sliced away, empty scene.
if I use the inverted
`plane = scene.atlas.get_plane(pos=ca1.centerOfMass(), norm=(0,0,-1))`
nothing get sliced.
but the point is definitely inside the brain......So your guess was right, I just don't get why the plane is outside the brain if the center of mass is inside.

**Comment by FedeClaudi** [comment]
mmm, if you pass another set of 3 coordinates what happens?

**Comment by RobertoDF** [comment]
oh! if I make the coordinates all negative it works!!!
![Screenshot 2022-04-14 at 19 39 27](https://user-images.githubusercontent.com/37729096/163443755-11d09fa8-ac1d-48f9-9dd7-bd81ed182a5e.png)
!

**Comment by FedeClaudi** [comment]
it sounds like centerofmass is giving the wrong coordinates?

What version of vedo/vtk/brainrender are you using?

**Comment by RobertoDF** [comment]
Using brainrender 2.0.5.0 vedo 2021.0.5 vtk 8.1.2.

I think the center of mass is right otherwise also the "frontal" or "sagittal" planes would be messed up, isn't it? I think  maybe it's something in the construction of the plane, in Atlas.get_plane()

**Comment by FedeClaudi** [comment]
> I think the center of mass is right otherwise also the "frontal" or "sagittal" planes would be messed up, isn't it? I
if it's right in the AP and DV directions but off to a side, the other planes would be fine. Have you tried visualizing the COM?

**Comment by RobertoDF** [comment]
Yes, it's the dot in the previous screenshots.

**Comment by RobertoDF** [comment]
I don't see anything wrong in Atlas.get_plane()....

**Comment by RobertoDF** [comment]
In any case I managed to reach what I wanted. Thanks for the quick reply again!
![Screenshot 2022-04-14 at 20 16 46](https://user-images.githubusercontent.com/37729096/163452193-5cfbd0ac-f6c0-4900-ac30-44523f3e5c1f.png)

**Comment by LSeu-994** [comment]
Hello @RobertoDF  and @FedeClaudi  if i can add an possible error to this.

I'm currently trying to use brainrender to make a nice visualisation of 3D reconstructed malformations in the DCX rat brain.

When using the whs_sd_rat_39um atlas, it seems there is an orientation error or a bug when slicing the brain.

Actually saggital and horizontal plane are switched.

![0](https://user-images.githubusercontent.com/95351758/163555620-81dc20ef-1bf5-403a-89c6-4785c5092229.JPG)

Here is the result using `scene.slice('sagittal')`

![2](https://user-images.githubusercontent.com/95351758/163555905-2ee9d150-76cd-4674-a197-a62baf1d74ba.JPG)

Here is the result using `scene.slice('horizontal')`

is it a known problem with this atlas ?

**Comment by FedeClaudi** [comment]
> is it a known problem with this atlas ?

It is not! It might be best to raise this in the atlas API repository, I'm not sure who provided this atlas, so there might have been a mixup with the axes directions. Do other things (e.g. camera positioning) work as you'd expect?

**Comment by LSeu-994** [comment]
The camera positioning is dysfunctionnal as well. You are right the axes directions are mixed up. i just raise this issue on the API repos.
