### ISSUE TITLE
Installation issues on x86_64 Ubuntu 20.04.4

### ISSUE THREAD

**Issue by grahamfindlay** [brainglobe/brainrender#205]
I'm trying to use brainrender to visualize Neuropixel probe tracks, but ran into several issues during installation. 

I began by trying a basic installation per [the documentation](https://docs.brainrender.info/installation/installation):

```
conda create -n brainrender python=3.7
conda activate brainrender
pip install brainrender
python
>> from brainrender import Scene; s = Scene()
```

This leads to issue #197, which is fixed by pinning `vedo==2021.0.5`. However, this leads to a new issue, which is an unrecognized keyword argument `print_authors` passed to the `Atlas` constructor on line 26 of `atlas.py`. The latest source shows that this should be handled by commit ae92a40c2769f249d8ae7a040a64d43fad949ba0, so I tried installing from source using `pip install git+https://github.com/brainglobe/brainrender.git`. This leads to a situation where I can `import brainrender`, but `from brainrender import Scene` fails because Python can't find the `brainrender` module. Even though the wheel reports building successfully and `pip show brainrender` shows the correct path. This issue persists also using `pip install https://github.com/brainglobe/brainrender/tarball/master` and `pip install https://github.com/brainglobe/brainrender.git#egg=brainrender`. It also occurs if I clone from source and install using `pip install .` 

FYI, the documentation linked to above references a different, deprecated repository: `https://github.com/BrancoLab/BrainRender.git`. I wonder if it is also not necessary to use python 3.7 as the documentation suggests, since 3.8 is listed as valid target in both `setup.py` and `pyproject.toml`. 

Also, It looks like [the default PyPI release](https://pypi.org/project/brainrender/#history) is version `2.0.5.0`, although for some reason this is timestamped January 19, 2022, while version `2.0.4.7` actually has a *later* release date.

Anyways, I eventually discovered with `pip show -f` and `pip install -vvv` that dist-info and tests are added to the wheel, but the actual brainrender package is not! I suspect the issue lies in line 90 of `setup.py`: `    packages=find_packages(include=("tests",)),`, which should probably include `brainrender`. 

In the end, if I clone from source and do an editable install with `pip install -e .`, this works and I can finally create a `Scene` object. Actually, I'm having new issues with some of the provided examples clearly not rendering properly, but that may be a separate issue, and I haven't had time to look into it yet.

**Comment by noisysky** [comment]
Hi! I am installing brainrender in the fresh environment, and cannot import it afterwards. (Couple of months ago everything was ok.)

```
conda create -n br python=3.8
conda activate br
pip install brainrender
```

```
>>> import brainrender
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'brainrender'
```

**Comment by grahamfindlay** [comment]
Unfortunately, I can neither `import brainrender` nor `from brainrender import Scene` when installing `2.0.5.1` from PyPI. 
```
conda create -n br_pypi python=3.7
conda activate br_pypi
pip install --no-cache-dir -vvv brainrender &> br_pypi.log
```
[br_pypi.log](https://github.com/brainglobe/brainrender/files/8598105/br_pypi.log)

However, I can now import brainrender when doing a non-editable pip install from source:
```
conda create -n br_gh python=3.7
conda activate br_gh
git clone https://github.com/brainglobe/brainrender.git
cd brainrender
pip install --no-cache-dir -vvv . &> br_gh.log
```
[br_gh.log](https://github.com/brainglobe/brainrender/files/8598106/br_gh.log)

I get the same result on Windows.

**Comment by noisysky** [comment]
@grahamfindlay if you need it to work right now, the version 2.0.4.5 works for me in python 3.8 environment. I had to replace the version of vtk from `vtk<=9.0.0` to `vtk<=9.0.1` in setup.py, and then `pip install .`. Source can be downloaded from pypi https://pypi.org/project/brainrender/2.0.4.5/#files

**Comment by grahamfindlay** [comment]
Thanks @noisysky . I actually got the most recent version working using an editable pip install from source (`pip install -e`) before opening the issue 😄.  Just wanted to make sure someone was aware of the problem.

**Comment by FedeClaudi** [comment]
Thanks for the updates.

Something seems to have gone wrong with the latest releases. Perhaps the way the package is created is not compatible with the latest `pip` versions? I'll try to look into this ASAP, in the mean while `pip install -e` seems to work (thanks @grahamfindlay )

**Comment by FedeClaudi** [comment]
I've been trying to figure out what is going on here. 

With the version that is currently on github I can install and use brainrender on windows. I can install it on Mac, and it all looks fine but when I try to use it it fails to find `loguru` or any other package used. So it finds `brainrender`, it's not the same as what you had @grahamfindlay  but it doesn't find other package used within brainrender even though they were install correctly and are in the environment. 

I have no idea why this is happening now or how to fix it! `pip install -e .` also doesn't seem to work for me

**Comment by lcarot** [comment]
Any of the above does not fix the problem for me, the error: No module named "brainrender' persists, any advice?
