### ISSUE TITLE
brainrender install problem:  no module named 'brainrender' 

### ISSUE THREAD

**Issue by AmaranthCao** [brainglobe/brainrender#208]
Hello,

I am trying to install the brainrender based on Anaconda. I created a new env with python3.7 and only installed brainrender package by using "pip install brainrender" in my new env in Anaconda Prompt. When I checked my package list, there is a package called 'brainrender', but when I running it, the first sentence: from brainrender import Scene, it displayed : modulenotfounderror: no module named 'brainrender'? 

Do you know why?

Thanks a lot for your help!

**Comment by FedeClaudi** [comment]
probably related to https://github.com/brainglobe/brainrender/issues/205, will look into it

**Comment by AmaranthCao** [comment]
Hi, Thanks for your suggestion. I have solved the install problem but meet a new AssertionError. I am using you exampled .npy file. But when I was running, it flashed back and displayed: AssertionError: Only arrays of dimensionality 2 or lower are allowed! And bellow is my python code and traceback.

My Code:

from brainrender.scene import Scene
from brainrender.actors import Points

cells_path = "C:/Users/user/Desktop/output/volume.npy"

# intialise brainrender scene
scene = Scene()

# create points actor
cells = Points(cells_path, radius=45, colors="palegoldenrod", alpha=0.8)

# visualise injection site (retrosplenial cortex)
scene.add_brain_regions(["RSPd"], colors="mediumseagreen", alpha=0.6)
#scene.add_brain_regions(["RSPv"], colors="purple", alpha=0.6)
#scene.add_brain_regions(["RSPagl"], colors="mediumseagreen", alpha=0.6)

# Add cells
scene.add(cells)

scene.render()

Traceback:
C:/Users/user/PycharmProjects/TissueClearingPY36/testBrainrender.py:10 in   │
│ <module>                                                                    │
│                                                                             │
│    7 scene = Scene()                                                        │
│    8                                                                        │
│    9 # create points actor                                                  │
│ > 10 cells = Points(cells_path, radius=45, colors="palegoldenrod", alpha=0. │
│   11                                                                        │
│   12 # visualise injection site (retrosplenial cortex)                      │
│   13 scene.add_brain_regions(["RSPd"], colors="mediumseagreen", alpha=0.6)  │
│                                                                             │
│ d:\brainrender-2.0.5.1\brainrender\actors\points.py:105 in __init__         │
│                                                                             │
│   102 │   │   if isinstance(data, np.ndarray):                              │
│   103 │   │   │   mesh = self._from_numpy(data)                             │
│   104 │   │   elif isinstance(data, (str, Path)):                           │
│ > 105 │   │   │   mesh = self._from_file(data)                              │
│   106 │   │   else:  # pragma: no cover                                     │
│   107 │   │   │   raise TypeError(  # pragma: no cover                      │
│   108 │   │   │   │   f"Input data should be either a numpy array or a file │
│                                                                             │
│ d:\brainrender-2.0.5.1\brainrender\actors\points.py:69 in _from_file        │
│                                                                             │
│    66 │   │   if path.suffix == ".npy":                                     │
│    67 │   │   │   self.name = self.name or path.name                        │
│    68 │   │   │   return self._from_numpy(                                  │
│ >  69 │   │   │   │   np.load(path),                                        │
│    70 │   │   │   )                                                         │
│    71 │   │   else:  # pragma: no cover                                     │
│    72 │   │   │   raise NotImplementedError(  # pragma: no cover            │
│                                                                             │
│ d:\brainrender-2.0.5.1\brainrender\actors\points.py:53 in _from_numpy       │
│                                                                             │
│    50 │   │                                                                 │
│    51 │   │   self.name = self.name or "Points"                             │
│    52 │   │   mesh = Spheres(                                               │
│ >  53 │   │   │   data, r=self.radius, c=self.colors, alpha=self.alpha, res │
│    54 │   │   )                                                             │
│    55 │   │   return mesh                                                   │
│    56                                                                       │
│                                                                             │
│ C:\Users\user\.conda\envs\TClearing\lib\site-packages\vedo\shapes.py:2008   │
│ in __init__                                                                 │
│                                                                             │
│   2005 │   │   │   urads.SetName("Radii")                                   │
│   2006 │   │   │   pd.GetPointData().SetScalars(urads)                      │
│   2007 │   │                                                                │
│ > 2008 │   │   vpts.SetData(utils.numpy2vtk(centers, dtype=np.float))       │
│   2009 │   │                                                                │
│   2010 │   │   glyph.SetInputData(pd)                                       │
│   2011 │   │   glyph.Update()                                               │
│                                                                             │
│ C:\Users\user\.conda\envs\TClearing\lib\site-packages\vedo\utils.py:266 in  │
│ numpy2vtk                                                                   │
│                                                                             │
│    263 │   if dtype and dtype=='id':                                        │
│    264 │   │   varr = numpy_to_vtkIdTypeArray(arr.astype(np.int64), deep=de │
│    265 │   else:                                                            │
│ >  266 │   │   varr = numpy_to_vtk(arr, deep=deep)                          │
│    267 │   if name:                                                         │
│    268 │   │   varr.SetName(name)                                           │
│    269 │   return varr                                                      │
│                                                                             │
│ C:\Users\user\.conda\envs\TClearing\lib\site-packages\vtkmodules\util\numpy │
│ _support.py:136 in numpy_to_vtk                                             │
│                                                                             │
│   133 │   shape = z.shape                                                   │
│   134 │   assert z.flags.contiguous, 'Only contiguous arrays are supported. │
│   135 │   assert len(shape) < 3, \                                          │
│ > 136 │   │      "Only arrays of dimensionality 2 or lower are allowed!"    │
│   137 │   assert not numpy.issubdtype(z.dtype, numpy.dtype(complex).type),  │
│   138 │   │      "Complex numpy arrays cannot be converted to vtk arrays."\ │
│   139 │   │      "Use real() or imag() to get a component of the array befo │
└─────────────────────────────────────────────────────────────────────────────┘
AssertionError: Only arrays of dimensionality 2 or lower are allowed!

Thanks a lot for your help!

**Comment by FedeClaudi** [comment]
are you sure that's the correct .npy file, and that the numpy array has the correct shape?

**Comment by AmaranthCao** [comment]
Yeah, this .npy file is just copied from the [brainrender](https://github.com/brainglobe/brainrender)/[examples]/[data]/volume.npy in your giuhub.

**Comment by FedeClaudi** [comment]
`Points` is used to show the location of cells. It accepts a 2D array if Nx3 cell coordinates, volume is a 3D array, hence the error.
