### ISSUE TITLE
kim_mouse atlas plots only one hemisphere

### ISSUE THREAD

**Issue by alowet** [brainglobe/brainrender#210]
Using kim_mouse_50um, for which scaling issues have been solved (see https://github.com/brainglobe/bg-atlasgen/issues/73), individual brain regions plot in only one hemisphere or the other. Consider this snippet:

```
from brainrender import Scene

atlas = 'kim_mouse_50um'

# Create a brainrender scene
scene = Scene(screenshots_folder='.', inset=False, atlas_name=atlas)

# add actors
acb = scene.add_brain_region('Acb', alpha=0.3, color='blue', hemisphere='both')

# render
scene.render(interactive=False, zoom=1)
scene.screenshot(name='example_{}'.format(atlas))
```

This produces the following output:
![image](https://user-images.githubusercontent.com/33499753/170127703-6f84215f-f44c-43b5-8f14-43861c00d684.png)

As you can see, the nucleus accumbens gets plotted only in the left hemisphere. This is contrary to the behavior of allen_mouse_25um and the documented behavior of the hemisphere parameter. It doesn't appear to be a problem with kim_mouse_50um *per se*, as the structure_from_coords function correctly returns the same region regardless of whether the point is in the left or the right hemisphere, and visualizing the meshes directly shows that they exist for both hemispheres. I previously reported this bug on the [bgatlas-api Github](https://github.com/brainglobe/bg-atlasgen/issues/92), but didn't have success there. Any ideas?

**Comment by adamltyson** [comment]
@FedeClaudi do you have an idea whether this is an issue with brainrender or the atlas (or some interaction between the two)?

**Comment by FedeClaudi** [comment]
hi, 

I can't imagine how it could be a brainrender issue. Brainrender might mess something up when one asks for just one hemisphere, but when rendering both hemisphere it just fetches the mesh file from the brainglobe atlas.

If you look at the mesh files independently (either with vedo, napari or another software) do they look fine?

**Comment by FedeClaudi** [comment]
I see.

Indeed it seems to be the case that something's happening in BR. It's  the same for the 25um and 50um versions of the atlas. I can't quite figure out what could be wrong here though, but I'll try look into it when I get a moment.

**Comment by FedeClaudi** [comment]
@alowet  is this still an issue?

**Comment by alowet** [comment]
Yes, as far as I can tell this hasn't been fixed.

**Comment by alowet** [comment]
Hey, any chance you've been able to address this yet?

**Comment by FedeClaudi** [comment]
No sorry, I can't figure it out

**Comment by IgorTatarnikov** [comment]
I think this may be an underlying issue with the atlas meshes themselves, see [brainglobe/bg-atlasapi#114](https://github.com/brainglobe/bg-atlasapi/issues/114#issuecomment-1789285465)
