### ISSUE TITLE
Request for Addition of Specific Layer Information

### ISSUE THREAD

**Issue by sjhkim1** [brainglobe/brainrender#214]
Hello, 
Is there a way you could add specific layer information to the visualizer, or is it impossible at the moment because it is connected to the Allen Reference Atlas whose CCFv3 excludes that kind of information?
ex) CA1slm, CA1so, CA1sp, CA1sr instead of simply a catch-all parcel for CA1

**Comment by adamltyson** [comment]
Hey @sjhkim1, brainrender will only be able to show the information contained in the atlas that you're using (e.g. the Allen atlas). If the atlas doesn't contain the regions labelled individually, then brainrender won't be able to visualise it. There are other mouse atlases available in brainrender that have more regions (such as the [Enhanced and Unified Mouse Brain Atlas](https://kimlab.io/brain-map/atlas/)), but the quality of the 3D meshes is lower.
