### ISSUE TITLE
root mesh of atlas not visualised

### ISSUE THREAD

**Issue by chrytsi** [brainglobe/brainrender#215]
**Describe the bug**
Brainrender GUI does not visualise the root mesh of the atlas selected. 
Same problem when using `pip install brainrender` and `pip install -U git+https://github.com/BrancoLab/BrainRender.git`

Besides me, there are two other users hat I know of who have the same issue.

**To Reproduce**
I believe version 2.0.5.3 of brainrender  and vedo-2021.0.5 (ran `pip install brainrender` today)
both  macOS 12.4 and Windows 10  
both Python 3.6 and 3.7 in vitrual environments

Then tell us the steps to reproduce the behavior:
ran `brainrender-gui -a allen_mouse_10um` in conda env
needed to install PyQt5 by running `pip install PyQt5` after brainrender installation

**Expected behavior**
GUI to start and open a window visualizing the root mesh of the atlas selected.

**Screenshots**
<img width="1440" alt="Screenshot 2022-08-11 at 15 11 44" src="https://user-images.githubusercontent.com/34349487/184153569-cf17ef25-b4b0-4428-aee4-30ab6e81a793.png">

In case it's relevant this is printed in the terminal:
```
qt.qpa.fonts: Populating font family aliases took 780 ms. Replace uses of missing font family "Roboto" with one that exists to avoid this cost. 
qt.qpa.window: <QNSWindow: 0x7f8df636de00; contentView=<QNSView: 0x7f8df4bdd930; QCocoaWindow(0x600000b1a890, window=QWidgetWindow(0x600001844360, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
qt.qpa.window: <QNSWindow: 0x7f8df506fc10; contentView=<QNSView: 0x7f8df506f800; QCocoaWindow(0x600000b04840, window=QWidgetWindow(0x6000018b1620, name="CentralColumnWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
qt.qpa.window: <QNSWindow: 0x7f8df4bdb150; contentView=<QNSView: 0x7f8df638eca0; QCocoaWindow(0x600000b1eaa0, window=QWidgetWindow(0x6000018aebe0, name="QSplitterClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
qt.qpa.window: <QNSWindow: 0x7f8df5255a20; contentView=<QNSView: 0x7f8df5255610; QCocoaWindow(0x600000b10a50, window=QWidgetWindow(0x6000018a7540, name="MainWidgetWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
```

**Comment by chrytsi** [comment]
@adamltyson do you have any ideas as to what is going on?

**Comment by adamltyson** [comment]
> @adamltyson do you have any ideas as to what is going on?

Nope, but I can reproduce on Ubuntu 20.04. I don't think the font issue has anything to do with the problem though.

**Comment by FedeClaudi** [comment]
I could reproduce as well. Installing `PyQt==5.12.3` causes the GUI to not open at all. No error message, nothing, just python hanging.

With more recent versions I get the same as you
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/17436313/184169914-cf04c188-f9d0-4126-8e9e-067ca3e4946b.png">

However, if you click on `root` in the actors list on the right, a window with the rendered brain appears
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/17436313/184170106-9b444572-d395-4e14-9d7e-9b3b8a38d51f.png">

with these error messages
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/17436313/184170306-2f704348-1232-420b-86a2-1e76a0caac74.png">


The rest of the GUI seems to work fine...

---

So it seems like either the [`QFrame`](https://github.com/brainglobe/brainrender/blob/d9d0a5ceb3fbb3f64fad9b2691b8305ee8794eac/brainrender/gui/app.py#L44) or the `QVTKRenderWindowInteractor` are not displayed in the app and `vedo` creates a new window for the plotter when the brainrender scene gets updated. 

I don't think it is a brainrender issue, but I'm not sure what a fix could be. @marcomusy  did you ever see this behavior before>

**Comment by chrytsi** [comment]
Ah, yes that works!
Didn't see it before as the new window is tiny (see lower left corner of screenshot). :)
Thank you
<img width="1440" alt="Screenshot 2022-08-11 at 16 57 01" src="https://user-images.githubusercontent.com/34349487/184177387-6cc8dd58-9b11-4d62-b27e-340c35f53342.png">
!

**Comment by chrytsi** [comment]
Hi, 
I re-tried on Windows 10 and here no window gets opened, so it seems to not work on Windows 10.

**Comment by marcomusy** [comment]
> I don't think it is a brainrender issue, but I'm not sure what a fix could be. @marcomusy did you ever see this behavior before

uhm sorry, I've no idea why that happens.. you may wish to test one or more of the examples in
https://github.com/marcomusy/vedo/tree/master/examples/other
`qt_*.py`

**Comment by Ma-Bar** [comment]
Same problem here, on Ubuntu 20.04. However when I clicked on `root` in Actors list, the GUI window disappeared with the message in terminal: 
> Segmentation fault (core dumped)

**Comment by Tywang-720** [comment]
Hi:
I happened to solve this problem with an emprical way.
My system is Windows10. I ran brainrender from Anaconda3 (python 3.6).

I will descirbe the process below:
**First I tried the above methods (click root), but it gives no response.
Then I tried to roll back to history versions:
I sequentially installed brainrender 2.0.4.5, 2.0.4.7, 2.0.5.0, 2.0.5.1. None of those could open brainrender-gui on my machine.
Then I installed brainrender 2.0.5.3 again, this time brainrender could visualize the brain.**

Hope this information helps.

**Comment by Tywang-720** [comment]
> Hi: I happened to solve this problem with an emprical way. **My system is Windows10. I ran brainrender 2.0.5.3 from Anaconda3 (python 3.6).**
> 
> I will descirbe the process below: **First I tried the above methods (click root), but it gave no response. Then I tried to roll back to history versions: I sequentially installed brainrender 2.0.4.5, 2.0.4.7, 2.0.5.0, 2.0.5.1. None of those could open brainrender-gui on my machine. Then I installed brainrender 2.0.5.3 again, this time brainrender could visualize the brain.**
> 
> Hope this information helps.

So, it seems to me that, if one install brainrender 2.0.5.3 directly, then this issue would be there.
After he installed history versions of brainrender, then some missing part is back.

**Comment by FedeClaudi** [comment]
Hey, that's very weird I have no idea why installing it directly didn't work, but happy you've found a work around

**Comment by darikoneil** [comment]
I can confirm @Tywang-720 's fix worked for me as well (Windows 10, Python 3.7, PyCharm).  The only dependency that seems to change is that the terminal downgraded a vtk package when installing 2.0.4.5, otherwise it seems all requirements were satisfied. The downgrade to vtk 9.0.0 was kept with the final 2.0.5.3 version, so perhaps this is the issue.

**Comment by FedeClaudi** [comment]
got it, thanks.
