### ISSUE TITLE
Exporting rendering results

### ISSUE THREAD

**Issue by YuNangoChen** [brainglobe/brainrender#216]
Hey,

I tried this package and got beautifully rendered brains for schematics. It's really a great tool! Now, may I ask if it is possible to export the picture in a vector?  Since some journals ask for the specific format with a minimal resolution for graphics, that would be great if the rendering results can be saved not only in the bitmap. Thanks a lot!

**Comment by FedeClaudi** [comment]
Hi,

you can export scenes as screenshots saved to png files, but I think you know already . Unfortunately the rendering engine used by brainrender doesn’t support vector graphics yet though, sorry
