### ISSUE TITLE
PointsDensity gets rendered outside of brain

### ISSUE THREAD

**Issue by alexcalzoni** [brainglobe/brainrender#217]
**Describe the bug**
When rendering a scene with points and PointDensity, the points (cells) are rendered at the correct coordinates, while the density seems shifted by some amount.

**To Reproduce**
vedo version 2021.0.5; brainrender version 2.0.5.3; python 3.8; Windows 10

When I try the following code:
```
import numpy as np
import brainrender
from brainrender import Scene, Atlas, VideoMaker, Animation
from brainrender.actors import Points, PointsDensity
from rich import print
from myterial import orange
from pathlib import Path
import pandas as pd

print(f"[{orange}]Running example: {Path(__file__).name}")

#Settings for rendering
brainrender.settings.WHOLE_SCREEN = True  # If true render window is full screen
brainrender.settings.BACKGROUND_COLOR = "white"
brainrender.settings.DEFAULT_CAMERA = "three_quarters"
brainrender.settings.ROOT_COLOR = [0.9, 0.9, 0.9]  # color of the overall brain model's actor
brainrender.settings.ROOT_ALPHA = 0.1  # transparency of the overall brain model's actor'
brainrender.settings.SHOW_AXES = False
brainrender.settings.SHADER_STYLE = "cartoon"  # affects the look of rendered brain regions: [cartoon, metallic, plastic, shiny, glossy]
brainrender.settings.LW = .1  # e.g. for silhouettes
brainrender.settings.DEFAULT_ATLAS = "allen_mouse_10um"

def read_in_matlab_cells(filename):
    #col_list = ["X","Y","Z"]
    cells = pd.read_csv(filename, usecols=[1,2,3,4,5], names=["Ac","X","Y","Z","ID"],
                        skiprows = [0]) #skip header rows
    
    #filter out cells outside of the brain
    cells = cells[cells["ID"] != 1]
    
    if len(acronyms) > 0:
        cells = cells[cells["Ac"].isin(acronyms)]
    
    if cells.empty:
        pts = [[-10000, -10000, -10000]]
        return np.vstack(pts)
    else:
        X=cells["X"].tolist()
        Y=cells["Y"].tolist()
        Z=cells["Z"].tolist()
        
        #data is in mm, transform to um
        X = [element * (-1000) +5400 for element in X] 
        Y = [element * 1000 for element in Y]
        Z = [element * (1000) +5700 for element in Z]
        pts = [[x, y, z] for x, y, z in zip(X, Y, Z)]
        return np.vstack(pts)
    

#scene = Scene(title="")
scene = Scene(inset=False)
#Add some actors
scs=scene.add_brain_region("SCs", alpha=0.05, color="orange", hemisphere="both") #for SC visualization from above
scene.add_silhouette(scs, lw=2, color="darkgoldenrod")

coordinates_lat=read_in_matlab_cells(ntsr_lat)
coordinates_med=read_in_matlab_cells(ntsr_med)

# Add to scene
scene.add(Points(coordinates_lat, name="CELLS", colors="limegreen", alpha=0.8, radius=20))
scene.add(Points(coordinates_med, name="CELLS", colors="magenta", alpha=0.8, radius=20))
scene.add(PointsDensity(coordinates_lat))
scene.add(PointsDensity(coordinates_lat))

# render
scene.content
scene.render(camera="top", zoom=1)
```
I get the following output:
![brainrender_screenshot_20220901_185536](https://user-images.githubusercontent.com/112649691/187979654-7e10829e-982b-4afa-aee4-4ab9fa54ef94.png)
![brainrender_screenshot_20220901_185615](https://user-images.githubusercontent.com/112649691/187979657-65174ca8-c122-437e-916c-c5d7d33d6b12.png)

where the cell density is clearly shifted by some coordinates. Could anyone help me?

**Comment by FedeClaudi** [comment]
Hey, 

It seems like this is a bug, but I'm not sure where it's coming from. 
In the meanwhile, if you change the coordinates of the points before creating the density actor it should (should !) put it in the right place. You need to take the negative of the coordinates in one of the directions, not sure which of the axis it is though. 

Hope this helps.

**Comment by alexcalzoni** [comment]
Thanks for the fast reply. Following your suggestion, I managed to place the PointDensity in the correct place.
![brainrender_screenshot_20220902_133452](https://user-images.githubusercontent.com/112649691/188131107-b21ab8f0-ec80-49b7-a8ce-f7bf69ae81d2.png)
However, when I use the same settings to only visualize another brain area (e.g. visual cortex), the pointdensity function for one dataset is out of place again.
![brainrender_screenshot_20220902_133112](https://user-images.githubusercontent.com/112649691/188131433-7e2a12af-b272-4104-b0b0-392ccc726ecb.png)
Anyways, I will use your bgheatmap function for now, which works great.

**Comment by anandsku** [comment]
@alexcalzoni where can I find  the bgheatmap function you mention in your response? I am having similar issues with density being plotted outside the brain.

**Comment by adamltyson** [comment]
@anandsku [bgheatmap is a seperate tool](https://github.com/brainglobe/bg-heatmaps) that can be installed with `pip install bgheatmap`.

**Comment by anandsku** [comment]
@alexcalzoni Thanks for the info. From cursory reading, it seems that bg-heatmap is only for planar data. I need 3d density viz. Lemme figure out what transformation I need to apply, as suggested by Federico above.

**Comment by anandsku** [comment]
@alexcalzoni @FedeClaudi What works for me is translating the ML/LR coordinates 11175 or 11150 microns. Not sure why this intermediate number works as opposed to 11400, the full width of the ML aspect. Also, I cannot tell which one is better (11175 or 11150).
