### ISSUE TITLE
If I have all the location data array(ccf3 x,y,z) for one brain, how can i  only plot one brain region in python? Can anyone share some scripts?

### ISSUE THREAD

**Issue by Lynnsunny** [brainglobe/brainrender#218]
Thanks for the fast reply. Following your suggestion, I managed to place the PointDensity in the correct place.
![brainrender_screenshot_20220902_133452](https://user-images.githubusercontent.com/112649691/188131107-b21ab8f0-ec80-49b7-a8ce-f7bf69ae81d2.png)
However, when I use the same settings to only visualize another brain area (e.g. visual cortex), the pointdensity function for one dataset is out of place again.
![brainrender_screenshot_20220902_133112](https://user-images.githubusercontent.com/112649691/188131433-7e2a12af-b272-4104-b0b0-392ccc726ecb.png)
Anyways, I will use your bgheatmap function for now, which works great.

_Originally posted by @alexcalzoni in https://github.com/brainglobe/brainrender/issues/217#issuecomment-1235393494_

**Comment by Lynnsunny** [comment]
![python_t2HjtwdBSk](https://user-images.githubusercontent.com/47136605/193646126-50ecaaac-d3e5-4d7a-9f29-ee8e34561161.png)

**Comment by FedeClaudi** [comment]
Check the example [here](https://github.com/brainglobe/brainrender/blob/d9d0a5ceb3fbb3f64fad9b2691b8305ee8794eac/examples/add_cells.py#L25) for how to achieve this

**Comment by Lynnsunny** [comment]
I think i need to get the brain region's (e.g. ACB)  region_bounds, which in region.mesh.bounds(),

**Comment by Lynnsunny** [comment]
thank you for your reply

**Comment by Lynnsunny** [comment]
![image](https://user-images.githubusercontent.com/47136605/193649410-c2076bfd-c721-45a6-8ffe-1cedd6689407.png)

**Comment by FedeClaudi** [comment]
congrats!

**Comment by Lynnsunny** [comment]
very useful tool, thanks a lot, I have another question, how to get current camera parameter?  After i move the brain use my mouse, I press c ,but i can't see the  camera parameter in python console and the variable explorer(spyder)

**Comment by marcomusy** [comment]
> After i move the brain use my mouse, I press c

shouldn't it be shift-C

**Comment by Lynnsunny** [comment]
thank you for your reply, the problem have been solved, after  i press c, i can see the camera para in the console

**Comment by Lynnsunny** [comment]
![image](https://user-images.githubusercontent.com/47136605/199193011-a943ad12-ec64-4a27-b473-c3f236ea21ae.png)
 I wonder in the Cylinder function, how can i change the "pos " to only one side brain region?

**Comment by FedeClaudi** [comment]
You can pass [an array of coordinates](https://github.com/brainglobe/brainrender/blob/d9d0a5ceb3fbb3f64fad9b2691b8305ee8794eac/brainrender/actors/cylinder.py#L14) to cylinder.
