### ISSUE TITLE
BUG TypeError: __init__() got an unexpected keyword argument 'lexer_name'.

### ISSUE THREAD

**Issue by rcpeene** [brainglobe/brainrender#219]
**Describe the bug**
When running `scene.render()` in a Jupyter notebook using brainrender, I receive the following error; `TypeError: __init__() got an unexpected keyword argument 'lexer_name'`.

**To Reproduce**

1. Running brainrender 2.0.5.3 and vedo 2021.0.5
2. Clone this repo off of Github.
3. In the main directory, run jupyter notebook
4. Open getting_started.ipynb
5. In cell 2, change the argument in the call to embedWindow to 'k3d'
6. Run all the cells in order
7. See the resulting error from the last cell.

**Expected behavior**
I expect the window to render embedded within the notebook.

**Additional Context**
The [examples/notebook_workflow.ipynb](https://github.com/brainglobe/brainrender/blob/master/examples/notebook_workflow.ipynb) also yields this error when running locally on my machine.

**Traceback**
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [13], line 1
----> 1 scene.render()

File ~\Desktop\Projects\brainrender\brainrender\brainrender\render.py:244, in Render.render(self, interactive, camera, zoom, update_camera, **kwargs)
    241 self._apply_style()
    243 if self.inset and not self.is_rendered:
--> 244     self._get_inset()
    246 # render
    247 self.is_rendered = True

File ~\Desktop\Projects\brainrender\brainrender\brainrender\_jupyter.py:46, in not_on_jupyter.__call__(self, obj, *args, **kwargs)
     41     return self.func(obj, *args, **kwargs)
     42 else:
     43     print(
     44         f"[{orange_dark}]Cannot run function [bold {salmon}]{self.func.__name__}[/ bold {salmon}] in a jupyter notebook",
     45         f"[{orange_dark}]Try setting the correct backend before creating your scene:\n",
---> 46         Syntax("from vedo import embedWindow", lexer_name="python"),
     47         Syntax("embedWindow(None)", lexer_name="python"),
     48     )
     49     return None

TypeError: __init__() got an unexpected keyword argument 'lexer_name'
Desktop (please complete the following information):
```

**Comment by FedeClaudi** [comment]
Hi, 

The error seems to be due to the fact that newer versions of the `rich` library have changed the parameter name from `lexer_name` to `lexer` in `Syntax`: [see here](https://github.com/Textualize/rich/blob/594c06e5fc4d8872b6c9eb2d4f0260ac13fb0967/rich/syntax.py#L265). 

Downgrading to an older version of rich will fix this.

**Comment by rcpeene** [comment]
@FedeClaudi it looks like reverting rich to a version before this change would require going back at least 2 major versions, which might be incompatible with the rest of my environment. Any way this change could be made within brainrender?

**Comment by FedeClaudi** [comment]
Yes. It should be fairly easy to make a change to the call to `Syntax` as highlighted in the error stacktrace. Would you like to send in a PR?

**Comment by rcpeene** [comment]
PR made.

**Comment by rcpeene** [comment]
Closing, since this PR has been merged and the issue seems to be resolved.
