### ISSUE TITLE
Cannot connect and download atlas in certain country

### ISSUE THREAD

**Issue by Tywang-720** [brainglobe/brainrender#220]
Hi: Thanks for developing this wonderful tool.

I'm stationed in China and I found I could not download atlas such as "allen_mouse_25um", thus cannot use brainrender.

**Each time I run: "brainrender-gui" in cmd, it returns connection error.**

VPN doesn't seem to help either:  I have VPN and I have access to google.com in my browser but I cannot do this with brainrender. 

**Is it possible that these resources (all those needed in the pipeline) could be downloaded elsewhere that could be more easily reachable to Chinese users? (Such as shared in google drive ?)**

And If I managed to downloaded these resources by myself, where should I put these files locally?

Please help and let more people enjoy brainrender !

Thanks for any help！

**Comment by Tywang-720** [comment]
Update： I finally succeeded after several attempts in different VPN nodes.

The command I used :  **brainglobe install -allen_mouse_25um**
(I didn't succeed with “brainrender-gui” so I tried this. Not sure if this is important, just a note)

I think I can close this for now :)

**Comment by FedeClaudi** [comment]
happy you found a solution!
