### ISSUE TITLE
Progressive Slicing Animation

### ISSUE THREAD

**Issue by Bodhi-Rubinstein** [brainglobe/brainrender#221]
Hi!

I'm trying to replicate [this](https://www.youtube.com/watch?v=wTX_b4mJ_Co) progressive slicing animation from your paper and am having trouble. What is the best way to slice in between animation keyframes? Thanks so much for any help!

**Comment by FedeClaudi** [comment]
This is what I used: https://github.com/brainglobe/brainrender/blob/master/paper/videos/mouse_regions_video.py
