### ISSUE TITLE
Multiscene rendering not working

### ISSUE THREAD

**Issue by alexcalzoni** [brainglobe/brainrender#222]
Hi, first of all, thanks for brainrender, I've been able to create some amazing figures.

I was wondering if there is still an option for multiscene rendering? I've tried [this](https://github.com/marcomusy/BrainRender/blob/master/Examples/MultiScene.ipynb) tutorial but I get an import error stating "cannot import name 'MultiScene' from 'brainrender.scene'", as there is no class MultiScene in scene.py.
Is there a different way to render multiple instances of a scene?

**Comment by FedeClaudi** [comment]
Hi, 

I'm afraid this functionality is no longer supported. However brainrender relies quite heavily on vedo and vedo has support for multi-scene renderings. Perhaps you can work out a way to put the two together? Let me know if I can help
