### ISSUE TITLE
Hi. Just starting to use brainrender. I was using cocoframer before this. I am in Python version 3.9. I see that it requires Python version < 3.8. Does that mean it strictly won't work with 3.9 and should I downgrade my Jupyter notebook to Python 3.8? Thanks!

### ISSUE THREAD

**Issue by taningh86** [brainglobe/brainrender#230]

**Comment by taningh86** [comment]
I am getting some runtime errors so wondered if that is due to version incompatibility. I am also seeing some previous issues on matter somewhat similar to this and I am looking into them in detail to hopefully figure this out. In the meantime if there's a quick fix and smooth path with version 3.8 then I would rather go with that. Thanks!

**Comment by FedeClaudi** [comment]
yes please use 3.8
