### ISSUE TITLE
Rendering with labels not working

### ISSUE THREAD

**Issue by aboharbf** [brainglobe/brainrender#234]
Running some simple script in a .py file. 

![image](https://github.com/brainglobe/brainrender/assets/25850560/cbed5ca5-63bf-4545-a1fc-f0ba97adbb89)

I've been getting consistent errors around numpy, though attempts to downgrade it haven't worked. The main issue though is my attempts to add labels only seems to add silhouettes (It seems), and no labels.

![image](https://github.com/brainglobe/brainrender/assets/25850560/167c28a5-a42e-4fa5-b138-8a4cc5fe9fa4)

I am using the latest version of brainrender (2.0.5.5), vedo (2021.0.5), on a Windows 11 machine w/ an intel CPU and a GTX 3080. Any tips on how I can get things working would be excellent.

**Comment by aboharbf** [comment]
So having successfully downgraded numpy to 1.19.5, I'm now running into a problem simply importing 'Scene', which requires 'numpy.typing', itself introduced in numpy 1.20.

**Comment by adamltyson** [comment]
Hi @aboharbf,

I think these issues are now fixed in the latest release.

This script at least works: 

```python
from brainrender import Scene

scene = Scene()
th, mos = scene.add_brain_region("TH", "CA1", alpha=0.3)
scene.add_label(th, "Thalamus")
scene.add_label(mos, "CA1")

scene.render()
```
<img width="400" alt="labels" src="https://github.com/brainglobe/brainrender/assets/13147259/f1adf88d-6bed-48e4-87f1-dce71ddd7764">

If you have any further problems, please let us know.
