### ISSUE TITLE
[BUG] Points flickering between assigned color and black when recording video through Animation class regardless of frame rate

### ISSUE THREAD

**Issue by kgruver** [brainglobe/brainrender#236]
Hello!

Thank you so much for creating this beautiful and versatile package. I am trying to produce a video of my regions of interest and specified points at several given custom camera angles. However, when I use the Animation class to record a video (to access these specified camera parameters) rather than the VideoMaker class, my videos come out flickering, where the points that are assigned different color values based on their inputs, flicker black and back to their original color. This creates a distracting video rather than a clarifying one at the moment.

I wondered if this was a frame rate incompatibility issue between the speed at which the rendering moves and the frame rate used to create the video, but I can't seem to identify a suitable frame rate fps value. Using the default value also results in this flickering.  It also does not change if I switch the shading style between "plastic" or "default." 

I have been using Visual Studio Code to render the points and actors, so it is not Jupyter notebook issue. Ideally, the video will show the points at the designated colors at every captured frame, rather than flashing to black every other frame or so.

Here is my code where I populate a nucleus in the cerebellum with points representing cells:
https://github.com/kgruver/CN-neurons/blob/main/Sagittal_points_CB_feb2023_kim_allcells_video_withoutlobs.py

Here is the .csv file needed to reconstruct these specific points:
https://github.com/kgruver/CN-neurons/blob/main/kimscoordinatesthroughFeb2023_allcells.csv

I have also attached two screenshots showing this issue. The first shows the cells in color, and the second shows them flickering to black:

First:
<img width="1271" alt="Screen Shot 2023-03-17 at 11 28 18 AM" src="https://user-images.githubusercontent.com/55257289/225951795-4f201b3f-1730-4cbd-b7c9-ebcc5344e1ed.png">

Second:
<img width="1269" alt="Screen Shot 2023-03-17 at 11 28 27 AM" src="https://user-images.githubusercontent.com/55257289/225951823-4efba426-6dee-4e77-a9fa-2c1ecde85aef.png">

Thank you so much for your help!

Kim

--------------
Specs:

Computer: macOS v. 12.4, M1 CPU. 16 GB RAM. 

**Additional context**

**Comment by adamltyson** [comment]
Hi @kgruver,

Sorry for the delay. Unfortunately I can't access your script and data above to reproduce this issue. We've fixed many brainrender issues in the latest release, so could you try your example again?

If you have any further issues, please let us know.

Adam
