### ISSUE TITLE
[BUG] cell_density example is not working correctly

### ISSUE THREAD

**Issue by orena1** [brainglobe/brainrender#243]
**Describe the bug**
![image](https://github.com/brainglobe/brainrender/assets/8983713/09c324b8-d6a0-471c-b8c5-5aa8066f3986)

**To Reproduce**
`python examples\cell_density.py`

**Expected behaviour**
I assume the density map should overlap the brain, right?

**Computer used (please complete the following information):**
Windows 11

**Comment by adamltyson** [comment]
Hi @orena1,

We're aware of this issue ([and trying to fix it](https://github.com/brainglobe/brainrender/pull/235)). I think you should be able to get this working by installing some specific versions of packages, but I don't know exactly which ones. @FedeClaudi?

**Comment by orena1** [comment]
Thanks @adamltyson, yeah I understand the problem. Actually wanted to use `reconstruct_surface` from vedo, but the version that brainrender does not have it.
Good luck with updating the dependencies!

**Comment by alessandrofelder** [comment]
See possibly related discussion in https://github.com/brainglobe/brainrender/pull/235#issuecomment-1609774243
