### ISSUE TITLE
BUG Color not saved when exporing to html

### ISSUE THREAD

**Issue by orena1** [brainglobe/brainrender#245]
**Describe the bug**
When exporting to html, all colors are saved as blue:
<img width="355" alt="image" src="https://github.com/brainglobe/brainrender/assets/8983713/2dbf0edd-3bc8-4854-a9a3-866a230cda66">
[brain_regions.zip](https://github.com/brainglobe/brainrender/files/12589193/brain_regions.zip)

**To Reproduce**
```
In [3]: vedo.__version__
Out[3]: '2021.0.5'

In [4]: brainrender.__version__
Out[4]: '2.0.5.5'
```
Then tell us the steps to reproduce the behavior:
Add `.export("brain_regions.html")` to `brainrender\examples\brain_regions.py` before the `scene.render()` line
Than run
`brainrender\examples>python brain_regions.py`

**Comment by orena1** [comment]
@FedeClaudi any thoughts?

**Comment by adamltyson** [comment]
Hi @orena1,

I can't reproduce this issue, it seems to be fixed with the latest release. 

This script seems to work:

```
from brainrender import Scene

scene = Scene(title="HTML test")
scene.add_brain_region("TH", "CA1")
scene.export("brain_regions.html")
```

[brain_regions.html.zip](https://github.com/brainglobe/brainrender/files/13743723/brain_regions.html.zip)

**Comment by orena1** [comment]
yes @adamltyson working great now. Thanks
