### ISSUE TITLE
Installation & dependency issues

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/brainrender#247]
We are aware of a number of issues relating to basic brainrender functionality, including:
- Issues installing the package
- Dependency issues
- Basic rendering not working
- Issues with coordinate systems (brain the wrong way round, objects not in the correct place etc)

We are aware of these problems, but we have had limited resources to fix them. There is now a plan to address these issues over the coming weeks/months and bring brainrender back to a place where it is fully functional and easier to maintain.

In the mean time, please bear with us. If you have any issues similar to those listed above, please do not raise a new issue, but feel free to add a comment here to let us know. If you want to raise a pull request, please be aware that we may not be able to look at it until we have addressed some of the larger issues with the repo.

For now, please consider brainrender **unmaintained**. We will be unable to offer much user support until the underlying issues are fixed. 

To aid maintenance we also may remove some functionality that adds disproportionately to the maintenance burden. As an example, we may remove the brainrender GUI as this will eventually be replaced with the [brainrender napari plugin](https://github.com/brainglobe/brainrender-napari). Please let us know if any of these changes will cause issues.

We have started some of this work over at #235, if anyone else feels able to contribute, please get in touch.

**Comment by carlocastoldi** [comment]
I don't know if this issue is related or not to the _"basic rendering not working"_ problem, but over at `bg-heatmaps` there is a known bug (see https://github.com/brainglobe/bg-heatmaps/issues/11) caused by Vtk (vedo's dependency) where mesh intersection sometime fail and crash.

I did not fix it upstream, but over at `bg-heatmaps` I proposed (see https://github.com/brainglobe/bg-heatmaps/pull/16) to stop using square meshes for planes but use proper infinite/mathematical planes. A similar solution may be applied here, when possible.

**Comment by adamltyson** [comment]
Thanks @carlocastoldi. We will aim to fix brainrender and then look into other tools such as `bg-heatmaps`. Your comment in https://github.com/brainglobe/bg-heatmaps/pull/16 mentions backporting a binding from `vedo`. Do I understand correctly that https://github.com/brainglobe/bg-heatmaps/pull/16 could be simplified once we update version of `vedo` used by `brainrender`?

**Comment by adamltyson** [comment]
FYI @alessandrofelder  - https://github.com/brainglobe/brainrender/pull/246#issuecomment-1749197995

**Comment by carlocastoldi** [comment]
> Do I understand correctly that https://github.com/brainglobe/bg-heatmaps/pull/16 could be simplified once we update version of `vedo` used by `brainrender`

Yes, correct. However I don't know whether the maintainer of `bg-heatmaps` like my approach.
On the flip side I only really backported a single python binding to `vtk` (see https://github.com/carlocastoldi/bg-heatmaps/blob/ea7a847cad6800f8f30d41bd5bdc0be445dfe867/bgheatmaps/plane.py#L18). Nothing too big, about 30 lines! It's a native function that already exists in the vtk version installed with `vedo=2021.0.5`

**Comment by adamltyson** [comment]
> Yes, correct. However I don't know whether the maintainer of bg-heatmaps likes my approach or not. So my PR being simplified is dependant of on that 😁.

The maintainers of all repos in this org are now the same (chiefly @alessandrofelder and myself, with help from many others). We haven't had time to work on any of the brainrender-based tools, so sorry your PR has been ignored so far! We will focus on brainrender first though.

**Comment by carlocastoldi** [comment]
I totally get it, do worry!
I commted here referencing that issue only because i thought it was a solution worth looking if/when similar problems happen in brainrender
