### ISSUE TITLE
Change from `master` to `main`

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/brainrender#268]
Most, if not all, BrainGlobe repos use `main` as the default branch. It would be useful to do the same here. 

@alessandrofelder @IgorTatarnikov I haven't done this myself to not complicate your current branch workflow.

**Comment by alessandrofelder** [comment]
Done

Instructions to move branch name on local clones below:
```bash
git branch -m mainmaster main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
