### ISSUE TITLE
test_scene::test_scene_screenshot fails on Windows CI run

### ISSUE THREAD

**Issue by IgorTatarnikov** [brainglobe/brainrender#270]
test_scene::test_scene_screenshot fails when run on Windows CI. This cannot be reproduced locally, but can be reproduced using a tmate session on the runner.

The code fails on a seg fault, in a call to vtk.WindowToImageFilter().Update(). We used the debugger to make sure all attributes are set correctly/not null before this call. We tried running the tests for the latest development version of vedo on the Windows CI runner and a similar seg faul happens, superficially in plotter:render.show() which migh end up at the same vtk function underneath.

In https://github.com/brainglobe/brainrender/tree/windows-test-scene-screenshot we tried to pass the same env variables to tox as brainrender-napari in case it was a tox configuration issue with no success. 

This might be an interaction between vtk and the Windows runner, can look into opening issues on vedo/vtk.

**Comment by alessandrofelder** [comment]
> I think this is probably vtk behaving differently on different systems.

Thanks for this clue, @marcomusy - this helped me figure out that we needed to ensure vtk and the headless display work well together, and therefore reminded me of the `pyvista` GH action that sets up headless displays for the `napari` CI.
