### ISSUE TITLE
Brainrender example showing output of `brainglobe-segmentation` data

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/brainrender#280]
The text below was removed from the `brainglobe-segmentation` tutorials, but may be handy as an example for `brainrender` or `brainrender-napari` one day:

>if you loaded your data in atlas space, you can also export the track to [brainrender](/documentation/brainrender/index). The file will be saved as e.g. `track_0.npy`. Using the Python API, you can visualise the track as follows:

```python
from brainrender import Scene
from brainrender.actors import Points
from myterial import blue

file = ("/path/to/track_0.npy")

scene = Scene()
scene.add(Points(file, colors=blue, radius=100, alpha=0.7))
scene.render()
```

**Comment by adamltyson** [comment]
Closing, and addressed in #313
