### ISSUE TITLE
[Feature] improve testing set-up

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/brainrender#285]
**Is your feature request related to a problem? Please describe.**
By default, not all tests are run, neither in a local development environment nor on CI. You need to specify `--runlocal --runslow` to `pytest`.

**Describe the solution you'd like**
Either all tests are run always, or all tests are run by default locally (but not on CI)

**Additional context**
* See https://github.com/brainglobe/brainrender/pull/284#discussion_r1409381890
* also consider that using `pooch` and shipping example data in `mega-fix` should render at least the `--runlocal` part obsolete.

**Comment by adamltyson** [comment]
FYI we do have a convention here: https://brainglobe.info/community/developers/testing.html#long-running-tests

**Comment by adamltyson** [comment]
Just bumping this. Basically all the "slow" tests fail, but they're rarely run, so they may as well not be there.
