### ISSUE TITLE
[BUG] Brainrender GUI not displaying meshes correctly

### ISSUE THREAD

**Issue by IgorTatarnikov** [brainglobe/brainrender#286]
**Describe the bug**
After running `brainrender-gui` the GUI opens up, but the root mesh doesn't show at all. See below:

![Screenshot 2023-11-30 102045](https://github.com/brainglobe/brainrender/assets/61896994/8a4a27d8-240d-4c63-b2fc-184655f5797e)

**To Reproduce**
Run `brainrender-gui` in the terminal.

**Expected behaviour**
The GUI should open, with the root mesh visible.

**Computer used (please complete the following information):**

- OS: Tried on both Windows and MacOS, with PyQT5 or PySide2.

**Additional context**
This can be partly fixed by editing [these lines](https://github.com/brainglobe/brainrender/blob/5a8418c1a81953588d701bc5075bd0dfefc98e05/brainrender/gui/app.py#L45)
From:
```
        frame = QFrame()
        self.vtkWidget = QVTKRenderWindowInteractor(frame)
```
To:
```
        self.frame = QFrame()
        self.vtkWidget = QVTKRenderWindowInteractor(self.frame)
```

With this change, the plotter widget now shows up in the GUI.

![Screenshot 2023-11-30 103218](https://github.com/brainglobe/brainrender/assets/61896994/f3fd0ad1-0777-4047-838c-c996d2276741)

To get the root to render, we either have to set `immediate_rendering` to `True` in `brainrender/settings.py` or insert a `self.scene.plotter.window.Render()` somewhere in `brainrender/gui/app.py`. I'm not happy with these results because the rendering looks off, and doesn't behave as expected when toggling the visibility of meshes.

https://github.com/brainglobe/brainrender/assets/61896994/b0d8c2eb-41b5-4070-b3c4-5e09d5ee7189

I think this can be solved by finding the correct place to call the `Render()` method, or by clearing the plotter completly after each update.

**Comment by adamltyson** [comment]
@brainglobe/active-devs we've discussed this before, but shall we finally remove the GUI and focus on maintaining the Python API and developing `brainrender-napari`?

**Comment by alessandrofelder** [comment]
Fine by me. I'd suggest
* deprecating the GUI functionality + making a release
* remove GUI code
* release when `brainrender-napari` has replacements for
	* `Add cells`
	* `Add from file`

I will prioritise these feature in `brainrender-napari` once I've closed https://github.com/brainglobe/brainrender-napari/issues/21

(We'll rely on `napari` to edit the actor properties)

**Comment by adamltyson** [comment]
> release when brainrender-napari has replacements for
>
>    Add cells
>    Add from file

@alessandrofelder considering the GUI is broken, we should be able to release a version without the GUI anytime no? Or do you just want to announce it all together?

**Comment by alessandrofelder** [comment]
Some parts of the GUI seem to be working in the video above? Do we have an idea whether people are using the GUI? Those are the people I would have wanted to warn with a deprecation warning... I don't have a strong opinion on this though, and if we feel it not worth the overhead, I am happy to remove in one step 🤷

**Comment by adamltyson** [comment]
> Some parts of the GUI seem to be working in the video above? 

I think that's only after @IgorTatarnikov's fiddling. It doesn't work for me out of the box.

> Do we have an idea whether people are using the GUI?

I doubt it, considering it's been broken for a long time.
