### ISSUE TITLE
[BUG]I found the one error when I tried to install brainrender in the terminal. 

### ISSUE THREAD

**Issue by ZChen90** [brainglobe/brainrender#292]
Hi,
I found one error when I tried to install brainrender in the terminal (as shown below). 
My computer is mac. The version is MaxOS Moneterey 12.3 It is M1 CPU. The memory is 16GB. I am using python 3.12. 
I checked on the internet and found that I can try to solve the problem by upgrading pip, but unfortunately the error is still there after pip was upgraded.  Could you please give me some advice about it? Thanks a lot!

I got this error after i entering " pip install brainrender".

**The error is as follows:**

error: subprocess-exited-with-error
 
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

Best regards,
Chen

```[tasklist]
### Tasks
```

**Comment by adamltyson** [comment]
Hi @ZChen90, BrainGlobe doesn't yet support Python 3.12. Could you try creating a Python 3.11 environment, and running `conda install hdf5` first before installing brainrender?
