### ISSUE TITLE
Remove paper & benchmark scripts

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/brainrender#305]
Currently both these set of scripts do not run, and haven't been updated in years. I also think they're not the top priority when it comes to maintaining this package. We should focus on making sure the examples always run smoothly. 

I suggest we remove these sets of files. They will be available within the git history, and in releases in case anybody wants them ( I would gues not?).

cc @brainglobe/active-devs

**Comment by IgorTatarnikov** [comment]
I agree, I think focusing on the examples is the best idea!
