### ISSUE TITLE
allen_cord_20um atlas weird lookup_df

### ISSUE THREAD

**Issue by RobertoDF** [brainglobe/brainrender#361]
Hi!
I am trying to use the [heatmap](https://github.com/brainglobe/brainglobe-heatmap), but if I set the atlas like this it raise an error due to the acronym (TH for example) not being present in the lookout_df:

```
values = dict(  # scalar values for each region
    TH=1,
    RSP=0.2,
    AI=0.4,
    SS=-3,
    MO=2.6,
    PVZ=-4,
    LZ=-3,
    VIS=2,
    AUD=0.3,
    RHP=-0.2,
    STR=0.5,
    CB=0.5,
    FRP=-1.7,
    HIP=3,
    PA=-4,
)


scene = bgh.Heatmap(
    values,
    position=(8000, 5000, 5000),
    orientation="frontal",  # or 'sagittal', or 'horizontal' or a tuple (x,y,z)
    thickness=1000,
    title="frontal",
   atlas_name="allen_cord_20um"
    vmin=-5,
    vmax=3,
    format="3D",
)
```

The lookout_df indeed contains only "weird acronyms":
```
atlas = Atlas(atlas_name="allen_cord_20um")
atlas.lookup_df:
acronym	id	name
1Sp	1	Lamina 1
2Ssp	2	Lamina 2 Outer part
2Spl	3	Lamina 2 Inner part
3Sp	4	Lamina 3
4Sp	5	Lamina 4
IB	6	Internal basilar nucleus_4Sp
5Sp	7	Lamina 5
5SpL	8	Lamina 5 Lateral part
5SpM	9	Lamina 5 Medial part
D	10	Dorsal nucleus (Clarke)_5Sp
```

- OS: Linux
brainglobe-atlasapi       2.0.6                    pypi_0    pypi
brainglobe-heatmap        0.5.3                    pypi_0    pypi
brainglobe-space          1.0.2                    pypi_0    pypi
brainglobe-utils          0.5.0                    pypi_0    pypi
brainrender               2.1.9                    pypi_0    pypi

**Comment by alessandrofelder** [comment]
(Not an expert neuroanatomist) are those acronyms not what is expected for the allen spinal cord atlas @RobertoDF?
Are you wanting to use a spinal cord or a brain atlas?
