### ISSUE TITLE
504 Gateway Time-out at https://gin.g-node.org/brainglobe/atlases

### ISSUE THREAD

**Issue by dylanablack** [brainglobe/brainrender#374]
When trying to run brainrender via napari, I receive a MissingSectionHeaderError: 

```
MissingSectionHeaderError: File contains no section headers.
file: '<string>', line: 1 <html><body><h1>504 Gateway Time-out</h1>\n
```

I will provided system and installation information (and full error output) if helpful but I suspect this is an error on the GIN side?

https://gin.g-node.org/brainglobe/atlases does not load via browser.

**Comment by alessandrofelder** [comment]
Thanks for reporting @dylanablack - yep looks like it was down for a bit, but back up now. We have no control over GIN itself, so :crossed_fingers: this doesn't happen again. We will hopefully one-day find time to address [the issue](https://github.com/brainglobe/brainglobe-atlasapi/issues/142) to make the atlas API more robust to internet problems.
