### ISSUE TITLE
Imported cell mis-alignment from Wholebrain

### ISSUE THREAD

**Issue by sgoldenlab** [brainglobe/brainrender#38]
We have several datasets where cells have been segmented and then reverse-warped back into the ABA CCF space using Wholebrain (https://www.nature.com/articles/s41593-017-0027-7). 

When we load these datasets using `scene.add_cells_from_file` in BrainRender the cells appear to be offset.
![image](https://user-images.githubusercontent.com/50497030/75916741-bf94b080-5e0d-11ea-888a-a77b1da255ec.png)

This is probably an issue with Wholebrain, rather than BrainRender, but wanted to run it paste you as well since both should be using the identical ABA CCF coordinates.  Happy to share datasets and further describe the issue.

**Comment by FedeClaudi** [comment]
Hi, thanks for trying brainrender out. 

From the image it looks like the cells are shifted medio-laterally but otherwise in place, is that correct or are they shifted along different axes?

Every labelled cells dataset I've used so far was generated with cellfinder (https://github.com/SainsburyWellcomeCentre/cellfinder), and I never encountered this problem before. Given that brainrender is simply taking the coordinates it is passed and rendering sphere where each cell is located, I'm afraid that the problem might be with how the registration was done. 
@adamltyson  has a lot more experience than me on image/whole-brain registration, maybe he can weigh in with some advice. 

I'd be happy to have a look at the code you're using to render these cells + the dataset you're using if you think that could help.

**Comment by adamltyson** [comment]
Hi both. I’m away at the moment, but I’m having a call with Daniel Furth next week to discuss wholebrain/cellfinder interoperability. Once I’m more familiar with wholebrain, I should be able to sort this out

**Comment by sgoldenlab** [comment]
Thanks both. It's got to be a simple difference in the coordinate system being used between the two, as the slices are registered appropriately in Wholebrain.  

![image](https://user-images.githubusercontent.com/50497030/75923244-88c49780-5e19-11ea-84ca-8e46777a9f78.png)

Side note, just for fun, I threw a ClearMap dataset in as well. Sort of the same issue, but I've asked Christoph Kirst to take a look and see if the appropriate coordinates are available anywhere else that I could not find them.

![image](https://user-images.githubusercontent.com/50497030/75923332-b01b6480-5e19-11ea-87f1-f2bad27f4df1.png)

Thank you for looking into the compatibility of the different systems. My lab will try CellFinder soon, which will give us a better comparison.

**Comment by FedeClaudi** [comment]
Very interesting, thanks for looking into this in more detail [and very cool visualisation from WholeBrain!]. 

I will close this for now as it doesn't seem to be a brainrender issue. 
Until a more definitive solution is found, if you need to visualise data in brainrender you can always scale/shift the row data as necessary. It's not ideal and it won't be too accurate, but for a quick visualisation it should work.

**Comment by adamltyson** [comment]
Hi @sgoldenlab. I’ll forget about this. Please remind me, I want to get wholebrain/clearmap/cellfinder/brainrender as integrated as possible.

**Comment by sgoldenlab** [comment]
@adamltyson Will do, and I'll send a reminder about the datasets we uploaded for CellFinder as well.  Enjoy the rest of your travels!

**Comment by sgoldenlab** [comment]
Hi Adam and Fede, bumping this as the requested reminder. Thanks!

**Comment by adamltyson** [comment]
No results, but just to say that I've spoken to Daniel Furth and Christoph Kirst about this (and other issues of compatibility), and I'm aiming to get everything working together properly (not sure when though).

**Comment by sgoldenlab** [comment]
Hey Adam, just bugging you mostly so this stays on the radar :) Also, even if you dont have time to look into this now, could you give me some direction on what is causing the mis-alignment, especially with Clearmap? We could take a swing at it with a bit more direction.

**Comment by adamltyson** [comment]
Hi Sam,

No worries, thanks for reminding me. Could you email me:
* The output cell positions from wholebrain
* The output cell positions from clearmap
* The scripts you used to load them into brainrender

Thanks!

**Comment by adamltyson** [comment]
@FedeClaudi I know this isn't a BR issue, so feel free to close it, but it would be cool to get this working.

**Comment by FedeClaudi** [comment]
No problem, lets leave it open so that we can keep an eye on it. Let me know if I can help somehow

**Comment by FedeClaudi** [comment]
See https://github.com/BrancoLab/BrainRender/issues/63 for another example of an user experiencing the same issue

**Comment by macaskill-lab** [comment]
just as a random add-on to this. we also have been importing from wholebrain - the issue seens to be that wholebrain treats allen as mirrored at midline, while brainrender plots from leftmost coordinate? midline seems to be like ~ 5.8 mm?

**Comment by FedeClaudi** [comment]
Hi, just so that I understand: wholebrain sets the origin of the medio-lateral axis along the midline? The origin in brainrender is as set by the allen at one corner of the voxel space.

**Comment by macaskill-lab** [comment]
yep at least in the way we output the data - i think the rationale was that you could easily combine counts across all hemispheres - could just be our random code though! 

but at first glance ours looks the same as sams - we are offest by around 5 mm

**Comment by FedeClaudi** [comment]
I see. Okay, thanks for the update. If anyone finds a transform matrix that takes wholebrain's out and aligns it to brainrender's renderings (or vice versa) I can easily add some code that makes use if it to align the visualizations.
