### ISSUE TITLE
remove imio dependency

### ISSUE THREAD

**Issue by carlocastoldi** [brainglobe/brainrender#384]
hi!
I was trying to update my project to numpy 2.0+ and noticed that my building tool (poetry) was downgrading some ~unmaintained libraries like `nptyping`. I then noticed that that is due to `brainrender` still depending on `imio` even though, to my understanding, all its functionaliesi were included into `braiglobe-utils`
Am I missing something? Do you think that `brainrender` can completely ditch `imio` too?

Thanks in advance!

**Comment by alessandrofelder** [comment]
Yep that should be possible indeed. I'll make a PR.

**Comment by alessandrofelder** [comment]
I've released the fixed version - thanks again for reporting @carlocastoldi and shout if anything breaks :)
