### ISSUE TITLE
[Feature] Flipping single neurons

### ISSUE THREAD

**Issue by CaroniLab** [brainglobe/brainrender#389]
Hi, is there an easy way to flip the neuron actor (neuron morphology loaded from an SWC file) so the soma is in the opposite hemisphere.

A way to flip any actor to the opposite hemisphere would be very much appreciated!

Alternatively, I would need to load the swc and slip it and I cannot find an easy way with morphapi to flip the morphology either.

Thanks!

**Comment by IgorTatarnikov** [comment]
Hi @CaroniLab, thank you for the suggestion!

We've implemented a new method to flip actors in `brainrender` v2.1.15, you can update with `pip install brainrender -U`.

Please see https://github.com/brainglobe/brainrender/blob/main/examples/mirror_actors.py for example usage.
