### ISSUE TITLE
Rendering a half of the brain

### ISSUE THREAD

**Issue by jt522** [brainglobe/brainrender#72]
Thank you for sharing the great code! 
I've been using Brainrender and it works fantastic.

I was wondering if it is possible to render only a part of the brain.
Specifically, I would like to render only the left or right side of the brain.
This is because when I plot labeled neurons in the brainstem and see from the sagittal, the paraflocculus obscures the view.

Thanks!

**Comment by FedeClaudi** [comment]
Hey thanks, that's great to hear!

Yep you can do that, there's two examples of how to use planes to cut actors in a scene ([here](https://github.com/BrancoLab/BrainRender/blob/master/Examples/basic/cut_with_plane1.py) and [here](https://github.com/BrancoLab/BrainRender/blob/master/Examples/basic/cut_with_plane2.py)).

Below is a reworked example showing how to cut the root and region meshes along the sagittal plane and display some cell locations. Note that you want to do the cutting **before** you add the cells to the scene or you'll be cutting the actor that shows the cell location as well.  Alternatively you can do the cutting later on and pass a list of actors to cut to `scene.cut_actors_with_plane` with the `actor` keyword argument [actors not in the list will not be affected]. 

P.s.: you'll need the latest version of brainrender for this to work so: `pip install -U brainrender`


### Example code
```
import pandas as pd

import brainrender
brainrender.SHADER_STYLE = 'cartoon'

from brainrender.scene import Scene


regions = ['GRN', 'PRNc', 'PRNr']

scene = Scene()

# Add some actors
root = scene.actors['root']
regs = scene.add_brain_regions(regions, alpha=.2)

# Cut with plane
scene.cut_actors_with_plane('sagittal', showplane=False) # Set showplane to True if you want to see the plane location
sil = root.silhouette().lw(1).c('k')
sil2 = [act.silhouette().lw(1).c('k') for act in regs]
scene.add_vtkactor(sil, *sil2)

# Get fake cell coordinates
cells = [] # to store x,y,z coordinates
for region in regions:
    region_cells = scene.get_n_random_points_in_region(region=region, N=1000, hemisphere='right')
    cells.extend(region_cells)
x,y,z = [c[0] for c in cells], [c[1] for c in cells], [c[2] for c in cells]
cells = pd.DataFrame(dict(x=x, y=y, z=z)) # ! <- coordinates should be stared as a pandas dataframe



# Add cells
scene.add_cells(cells, color='darkseagreen', res=12, radius=25)



scene.render(camera='top')
```

-----------------------------------
If you want to get the other half of the brain after cutting, you'll have to use a plane with the normal pointing in the opposite direction of what's used for sagittal by default. So you want to do something like this:

```
pos = scene.atlas._root_midpoint
sx, sy = 15000, 15000
norm = [0, 0, -1]
plane = scene.atlas.get_plane_at_point(pos, norm, sx, sy, color='lightblue')
scene.cut_actors_with_plane(plane, close_actors=False, 
                showplane=True, actors=scene.actors['root'])
```

Hope this helps, let me know if you have any question

**Comment by jt522** [comment]
Thanks for your quick response!
It works very well. I have two questions.

When I render the left side, regions (nuclei) on the right side are still visible. How can I remove them?

Also, is it possible to remove black lines around regions?

Thanks!

**Comment by FedeClaudi** [comment]
The black lines are added with these lines:
```
sil = root.silhouette().lw(1).c('k')
sil2 = [act.silhouette().lw(1).c('k') for act in regs]
scene.add_vtkactor(sil, *sil2)
```

So you can just omit those and you won't have the lines. 

When you call `scene.cut_actors_with_plane`, it will cut all the actors that have been added to scene up to that point (unless you pass a list of actors as a keyword argument). So you want to make sure to call `scene.add_brain_regions` before `scene.cut_actors_with_plane`

If this doesn't work perhaps you can copy/paste the code you're using so that I can see what's going wrong.

**Comment by jt522** [comment]
Thanks! Regions still don't go away.
Here is my code.

# Create a scene
scene = Scene(jupyter=True)
scene.screenshots_folder
# Define in which regions to crate the cells and how many
regions = ["XII", "VII", "AMB" ]

# Add some actors
root = scene.actors['root']
regs = scene.add_brain_regions(regions, alpha=.2)

# Cut with plane - left side
pos = scene.atlas._root_midpoint
sx, sy = 15000, 15000
norm = [0, 0, -1]
plane = scene.atlas.get_plane_at_point(pos, norm, sx, sy, color='lightblue')
scene.cut_actors_with_plane(plane, close_actors=True, 
                showplane=False, actors=scene.actors['root'])

scene.add_cells(file_names[0], color="magenta", radius = 14, res = 30);
scene.add_cells(file_names[1], color="aqua", radius = 14, res = 30);
scene.add_cells(file_names[2], color="gold", radius = 14, res = 30);

scene.render() 
vp = Plotter(axes=0)
vp.show(scene.get_actors())

**Comment by FedeClaudi** [comment]
The problem is with this line:
```
scene.cut_actors_with_plane(plane, close_actors=True, showplane=False, 
actors=scene.actors['root'])
```

By passing `actors=scene.actors['root']` you're saying that you want only the brain outline to be cut. If you change that line to:
```
scene.cut_actors_with_plane(plane, close_actors=True, showplane=False)
```
all actors will be cut. 

I also suggest setting `close_actors=False` for better visualisation.

**Comment by jt522** [comment]
It works great now. Thanks!
One last thing, it is possible to remove the line circled in the attached image?
<img width="880" alt="image" src="https://user-images.githubusercontent.com/13648214/82765404-b6035f00-9de4-11ea-951a-e8976ad77669.png">

**Comment by FedeClaudi** [comment]
mmm I don't know where the circle comes from. Does it appear with the same code as you've sent above?

**Comment by jt522** [comment]
I didn't explain well. I meant the rectangle shaped shadow between the cerebellum and hypothalamus.

**Comment by FedeClaudi** [comment]
Ah, I see sorry I didn't read your message correctly. Have you tried setting `close_actors=False`?

**Comment by jt522** [comment]
It disappeared with "close_actors=False". 
I think my problems are all solved.
Thanks a lot!

**Comment by FedeClaudi** [comment]
Great!

**Comment by blogeman** [comment]
Thanks for this great piece of software and congrats on the publication. I'm re-opening this comment sense it appears that the switch from V1->V2 requires some adjustments to slicing the root. After running scene.get_actors() I can see 'brainrender.Actor: root-brain region' is one of my Actors, but when passing it to .slice() I get the following error 

'str' object has no attribute '_mesh'

Any suggestions are much appreciated.

**Comment by FedeClaudi** [comment]
Hi, 

how are you trying to do this? Could you share an example code?

**Comment by blogeman** [comment]
Hi @FedeClaudi, thanks for the reply. I was able to (mostly) figure this out by going through the examples you have posted using V2. Posting the code I used below for posterity.

`import pandas as pd

import brainrender
brainrender.SHADER_STYLE = 'cartoon'

from brainrender.scene import Scene
from vedo import embedWindow
embedWindow(None) 

scene = Scene()

# Add some actors
scene.add_brain_region("GRN", "PRNc", "PRNr", alpha=0.2, color="green")
actors = [a for a in scene.actors]

# Cut with plane
scene.slice('sagittal', actors=actors, close_actors=True)

scene.render(camera='top')`

**Comment by FedeClaudi** [comment]
Thanks, get in touch if you have any other question
